BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "TestIdTrun"

BeforeExecute
-- SapHana.Native SapHana

CREATE COLUMN TABLE "TestIdTrun"
(
	"ID"     Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Field1" Decimal                                  NOT NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "TestIdTrun"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "TestIdTrun"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @take  -- Int32
SET     @take = 2
DECLARE @skip  -- Int32
SET     @skip = 1

SELECT
	"t1"."ID",
	"t1"."Field1"
FROM
	"TestIdTrun" "t1"
ORDER BY
	"t1"."ID"
LIMIT :"take" OFFSET :"skip"

BeforeExecute
-- SapHana.Native SapHana

DELETE FROM "TestIdTrun"

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "TestIdTrun"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "TestIdTrun"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @take  -- Int32
SET     @take = 2
DECLARE @skip  -- Int32
SET     @skip = 1

SELECT
	"t1"."ID",
	"t1"."Field1"
FROM
	"TestIdTrun" "t1"
ORDER BY
	"t1"."ID"
LIMIT :"take" OFFSET :"skip"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "TestIdTrun"

