BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DynamicParent"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "DynamicParent"
(
	"ID" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DynamicChild"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "DynamicChild"
(
	"ID"       Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ParentID" Integer                                  NOT NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc (asynchronously)

SELECT
	"it"."ID"
FROM
	"DynamicParent" "it"
		LEFT JOIN "DynamicChild" "a_Child" ON "it"."ID" = "a_Child"."ParentID"
WHERE
	"a_Child"."ID" = 123

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DynamicChild"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DynamicParent"

