BeforeExecute
-- Oracle.11.Managed Oracle11

DELETE FROM
	LINQDATATYPESBC t1

BeforeExecute
INSERT BULK LINQDATATYPESBC(ID, MONEYVALUE, DATETIMEVALUE, DATETIMEVALUE2, BOOLVALUE, GUIDVALUE, SMALLINTVALUE, INTVALUE, BIGINTVALUE, STRINGVALUE)

BeforeExecute
-- Oracle.11.Managed Oracle11

DELETE FROM
	LINQDATATYPESBC t1

