-- Oracle.11.Managed Oracle11

DELETE FROM
	SEQUENCETEST t1
WHERE
	t1.VALUE = 'SeqValue'

-- Oracle.11.Managed Oracle11

SELECT SEQUENCETESTSEQ.nextval ID from DUAL connect by level <= 4

-- Oracle.11.Managed Oracle11

INSERT ALL
	INTO SEQUENCETEST (ID, VALUE) VALUES (43,'Value')
	INTO SEQUENCETEST (ID, VALUE) VALUES (44,'Value')
	INTO SEQUENCETEST (ID, VALUE) VALUES (45,'Value')
	INTO SEQUENCETEST (ID, VALUE) VALUES (46,'Value')
SELECT * FROM dual

