-- Oracle.11.Managed Oracle11

SELECT user FROM dual

-- Oracle.11.Managed Oracle11

GRANT CREATE ANY TRIGGER TO TEST

-- Oracle.11.Managed Oracle11

GRANT CREATE ANY SEQUENCE TO TEST

-- Oracle.11.Managed Oracle11

GRANT DROP ANY TRIGGER TO TEST

-- Oracle.11.Managed Oracle11

GRANT DROP ANY SEQUENCE TO TEST

-- Oracle.11.Managed Oracle11

DROP USER C##ISSUE723SCHEMA CASCADE

-- Oracle.11.Managed Oracle11

CREATE USER C##ISSUE723SCHEMA IDENTIFIED BY password

-- Oracle.11.Managed Oracle11

SELECT default_tablespace FROM sys.dba_users WHERE username = 'C##ISSUE723SCHEMA'

-- Oracle.11.Managed Oracle11

ALTER USER C##ISSUE723SCHEMA quota unlimited on SYSTEM

-- Oracle.11.Managed Oracle11

CREATE TABLE C##ISSUE723SCHEMA.ISSUE723TABLE
(
	"Id" Int  NOT NULL,

	CONSTRAINT PK_ISSUE723TABLE PRIMARY KEY ("Id")
)

-- Oracle.11.Managed Oracle11

CREATE SEQUENCE C##ISSUE723SCHEMA.SIDENTITY_ISSUE723TABLE

-- Oracle.11.Managed Oracle11

CREATE OR REPLACE TRIGGER C##ISSUE723SCHEMA.TIDENTITY_ISSUE723TABLE
BEFORE INSERT ON C##ISSUE723SCHEMA.ISSUE723TABLE FOR EACH ROW
BEGIN
	SELECT C##ISSUE723SCHEMA.SIDENTITY_ISSUE723TABLE.NEXTVAL INTO :NEW."Id" FROM dual;
END;

-- Oracle.11.Managed Oracle11
DECLARE @IDENTITY_PARAMETER Decimal
SET     @IDENTITY_PARAMETER = NULL

INSERT INTO C##ISSUE723SCHEMA.ISSUE723TABLE VALUES (DEFAULT)
RETURNING 
	"Id" INTO :IDENTITY_PARAMETER

-- Oracle.11.Managed Oracle11
DECLARE @IDENTITY_PARAMETER Decimal
SET     @IDENTITY_PARAMETER = NULL

INSERT INTO C##ISSUE723SCHEMA.ISSUE723TABLE VALUES (DEFAULT)
RETURNING 
	"Id" INTO :IDENTITY_PARAMETER

-- Oracle.11.Managed Oracle11

BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER C##ISSUE723SCHEMA.TIDENTITY_ISSUE723TABLE';
	EXECUTE IMMEDIATE 'DROP SEQUENCE C##ISSUE723SCHEMA.SIDENTITY_ISSUE723TABLE';
	EXECUTE IMMEDIATE 'DROP TABLE C##ISSUE723SCHEMA.ISSUE723TABLE';
END;

-- Oracle.11.Managed Oracle11

DROP USER C##ISSUE723SCHEMA CASCADE

