-- Oracle.11.Managed Oracle11
DELETE FROM
	SEQUENCETEST t1
WHERE
	t1.VALUE = 'SeqValue'

-- Oracle.11.Managed Oracle11
SELECT SEQUENCETESTSEQ.nextval ID from DUAL connect by level <= 4

-- Oracle.11.Managed Oracle11
INSERT INTO SEQUENCETEST
(
	ID,
	VALUE
)

	SELECT 71,'Value' FROM DUAL  UNION ALL
	SELECT 72,'Value' FROM DUAL  UNION ALL
	SELECT 73,'Value' FROM DUAL  UNION ALL
	SELECT 74,'Value' FROM DUAL 

