-- Oracle.11.Managed Oracle11

DELETE FROM
	LINQDATATYPESBC t1

INSERT BULK LINQDATATYPESBC(ID, MONEYVALUE, DATETIMEVALUE, DATETIMEVALUE2, BOOLVALUE, GUIDVALUE, SMALLINTVALUE, INTVALUE, BIGINTVALUE, STRINGVALUE)

-- Oracle.11.Managed Oracle11

DELETE FROM
	LINQDATATYPESBC t1

