BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE NC_CODE';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE NC_CODE
		(
			HANDLE             NVarChar(255) NOT NULL,
			CHANGE_STAMP       Decimal           NULL,
			SITE               NVarChar(18)      NULL,
			NC_CODE            NVarChar(48)      NULL,
			DESCRIPTION        NVarChar(120)     NULL,
			STATUS_BO          NVarChar(255)     NULL,
			CREATED_DATE_TIME  timestamp         NULL,
			MODIFIED_DATE_TIME timestamp         NULL,
			NC_CATEGORY        NVarChar(255)     NULL,
			DPMO_CATEGORY_BO   NVarChar(255)     NULL
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE NC_GROUP_MEMBER';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE NC_GROUP_MEMBER
		(
			HANDLE               NVarChar(255) NOT NULL,
			NC_GROUP_BO          NVarChar(255)     NULL,
			NC_CODE_OR_GROUP_GBO NVarChar(255)     NULL,
			SEQUENCE             Decimal           NULL
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE NC_GROUP_MEMBER';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE NC_CODE';
END

