BeforeExecute
-- DB2 DB2.LUW DB2LUW

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t1".SMALLINTDATATYPE
FROM
	(
		SELECT DISTINCT
			"c_1".SMALLINTDATATYPE
		FROM
			ALLTYPES "_"
				INNER JOIN ALLTYPES "c_1" ON "_".SMALLINTDATATYPE = "c_1".INTDATATYPE
		WHERE
			"_".SMALLINTDATATYPE IS NULL
	) "t1"

BeforeExecute
-- DB2 DB2.LUW DB2LUW
DECLARE @ID SmallInt(2) -- Int16
SET     @ID = 1234

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t1".SMALLINTDATATYPE
FROM
	(
		SELECT DISTINCT
			"c_1".SMALLINTDATATYPE
		FROM
			ALLTYPES "_"
				INNER JOIN ALLTYPES "c_1" ON "_".SMALLINTDATATYPE = "c_1".INTDATATYPE
		WHERE
			"_".SMALLINTDATATYPE = @ID
	) "t1"

