-- Oracle.23.Managed Oracle.Managed Oracle12

DELETE FROM
	LINQDATATYPESBC t1

INSERT BULK LINQDATATYPESBC(ID, MONEYVALUE, DATETIMEVALUE, DATETIMEVALUE2, BOOLVALUE, GUIDVALUE, SMALLINTVALUE, INTVALUE, BIGINTVALUE, STRINGVALUE)

-- Oracle.23.Managed Oracle.Managed Oracle12

DELETE FROM
	LINQDATATYPESBC t1

