BeforeExecute
-- Oracle.23.Managed Oracle.Managed Oracle12

DELETE FROM
	LINQDATATYPESBC t1

BeforeExecute
INSERT BULK LINQDATATYPESBC(ID, MONEYVALUE, DATETIMEVALUE, DATETIMEVALUE2, BOOLVALUE, GUIDVALUE, SMALLINTVALUE, INTVALUE, BIGINTVALUE, STRINGVALUE)

BeforeExecute
-- Oracle.23.Managed Oracle.Managed Oracle12

DELETE FROM
	LINQDATATYPESBC t1

