BeforeExecute
-- Firebird3 Firebird

CREATE TABLE NC_CODE
(
	HANDLE             VarChar(255) CHARACTER SET UNICODE_FSS NOT NULL,
	CHANGE_STAMP       Decimal,
	SITE               VarChar(255) CHARACTER SET UNICODE_FSS,
	NC_CODE            VarChar(255) CHARACTER SET UNICODE_FSS,
	DESCRIPTION        VarChar(255) CHARACTER SET UNICODE_FSS,
	STATUS_BO          VarChar(255) CHARACTER SET UNICODE_FSS,
	CREATED_DATE_TIME  TimeStamp,
	MODIFIED_DATE_TIME TimeStamp,
	NC_CATEGORY        VarChar(255) CHARACTER SET UNICODE_FSS,
	DPMO_CATEGORY_BO   VarChar(255) CHARACTER SET UNICODE_FSS
)

BeforeExecute
-- Firebird3 Firebird

CREATE TABLE NC_GROUP_MEMBER
(
	HANDLE               VarChar(255) CHARACTER SET UNICODE_FSS NOT NULL,
	NC_GROUP_BO          VarChar(255) CHARACTER SET UNICODE_FSS,
	NC_CODE_OR_GROUP_GBO VarChar(255) CHARACTER SET UNICODE_FSS,
	SEQUENCE             Decimal
)

BeforeExecute
-- Firebird3 Firebird

DROP TABLE NC_GROUP_MEMBER

BeforeExecute
-- Firebird3 Firebird

DROP TABLE NC_CODE

