BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue1189Customer"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Issue1189Customer"
		(
			ID   Int           NOT NULL,
			NAME NVarChar(255) NOT NULL,

			CONSTRAINT "PK_Issue1189Customer" PRIMARY KEY (ID)
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW
DECLARE @DateTime Timestamp(20) -- DateTime
SET     @DateTime = '2020-02-29-17.54.55.123123'

SELECT
	"k_1".ID,
	"k_1".NAME,
	CAST(@DateTime AS timestamp)
FROM
	"Issue1189Customer" "k_1"

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue1189Customer"';
END

