BeforeExecute
--  SapHana.Odbc SapHanaOdbc

RENAME TABLE "AllTypes" TO "AllTypes_OLD"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc


CREATE COLUMN TABLE "AllTypes"
(
	ID INTEGER CS_INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"bigintDataType" BIGINT NULL,
	"smallintDataType" SMALLINT NULL,
	"decimalDataType" DECIMAL NULL,
	"smalldecimalDataType" SMALLDECIMAL NULL,
	"intDataType" INTEGER NULL,
	"tinyintDataType" TINYINT NULL,
	"floatDataType" FLOAT NULL,
	"realDataType" REAL NULL,

	"dateDataType" DATE NULL,
	"timeDataType" TIME NULL,
	"seconddateDataType" SECONDDATE NULL,
	"timestampDataType" TIMESTAMP NULL,

	"charDataType" CHAR(1) NULL,
	"char20DataType" CHAR(20) NULL,
	"varcharDataType" VARCHAR(20) NULL,
	"textDataType" TEXT NULL,
	"shorttextDataType" SHORTTEXT(20) NULL,
	"ncharDataType" NCHAR(1) NULL,
	"nchar20DataType" NCHAR(20) NULL,
	"nvarcharDataType" NVARCHAR(20) NULL,
	"alphanumDataType" ALPHANUM(20) NULL,

	"binaryDataType" BINARY(10) NULL,
	"varbinaryDataType" VARBINARY(10) NULL,

	"blobDataType" BLOB NULL,
	"clobDataType" CLOB NULL,
	"nclobDataType" NCLOB NULL,
	PRIMARY KEY ("ID")
)

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

INSERT INTO "AllTypes" SELECT ID, "bigintDataType", "smallintDataType", "decimalDataType", "smalldecimalDataType", "intDataType", "tinyintDataType", "floatDataType", "realDataType", "dateDataType", "timeDataType", "seconddateDataType", "timestampDataType", "charDataType", "char20DataType", "varcharDataType", "textDataType", "shorttextDataType", "ncharDataType", "nchar20DataType", "nvarcharDataType", "alphanumDataType", "binaryDataType", "varbinaryDataType", "blobDataType", "clobDataType", "nclobDataType" FROM "AllTypes_OLD"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

DROP TABLE "AllTypes_OLD"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc
DECLARE @Value  -- Int32
SET     @Value = 0

INSERT INTO "AllTypes"
(
	"intDataType"
)
VALUES
(
	?
)

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

SELECT CURRENT_IDENTITY_VALUE() FROM DUMMY

BeforeExecute
--  SapHana.Odbc SapHanaOdbc
DECLARE @Value  -- Int32
SET     @Value = 200

INSERT INTO "AllTypes"
(
	"intDataType"
)
VALUES
(
	?
)

BeforeExecute
--  SapHana.Odbc SapHanaOdbc
DECLARE @Value  -- Int32
SET     @Value = 300

INSERT INTO "AllTypes"
(
	"intDataType"
)
VALUES
(
	?
)

BeforeExecute
--  SapHana.Odbc SapHanaOdbc
DECLARE @lastId  -- Int32
SET     @lastId = 3

SELECT
	"t1"."ID",
	"t1"."intDataType"
FROM
	"AllTypes" "t1"
WHERE
	"t1"."ID" > ?
ORDER BY
	"t1"."ID"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc
DECLARE @lastId  -- Int32
SET     @lastId = 3

DELETE FROM
	"AllTypes" "t1"
WHERE
	"t1"."ID" >= ?

