BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "test_temp"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "test_temp"
(
	"ID"     Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Field1" Decimal                                  NOT NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DELETE FROM "test_temp"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

INSERT INTO "test_temp"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

INSERT INTO "test_temp"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @skip  -- Int32
SET     @skip = 1

SELECT
	"t1"."ID",
	"t1"."Field1"
FROM
	"test_temp" "t1"
ORDER BY
	"t1"."ID"
LIMIT 2 OFFSET ?

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DELETE FROM "test_temp"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

INSERT INTO "test_temp"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

INSERT INTO "test_temp"
(
	"Field1"
)
VALUES
(
	1
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @skip  -- Int32
SET     @skip = 1

SELECT
	"t1"."ID",
	"t1"."Field1"
FROM
	"test_temp" "t1"
ORDER BY
	"t1"."ID"
LIMIT 2 OFFSET ?

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "test_temp"

