BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Table1"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Table1"
(
	"Field1" Integer  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Foeld2" NChar(1)                                      NULL,

	PRIMARY KEY ("Field1")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"current_1"."Field1",
	"previous"."Field1"
FROM
	"Table1" "current_1",
	"Table1" "previous"
WHERE
	"current_1"."Foeld2" = "previous"."Foeld2" AND "current_1"."Foeld2" IS NOT NULL AND "previous"."Foeld2" IS NOT NULL OR
	"current_1"."Foeld2" IS NULL AND "previous"."Foeld2" IS NULL

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Table1"

