BeforeExecute
-- SqlServer.2008 (asynchronously)

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[AllTypes] [p]
			WHERE
				[p].[ID] = 2 AND ([p].[intDataType] <> COALESCE(CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) OR [p].[intDataType] IS NULL AND COALESCE(CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) IS NOT NULL OR [p].[intDataType] IS NOT NULL AND COALESCE(CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) IS NULL)
		)
			THEN 1
		ELSE 0
	END

