BeforeExecute
-- SqlServer.2016

SELECT
	IIF(EXISTS(
		SELECT
			*
		FROM
			[Parent] [p]
		WHERE
			[p].[ParentID] = 3 AND ([p].[Value1] = COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) AND [p].[Value1] IS NOT NULL AND COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) IS NOT NULL OR [p].[Value1] IS NULL AND COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) IS NULL)
	), 1, 0)

