BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Parent564"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Parent564"
(
	"Id"          Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Type"        NVarChar(255)                                      NULL,
	"StringValue" NVarChar(20)                                       NULL,
	"IntValue"    Integer                                            NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Type NVarChar(9) -- String
SET     @Type = 'Child564A'
DECLARE @StringValue NVarChar(9) -- String
SET     @StringValue = 'SomeValue'

INSERT INTO "Parent564"
(
	"Type",
	"StringValue"
)
VALUES
(
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Type NVarChar(9) -- String
SET     @Type = 'Child564B'
DECLARE @IntValue  -- Int32
SET     @IntValue = 911

INSERT INTO "Parent564"
(
	"Type",
	"IntValue"
)
VALUES
(
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	COUNT(*)
FROM
	"Parent564" "t1"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Parent564"

