BeforeExecute
-- ClickHouse.MySql ClickHouse

SELECT
	EXISTS(
		SELECT
			*
		FROM
			Parent p
		WHERE
			p.ParentID = 3 AND (COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END) <> p.Value1 OR COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END) IS NULL AND p.Value1 IS NOT NULL OR COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END) IS NOT NULL AND p.Value1 IS NULL)
	)

