BeforeExecute
-- ClickHouse.MySql ClickHouse (asynchronously)

SELECT
	EXISTS(
		SELECT
			*
		FROM
			Parent p
		WHERE
			p.ParentID = 3 AND (COALESCE(CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END, CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END) = p.Value1 OR COALESCE(CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END, CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END) IS NULL AND p.Value1 IS NULL)
	)

