BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue4654Customer"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Issue4654Customer"
		(
			"Id"   Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"Name" NVarChar(255)                                  NULL,

			CONSTRAINT "PK_Issue4654Customer" PRIMARY KEY ("Id")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue4654Order"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Issue4654Order"
		(
			"Id"          Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"ProductName" NVarChar(255)                                  NULL,
			"Quantity"    Int                                        NOT NULL,
			"CustomerId"  Int                                        NOT NULL,

			CONSTRAINT "PK_Issue4654Order" PRIMARY KEY ("Id")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue4654Product"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Issue4654Product"
		(
			"Id"    Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"Name"  NVarChar(255)                                  NULL,
			"Price" Decimal                                    NOT NULL,

			CONSTRAINT "PK_Issue4654Product" PRIMARY KEY ("Id")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	RTrim(Char("c_1"."Id")),
	"c_1"."Name"
FROM
	"Issue4654Customer" "c_1"
UNION
SELECT
	RTrim(Char("o"."Id")),
	"o"."ProductName"
FROM
	"Issue4654Order" "o"
UNION
SELECT
	RTrim(Char("p"."Id")),
	"p"."Name"
FROM
	"Issue4654Product" "p"

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue4654Product"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue4654Order"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue4654Customer"';
END

