-- DuckDB

SELECT
	CAST(CAST(EXTRACT(year FROM d.DateTimeValue) AS VARCHAR) || '-02-24 00:00:00' AS TIMESTAMP)
FROM
	LinqDataTypes d
WHERE
	EXTRACT(day FROM CAST(CAST(EXTRACT(year FROM d.DateTimeValue) AS VARCHAR) || '-02-24 00:00:00' AS TIMESTAMP)) > 0

