-- ClickHouse.Driver ClickHouse

SELECT
	t3.Id,
	t3.Status,
	t3.ResourceLabel,
	t3.ResourceLabelNVE,
	t3.ParentResourceID,
	t3.TypeID,
	t3.HeightClass,
	t3.CurrentWeightOfResource,
	t3.WidthClass,
	t3.LengthClass,
	t3.OriginalResourceID,
	t3.LastGlobalTaskID,
	t3.WashingDate,
	t3.ResourcePointID,
	t3.Height,
	t3.Width,
	t3.Length_1,
	t3.TechnicalValues,
	t3.RearrangementCount,
	t3.IsVirtual,
	t3.ErrorMessage,
	t3.FillingDegree,
	t3.LastInventoryCheckTimeStamp,
	t3.Segmentation,
	t3.DontTouch,
	tp.Id,
	tp.Name,
	tp.ShortName,
	tp.Height,
	tp.Depth,
	tp.Width
FROM
	(
		SELECT
			t1.Id as Id,
			t1.Status as Status,
			t1.ResourceLabel as ResourceLabel,
			t1.ResourceLabelNVE as ResourceLabelNVE,
			t1.ParentResourceID as ParentResourceID,
			t1.TypeID as TypeID,
			t1.HeightClass as HeightClass,
			t1.CurrentWeightOfResource as CurrentWeightOfResource,
			t1.WidthClass as WidthClass,
			t1.LengthClass as LengthClass,
			t1.OriginalResourceID as OriginalResourceID,
			t1.LastGlobalTaskID as LastGlobalTaskID,
			t1.WashingDate as WashingDate,
			t1.ResourcePointID as ResourcePointID,
			t1.Height as Height,
			t1.Width as Width,
			t1.Length as Length_1,
			t1.TechnicalValues as TechnicalValues,
			t1.RearrangementCount as RearrangementCount,
			t1.IsVirtual as IsVirtual,
			t1.ErrorMessage as ErrorMessage,
			t1.FillingDegree as FillingDegree,
			t1.LastInventoryCheckTimeStamp as LastInventoryCheckTimeStamp,
			t1.Segmentation as Segmentation,
			t1.DontTouch as DontTouch
		FROM
			WmsLoadCarrierDTO t1
		UNION DISTINCT
		SELECT
			t2.Id as Id,
			t2.Status as Status,
			t2.ResourceLabel as ResourceLabel,
			t2.ResourceLabelNVE as ResourceLabelNVE,
			t2.ParentResourceID as ParentResourceID,
			t2.TypeID as TypeID,
			t2.HeightClass as HeightClass,
			t2.CurrentWeightOfResource as CurrentWeightOfResource,
			t2.WidthClass as WidthClass,
			t2.LengthClass as LengthClass,
			t2.OriginalResourceID as OriginalResourceID,
			t2.LastGlobalTaskID as LastGlobalTaskID,
			t2.WashingDate as WashingDate,
			t2.ResourcePointID as ResourcePointID,
			t2.Height as Height,
			t2.Width as Width,
			t2.Length as Length_1,
			t2.TechnicalValues as TechnicalValues,
			t2.RearrangementCount as RearrangementCount,
			t2.IsVirtual as IsVirtual,
			t2.ErrorMessage as ErrorMessage,
			t2.FillingDegree as FillingDegree,
			t2.LastInventoryCheckTimeStamp as LastInventoryCheckTimeStamp,
			t2.Segmentation as Segmentation,
			t2.DontTouch as DontTouch
		FROM
			WMS_ResourceA t2
	) t3
		LEFT JOIN WmsResourceTypeDTO tp ON t3.TypeID = tp.Id

