BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "DisTable"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "DisTable"
		(
			"DisTypeID" Int NOT NULL
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "JurTable"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "JurTable"
		(
			"JurCode" NVarChar(2) NOT NULL,

			CONSTRAINT "PK_JurTable" PRIMARY KEY ("JurCode")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "DisTypeTable"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "DisTypeTable"
		(
			"DisTypeID" Int          NOT NULL,
			"JurCode"   NVarChar(50) NOT NULL,

			CONSTRAINT "PK_DisTypeTable" PRIMARY KEY ("DisTypeID")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"d"."DisTypeID"
FROM
	"DisTable" "d"
		INNER JOIN "DisTypeTable" "a_DisType" ON CASE
			WHEN "d"."DisTypeID" = 1 THEN 1
			WHEN "d"."DisTypeID" = 2 THEN 2
			WHEN "d"."DisTypeID" = 4 THEN 4
			WHEN "d"."DisTypeID" = 5 THEN 5
		END = "a_DisType"."DisTypeID" AND CASE
			WHEN "d"."DisTypeID" = 1 THEN 1
			WHEN "d"."DisTypeID" = 2 THEN 2
			WHEN "d"."DisTypeID" = 4 THEN 4
			WHEN "d"."DisTypeID" = 5 THEN 5
		END IS NOT NULL
		INNER JOIN "JurTable" "j" ON "a_DisType"."JurCode" = "j"."JurCode"

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "DisTypeTable"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "JurTable"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "DisTable"';
END

