-- Firebird.3 Firebird3

SELECT
	"r".RDB$RELATION_NAME,
	"r".RDB$RELATION_TYPE,
	"r".RDB$OWNER_NAME,
	"r".RDB$DESCRIPTION
FROM
	RDB$RELATIONS "r"
WHERE
	"r".RDB$SYSTEM_FLAG IS NULL OR CAST("r".RDB$SYSTEM_FLAG AS Int) = 0

-- Firebird.3 Firebird3

SELECT
	"rc".RDB$RELATION_NAME,
	"rc".RDB$CONSTRAINT_NAME,
	"seg".RDB$FIELD_NAME,
	"seg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$INDEX_SEGMENTS "seg" ON "rc".RDB$INDEX_NAME = "seg".RDB$INDEX_NAME
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'

-- Firebird.3 Firebird3

SELECT
	"rf".RDB$RELATION_NAME,
	"rf".RDB$FIELD_NAME,
	"rf".RDB$FIELD_POSITION,
	"rf".RDB$NULL_FLAG,
	"rf".RDB$DESCRIPTION,
	"f".RDB$FIELD_TYPE,
	"f".RDB$FIELD_SUB_TYPE,
	"f".RDB$CHARACTER_LENGTH,
	"f".RDB$FIELD_PRECISION,
	"f".RDB$FIELD_SCALE,
	"f".RDB$COMPUTED_SOURCE
FROM
	RDB$RELATION_FIELDS "rf"
		INNER JOIN RDB$FIELDS "f" ON "rf".RDB$FIELD_SOURCE = "f".RDB$FIELD_NAME

-- Firebird.3 Firebird3

SELECT
	"rc".RDB$CONSTRAINT_NAME,
	"rc".RDB$RELATION_NAME,
	"rcUq".RDB$RELATION_NAME,
	"thisSeg".RDB$FIELD_NAME,
	"otherSeg".RDB$FIELD_NAME,
	"thisSeg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$REF_CONSTRAINTS "refc" ON "rc".RDB$CONSTRAINT_NAME = "refc".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$RELATION_CONSTRAINTS "rcUq" ON "refc".RDB$CONST_NAME_UQ = "rcUq".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "thisSeg" ON "rc".RDB$INDEX_NAME = "thisSeg".RDB$INDEX_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "otherSeg" ON ("rcUq".RDB$INDEX_NAME = "otherSeg".RDB$INDEX_NAME OR "rcUq".RDB$INDEX_NAME IS NULL AND "otherSeg".RDB$INDEX_NAME IS NULL) AND ("thisSeg".RDB$FIELD_POSITION = "otherSeg".RDB$FIELD_POSITION OR "thisSeg".RDB$FIELD_POSITION IS NULL AND "otherSeg".RDB$FIELD_POSITION IS NULL)
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'

-- Firebird.3 Firebird3

SELECT * FROM (
	SELECT
		RDB$PACKAGE_NAME                                        AS PackageName,
		RDB$PROCEDURE_NAME                                      AS ProcedureName,
		RDB$DESCRIPTION                                         AS Description,
		RDB$PROCEDURE_SOURCE                                    AS Source,
		CASE WHEN RDB$PROCEDURE_TYPE = 1 THEN 'TF' ELSE 'P' END AS Type
	FROM RDB$PROCEDURES
	WHERE RDB$SYSTEM_FLAG = 0 AND (RDB$PRIVATE_FLAG IS NULL OR RDB$PRIVATE_FLAG = 0) AND RDB$PROCEDURE_TYPE IS NOT NULL
	UNION ALL
	SELECT
		RDB$PACKAGE_NAME,
		RDB$FUNCTION_NAME,
		RDB$DESCRIPTION,
		RDB$FUNCTION_SOURCE,
		'F'
	FROM RDB$FUNCTIONS
	WHERE RDB$SYSTEM_FLAG = 0  AND (RDB$PRIVATE_FLAG IS NULL OR RDB$PRIVATE_FLAG = 0)
) ORDER BY PackageName, ProcedureName

-- Firebird.3 Firebird3

SELECT
	p.RDB$PACKAGE_NAME                                   AS PackageName,
	p.RDB$PROCEDURE_NAME                                 AS ProcedureName,
	p.RDB$PARAMETER_NAME                                 AS ParameterName,
	p.RDB$PARAMETER_NUMBER                               AS Ordinal,
	p.RDB$PARAMETER_TYPE                                 AS Direction,
	p.RDB$DESCRIPTION                                    AS Decsription,
	f.RDB$FIELD_TYPE                                     AS Type,
	f.RDB$FIELD_SUB_TYPE                                 AS SubType,
	COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS Length,
	f.RDB$FIELD_PRECISION                                AS "precision",
	f.RDB$FIELD_SCALE                                    AS Scale,
	COALESCE(f.RDB$NULL_FLAG, p.RDB$NULL_FLAG)           AS IsNullable
FROM RDB$PROCEDURE_PARAMETERS p
	INNER JOIN RDB$PROCEDURES pr ON p.RDB$PROCEDURE_NAME = pr.RDB$PROCEDURE_NAME
		AND (p.RDB$PACKAGE_NAME = pr.RDB$PACKAGE_NAME OR (p.RDB$PACKAGE_NAME IS NULL AND pr.RDB$PACKAGE_NAME IS NULL))
	LEFT JOIN RDB$FIELDS f ON p.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE p.RDB$SYSTEM_FLAG = 0 AND (pr.RDB$PROCEDURE_TYPE <> 1 OR p.RDB$PARAMETER_TYPE <> 1)
UNION ALL
SELECT
	p.RDB$PACKAGE_NAME,
	p.RDB$FUNCTION_NAME,
	p.RDB$ARGUMENT_NAME,
	p.RDB$ARGUMENT_POSITION,
	CASE WHEN fn.RDB$RETURN_ARGUMENT = p.RDB$ARGUMENT_POSITION THEN 2 ELSE 0 END,
	p.RDB$DESCRIPTION,
	COALESCE(f.RDB$FIELD_TYPE, p.RDB$FIELD_TYPE),
	COALESCE(f.RDB$FIELD_SUB_TYPE, p.RDB$FIELD_TYPE),
	COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH, p.RDB$CHARACTER_LENGTH, p.RDB$FIELD_LENGTH),
	COALESCE(f.RDB$FIELD_PRECISION, p.RDB$FIELD_PRECISION),
	COALESCE(f.RDB$FIELD_SCALE, p.RDB$FIELD_SCALE),
	COALESCE(f.RDB$NULL_FLAG, p.RDB$NULL_FLAG)
	FROM RDB$FUNCTION_ARGUMENTS p
		INNER JOIN RDB$FUNCTIONS fn ON p.RDB$FUNCTION_NAME = fn.RDB$FUNCTION_NAME
			AND (p.RDB$PACKAGE_NAME = fn.RDB$PACKAGE_NAME OR (p.RDB$PACKAGE_NAME IS NULL AND fn.RDB$PACKAGE_NAME IS NULL))
		LEFT JOIN RDB$FIELDS f ON p.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE p.RDB$SYSTEM_FLAG = 0

RollbackTransaction
-- Firebird.3 Firebird3

SELECT
	"r".RDB$RELATION_NAME,
	"r".RDB$RELATION_TYPE,
	"r".RDB$OWNER_NAME,
	"r".RDB$DESCRIPTION
FROM
	RDB$RELATIONS "r"
WHERE
	"r".RDB$SYSTEM_FLAG IS NULL OR CAST("r".RDB$SYSTEM_FLAG AS Int) = 0

-- Firebird.3 Firebird3

SELECT
	"rc".RDB$RELATION_NAME,
	"rc".RDB$CONSTRAINT_NAME,
	"seg".RDB$FIELD_NAME,
	"seg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$INDEX_SEGMENTS "seg" ON "rc".RDB$INDEX_NAME = "seg".RDB$INDEX_NAME
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'

-- Firebird.3 Firebird3

SELECT
	"rf".RDB$RELATION_NAME,
	"rf".RDB$FIELD_NAME,
	"rf".RDB$FIELD_POSITION,
	"rf".RDB$NULL_FLAG,
	"rf".RDB$DESCRIPTION,
	"f".RDB$FIELD_TYPE,
	"f".RDB$FIELD_SUB_TYPE,
	"f".RDB$CHARACTER_LENGTH,
	"f".RDB$FIELD_PRECISION,
	"f".RDB$FIELD_SCALE,
	"f".RDB$COMPUTED_SOURCE
FROM
	RDB$RELATION_FIELDS "rf"
		INNER JOIN RDB$FIELDS "f" ON "rf".RDB$FIELD_SOURCE = "f".RDB$FIELD_NAME

-- Firebird.3 Firebird3

SELECT
	"rc".RDB$CONSTRAINT_NAME,
	"rc".RDB$RELATION_NAME,
	"rcUq".RDB$RELATION_NAME,
	"thisSeg".RDB$FIELD_NAME,
	"otherSeg".RDB$FIELD_NAME,
	"thisSeg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$REF_CONSTRAINTS "refc" ON "rc".RDB$CONSTRAINT_NAME = "refc".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$RELATION_CONSTRAINTS "rcUq" ON "refc".RDB$CONST_NAME_UQ = "rcUq".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "thisSeg" ON "rc".RDB$INDEX_NAME = "thisSeg".RDB$INDEX_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "otherSeg" ON ("rcUq".RDB$INDEX_NAME = "otherSeg".RDB$INDEX_NAME OR "rcUq".RDB$INDEX_NAME IS NULL AND "otherSeg".RDB$INDEX_NAME IS NULL) AND ("thisSeg".RDB$FIELD_POSITION = "otherSeg".RDB$FIELD_POSITION OR "thisSeg".RDB$FIELD_POSITION IS NULL AND "otherSeg".RDB$FIELD_POSITION IS NULL)
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'

-- Firebird.3 Firebird3

SELECT * FROM (
	SELECT
		RDB$PACKAGE_NAME                                        AS PackageName,
		RDB$PROCEDURE_NAME                                      AS ProcedureName,
		RDB$DESCRIPTION                                         AS Description,
		RDB$PROCEDURE_SOURCE                                    AS Source,
		CASE WHEN RDB$PROCEDURE_TYPE = 1 THEN 'TF' ELSE 'P' END AS Type
	FROM RDB$PROCEDURES
	WHERE RDB$SYSTEM_FLAG = 0 AND (RDB$PRIVATE_FLAG IS NULL OR RDB$PRIVATE_FLAG = 0) AND RDB$PROCEDURE_TYPE IS NOT NULL
	UNION ALL
	SELECT
		RDB$PACKAGE_NAME,
		RDB$FUNCTION_NAME,
		RDB$DESCRIPTION,
		RDB$FUNCTION_SOURCE,
		'F'
	FROM RDB$FUNCTIONS
	WHERE RDB$SYSTEM_FLAG = 0  AND (RDB$PRIVATE_FLAG IS NULL OR RDB$PRIVATE_FLAG = 0)
) ORDER BY PackageName, ProcedureName

-- Firebird.3 Firebird3

SELECT
	p.RDB$PACKAGE_NAME                                   AS PackageName,
	p.RDB$PROCEDURE_NAME                                 AS ProcedureName,
	p.RDB$PARAMETER_NAME                                 AS ParameterName,
	p.RDB$PARAMETER_NUMBER                               AS Ordinal,
	p.RDB$PARAMETER_TYPE                                 AS Direction,
	p.RDB$DESCRIPTION                                    AS Decsription,
	f.RDB$FIELD_TYPE                                     AS Type,
	f.RDB$FIELD_SUB_TYPE                                 AS SubType,
	COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS Length,
	f.RDB$FIELD_PRECISION                                AS "precision",
	f.RDB$FIELD_SCALE                                    AS Scale,
	COALESCE(f.RDB$NULL_FLAG, p.RDB$NULL_FLAG)           AS IsNullable
FROM RDB$PROCEDURE_PARAMETERS p
	INNER JOIN RDB$PROCEDURES pr ON p.RDB$PROCEDURE_NAME = pr.RDB$PROCEDURE_NAME
		AND (p.RDB$PACKAGE_NAME = pr.RDB$PACKAGE_NAME OR (p.RDB$PACKAGE_NAME IS NULL AND pr.RDB$PACKAGE_NAME IS NULL))
	LEFT JOIN RDB$FIELDS f ON p.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE p.RDB$SYSTEM_FLAG = 0 AND (pr.RDB$PROCEDURE_TYPE <> 1 OR p.RDB$PARAMETER_TYPE <> 1)
UNION ALL
SELECT
	p.RDB$PACKAGE_NAME,
	p.RDB$FUNCTION_NAME,
	p.RDB$ARGUMENT_NAME,
	p.RDB$ARGUMENT_POSITION,
	CASE WHEN fn.RDB$RETURN_ARGUMENT = p.RDB$ARGUMENT_POSITION THEN 2 ELSE 0 END,
	p.RDB$DESCRIPTION,
	COALESCE(f.RDB$FIELD_TYPE, p.RDB$FIELD_TYPE),
	COALESCE(f.RDB$FIELD_SUB_TYPE, p.RDB$FIELD_TYPE),
	COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH, p.RDB$CHARACTER_LENGTH, p.RDB$FIELD_LENGTH),
	COALESCE(f.RDB$FIELD_PRECISION, p.RDB$FIELD_PRECISION),
	COALESCE(f.RDB$FIELD_SCALE, p.RDB$FIELD_SCALE),
	COALESCE(f.RDB$NULL_FLAG, p.RDB$NULL_FLAG)
	FROM RDB$FUNCTION_ARGUMENTS p
		INNER JOIN RDB$FUNCTIONS fn ON p.RDB$FUNCTION_NAME = fn.RDB$FUNCTION_NAME
			AND (p.RDB$PACKAGE_NAME = fn.RDB$PACKAGE_NAME OR (p.RDB$PACKAGE_NAME IS NULL AND fn.RDB$PACKAGE_NAME IS NULL))
		LEFT JOIN RDB$FIELDS f ON p.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE p.RDB$SYSTEM_FLAG = 0

RollbackTransaction
-- Firebird.3 Firebird3

SELECT
	"r".RDB$RELATION_NAME,
	"r".RDB$RELATION_TYPE,
	"r".RDB$OWNER_NAME,
	"r".RDB$DESCRIPTION
FROM
	RDB$RELATIONS "r"
WHERE
	"r".RDB$SYSTEM_FLAG IS NULL OR CAST("r".RDB$SYSTEM_FLAG AS Int) = 0

-- Firebird.3 Firebird3

SELECT
	"rc".RDB$RELATION_NAME,
	"rc".RDB$CONSTRAINT_NAME,
	"seg".RDB$FIELD_NAME,
	"seg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$INDEX_SEGMENTS "seg" ON "rc".RDB$INDEX_NAME = "seg".RDB$INDEX_NAME
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'

-- Firebird.3 Firebird3

SELECT
	"rf".RDB$RELATION_NAME,
	"rf".RDB$FIELD_NAME,
	"rf".RDB$FIELD_POSITION,
	"rf".RDB$NULL_FLAG,
	"rf".RDB$DESCRIPTION,
	"f".RDB$FIELD_TYPE,
	"f".RDB$FIELD_SUB_TYPE,
	"f".RDB$CHARACTER_LENGTH,
	"f".RDB$FIELD_PRECISION,
	"f".RDB$FIELD_SCALE,
	"f".RDB$COMPUTED_SOURCE
FROM
	RDB$RELATION_FIELDS "rf"
		INNER JOIN RDB$FIELDS "f" ON "rf".RDB$FIELD_SOURCE = "f".RDB$FIELD_NAME

-- Firebird.3 Firebird3

SELECT
	"rc".RDB$CONSTRAINT_NAME,
	"rc".RDB$RELATION_NAME,
	"rcUq".RDB$RELATION_NAME,
	"thisSeg".RDB$FIELD_NAME,
	"otherSeg".RDB$FIELD_NAME,
	"thisSeg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$REF_CONSTRAINTS "refc" ON "rc".RDB$CONSTRAINT_NAME = "refc".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$RELATION_CONSTRAINTS "rcUq" ON "refc".RDB$CONST_NAME_UQ = "rcUq".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "thisSeg" ON "rc".RDB$INDEX_NAME = "thisSeg".RDB$INDEX_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "otherSeg" ON ("rcUq".RDB$INDEX_NAME = "otherSeg".RDB$INDEX_NAME OR "rcUq".RDB$INDEX_NAME IS NULL AND "otherSeg".RDB$INDEX_NAME IS NULL) AND ("thisSeg".RDB$FIELD_POSITION = "otherSeg".RDB$FIELD_POSITION OR "thisSeg".RDB$FIELD_POSITION IS NULL AND "otherSeg".RDB$FIELD_POSITION IS NULL)
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'

-- Firebird.3 Firebird3

SELECT * FROM (
	SELECT
		RDB$PACKAGE_NAME                                        AS PackageName,
		RDB$PROCEDURE_NAME                                      AS ProcedureName,
		RDB$DESCRIPTION                                         AS Description,
		RDB$PROCEDURE_SOURCE                                    AS Source,
		CASE WHEN RDB$PROCEDURE_TYPE = 1 THEN 'TF' ELSE 'P' END AS Type
	FROM RDB$PROCEDURES
	WHERE RDB$SYSTEM_FLAG = 0 AND (RDB$PRIVATE_FLAG IS NULL OR RDB$PRIVATE_FLAG = 0) AND RDB$PROCEDURE_TYPE IS NOT NULL
	UNION ALL
	SELECT
		RDB$PACKAGE_NAME,
		RDB$FUNCTION_NAME,
		RDB$DESCRIPTION,
		RDB$FUNCTION_SOURCE,
		'F'
	FROM RDB$FUNCTIONS
	WHERE RDB$SYSTEM_FLAG = 0  AND (RDB$PRIVATE_FLAG IS NULL OR RDB$PRIVATE_FLAG = 0)
) ORDER BY PackageName, ProcedureName

-- Firebird.3 Firebird3

SELECT
	p.RDB$PACKAGE_NAME                                   AS PackageName,
	p.RDB$PROCEDURE_NAME                                 AS ProcedureName,
	p.RDB$PARAMETER_NAME                                 AS ParameterName,
	p.RDB$PARAMETER_NUMBER                               AS Ordinal,
	p.RDB$PARAMETER_TYPE                                 AS Direction,
	p.RDB$DESCRIPTION                                    AS Decsription,
	f.RDB$FIELD_TYPE                                     AS Type,
	f.RDB$FIELD_SUB_TYPE                                 AS SubType,
	COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS Length,
	f.RDB$FIELD_PRECISION                                AS "precision",
	f.RDB$FIELD_SCALE                                    AS Scale,
	COALESCE(f.RDB$NULL_FLAG, p.RDB$NULL_FLAG)           AS IsNullable
FROM RDB$PROCEDURE_PARAMETERS p
	INNER JOIN RDB$PROCEDURES pr ON p.RDB$PROCEDURE_NAME = pr.RDB$PROCEDURE_NAME
		AND (p.RDB$PACKAGE_NAME = pr.RDB$PACKAGE_NAME OR (p.RDB$PACKAGE_NAME IS NULL AND pr.RDB$PACKAGE_NAME IS NULL))
	LEFT JOIN RDB$FIELDS f ON p.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE p.RDB$SYSTEM_FLAG = 0 AND (pr.RDB$PROCEDURE_TYPE <> 1 OR p.RDB$PARAMETER_TYPE <> 1)
UNION ALL
SELECT
	p.RDB$PACKAGE_NAME,
	p.RDB$FUNCTION_NAME,
	p.RDB$ARGUMENT_NAME,
	p.RDB$ARGUMENT_POSITION,
	CASE WHEN fn.RDB$RETURN_ARGUMENT = p.RDB$ARGUMENT_POSITION THEN 2 ELSE 0 END,
	p.RDB$DESCRIPTION,
	COALESCE(f.RDB$FIELD_TYPE, p.RDB$FIELD_TYPE),
	COALESCE(f.RDB$FIELD_SUB_TYPE, p.RDB$FIELD_TYPE),
	COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH, p.RDB$CHARACTER_LENGTH, p.RDB$FIELD_LENGTH),
	COALESCE(f.RDB$FIELD_PRECISION, p.RDB$FIELD_PRECISION),
	COALESCE(f.RDB$FIELD_SCALE, p.RDB$FIELD_SCALE),
	COALESCE(f.RDB$NULL_FLAG, p.RDB$NULL_FLAG)
	FROM RDB$FUNCTION_ARGUMENTS p
		INNER JOIN RDB$FUNCTIONS fn ON p.RDB$FUNCTION_NAME = fn.RDB$FUNCTION_NAME
			AND (p.RDB$PACKAGE_NAME = fn.RDB$PACKAGE_NAME OR (p.RDB$PACKAGE_NAME IS NULL AND fn.RDB$PACKAGE_NAME IS NULL))
		LEFT JOIN RDB$FIELDS f ON p.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE p.RDB$SYSTEM_FLAG = 0

RollbackTransaction
