BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TestTable"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "TestTable"
(
	"ID"        Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Field1"    NVarChar(50)                                       NULL,
	"Field2"    NVarChar(255)                                      NULL,
	"CreatedOn" Timestamp                                          NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TestTable"

