BeforeExecute
-- DB2 DB2.LUW DB2LUW

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t2".ID
FROM
	(
		SELECT DISTINCT
			"a_Association".SMALLINTDATATYPE as ID
		FROM
			ALLTYPES "t1"
				INNER JOIN ALLTYPES "a_Association" ON "t1".SMALLINTDATATYPE = "a_Association".INTDATATYPE
		WHERE
			1 = 0
	) "t2"

BeforeExecute
-- DB2 DB2.LUW DB2LUW
DECLARE @ID SmallInt(2) -- Int16
SET     @ID = 1234

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t2".ID
FROM
	(
		SELECT DISTINCT
			"a_Association".SMALLINTDATATYPE as ID
		FROM
			ALLTYPES "t1"
				INNER JOIN ALLTYPES "a_Association" ON "t1".SMALLINTDATATYPE = "a_Association".INTDATATYPE
		WHERE
			"t1".SMALLINTDATATYPE = @ID
	) "t2"

