BeforeExecute
-- DB2 DB2.LUW DB2LUW
DECLARE @ID SmallInt(2) -- Int16
SET     @ID = 0

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t1".ID
FROM
	(
		SELECT DISTINCT
			"a_Association".SMALLINTDATATYPE as ID
		FROM
			ALLTYPES "_"
				INNER JOIN ALLTYPES "a_Association" ON "_".SMALLINTDATATYPE = "a_Association".INTDATATYPE
		WHERE
			"_".SMALLINTDATATYPE = @ID
	) "t1"

BeforeExecute
-- DB2 DB2.LUW DB2LUW
DECLARE @ID SmallInt(2) -- Int16
SET     @ID = 1234

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t1".ID
FROM
	(
		SELECT DISTINCT
			"a_Association".SMALLINTDATATYPE as ID
		FROM
			ALLTYPES "_"
				INNER JOIN ALLTYPES "a_Association" ON "_".SMALLINTDATATYPE = "a_Association".INTDATATYPE
		WHERE
			"_".SMALLINTDATATYPE = @ID
	) "t1"

