BeforeExecute
-- SapHana.Native SapHana

CREATE COLUMN TABLE "DynamicTable"
(
	"ID"             Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Not Identifier" Integer                                  NOT NULL,
	"Some Value"     Integer                                  NOT NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @NotIdentifier  -- Int32
SET     @NotIdentifier = 77
DECLARE @Value_1  -- Int32
SET     @Value_1 = 5

INSERT INTO "DynamicTable"
(
	"Not Identifier",
	"Some Value"
)
VALUES
(
	:"NotIdentifier",
	:"Value_1"
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @NotIdentifier  -- Int32
SET     @NotIdentifier = 77
DECLARE @Value_1  -- Int32
SET     @Value_1 = 5

INSERT INTO "DynamicTable"
(
	"Not Identifier",
	"Some Value"
)
VALUES
(
	:"NotIdentifier",
	:"Value_1"
)

BeforeExecute
-- SapHana.Native SapHana

SELECT
	"t1"."Not Identifier",
	Count(*),
	Sum("t1"."Some Value")
FROM
	"DynamicTable" "t1"
GROUP BY
	"t1"."Not Identifier"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "DynamicTable"

