BeforeExecute
-- DB2 DB2.LUW DB2LUW

CREATE TABLE MRECEIPT
(
	RECEIPT_NO NVarChar(255)     NULL,
	CUSTKEY    NVarChar(255)     NULL
)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

CREATE TABLE CUST_DTL
(
	CUSTKEY   NVarChar(255)     NULL,
	BILLGROUP NVarChar(255)     NULL
)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE CUST_DTL';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE MRECEIPT';
END

