BeforeExecute
-- Oracle.11.Managed Oracle11

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE BULKCOPYTABLE2';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;

BeforeExecute
-- Oracle.11.Managed Oracle11

BEGIN
	EXECUTE IMMEDIATE '
		CREATE TABLE BULKCOPYTABLE2
		(
			"id" Int NOT NULL
		)
	';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -955 THEN
			RAISE;
		END IF;
END;

BeforeExecute
-- Oracle.11.Managed Oracle11

SELECT
	sys_context('userenv','service_name')
FROM SYS.DUAL

BeforeExecute
-- Oracle.11.Managed Oracle11

INSERT ALL
	INTO BULKCOPYTABLE2 ("id") VALUES (1)
	INTO BULKCOPYTABLE2 ("id") VALUES (2)
	INTO BULKCOPYTABLE2 ("id") VALUES (3)
	INTO BULKCOPYTABLE2 ("id") VALUES (4)
	INTO BULKCOPYTABLE2 ("id") VALUES (5)
	INTO BULKCOPYTABLE2 ("id") VALUES (6)
	INTO BULKCOPYTABLE2 ("id") VALUES (7)
	INTO BULKCOPYTABLE2 ("id") VALUES (8)
	INTO BULKCOPYTABLE2 ("id") VALUES (9)
	INTO BULKCOPYTABLE2 ("id") VALUES (10)
SELECT * FROM dual

BeforeExecute
-- Oracle.11.Managed Oracle11

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE BULKCOPYTABLE2';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;

