-- Oracle.19.Managed Oracle.Managed Oracle12
SELECT
	t."Id",
	LAST_VALUE(CASE
		WHEN t."IntValue" = 20 THEN 1
		ELSE 0
	END) OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING),
	LAST_VALUE(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
FROM
	"WindowFunctionTestEntity" t
ORDER BY
	t."Id"

