BeforeExecute
-- Oracle.11.Managed Oracle11

SELECT
	AVG(p."Value1") OVER(),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID" ORDER BY p."Value1" RANGE BETWEEN 0 PRECEDING AND 1 FOLLOWING),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID" ORDER BY p."Value1" RANGE BETWEEN 0 PRECEDING AND 1 FOLLOWING),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(ALL p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(DISTINCT p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID"),
	AVG(p."Value1") OVER(),
	AVG(ALL p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID" ORDER BY p."Value1" RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
	AVG(p."Value1") OVER(PARTITION BY p."Value1", c_1."ChildID" ORDER BY p."Value1" RANGE BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING),
	AVG(DISTINCT p."Value1") OVER()
FROM
	"Parent" p
		INNER JOIN "Child" c_1 ON p."ParentID" = c_1."ParentID"

