-- SqlServer.SA.MS SqlServer.2019

SELECT 1 UNION ALL SELECT 2

-- SqlServer.SA.MS SqlServer.2019

SELECT 1 UNION ALL SELECT 2

-- SqlServer.SA.MS SqlServer.2019

SELECT 1 UNION ALL SELECT 2

-- SqlServer.SA.MS SqlServer.2019

SELECT 1 UNION ALL SELECT 2

-- SqlServer.SA.MS SqlServer.2019

SELECT 1 UNION ALL SELECT 2

-- SqlServer.SA.MS SqlServer.2019

SELECT 1 UNION ALL SELECT 2

