BeforeExecute
-- SqlServer.2017.MS SqlServer.2017

SELECT
	SUM([t].[IntValue]) OVER (PARTITION BY [t].[CategoryId] ORDER BY [t].[Id] RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM([t].[IntValue]) OVER (PARTITION BY [t].[CategoryId] ORDER BY [t].[Id] RANGE BETWEEN CURRENT ROW AND CURRENT ROW),
	SUM([t].[IntValue]) OVER (PARTITION BY [t].[CategoryId] ORDER BY [t].[Id] RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM([t].[IntValue]) OVER (PARTITION BY [t].[CategoryId] ORDER BY [t].[Id] RANGE BETWEEN CURRENT ROW AND CURRENT ROW)
FROM
	[WindowFunctionTestEntity] [t]

