BeforeExecute
-- DB2 DB2.LUW DB2LUW

DECLARE GLOBAL TEMPORARY TABLE SESSION."tmptbl1"
(
	ID      Int           NOT NULL,
	"Value" NVarChar(255)     NULL
)
ON COMMIT PRESERVE ROWS

BeforeExecute
-- DB2 DB2.LUW DB2LUW

INSERT INTO SESSION."tmptbl1"
(
	ID,
	"Value"
)
VALUES
(1,'Value1'),
(2,NULL)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

DECLARE GLOBAL TEMPORARY TABLE SESSION."tmptbl2"
(
	ID      Int           NOT NULL,
	"Value" NVarChar(255) NOT NULL
)
ON COMMIT PRESERVE ROWS

BeforeExecute
-- DB2 DB2.LUW DB2LUW

INSERT INTO SESSION."tmptbl2"
(
	ID,
	"Value"
)
VALUES
(1,'Value1'),
(3,'Value2')

BeforeExecute
-- DB2 DB2.LUW DB2LUW

DECLARE GLOBAL TEMPORARY TABLE SESSION."tmptbl3"
(
	ID      Int           NOT NULL,
	"Value" NVarChar(255)     NULL
)
ON COMMIT PRESERVE ROWS

BeforeExecute
-- DB2 DB2.LUW DB2LUW

INSERT INTO SESSION."tmptbl3"
(
	ID,
	"Value"
)
VALUES
(1,'Value1'),
(2,NULL)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"t4".ID,
	"t4"."Value"
FROM
	SESSION."tmptbl1" "t2"
		LEFT JOIN SESSION."tmptbl2" "t3" ON "t2".ID = "t3".ID
		LEFT JOIN SESSION."tmptbl3" "t4" ON Coalesce("t3"."Value", "t2"."Value") = "t4"."Value" OR "t3"."Value" IS NULL AND "t2"."Value" IS NULL AND "t4"."Value" IS NULL

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"t1".ID,
	"t1"."Value"
FROM
	SESSION."tmptbl1" "t1"

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"t1".ID,
	"t1"."Value"
FROM
	SESSION."tmptbl2" "t1"

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"t1".ID,
	"t1"."Value"
FROM
	SESSION."tmptbl3" "t1"

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE SESSION."tmptbl3"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE SESSION."tmptbl2"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE SESSION."tmptbl1"';
END

