BeforeExecute
-- ClickHouse.Client ClickHouse

SELECT
	EXISTS(
		SELECT
			*
		FROM
			Parent p
		WHERE
			p.ParentID = 3 AND (p.Value1 = COALESCE(CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END, CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END) OR p.Value1 IS NULL AND COALESCE(CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END, CASE WHEN '' IS NULL THEN NULL ELSE CAST('3' AS INT) END) IS NULL)
	)

