BeforeExecute
-- Oracle.Managed Oracle12

DELETE FROM
	ALLTYPES t1
WHERE
	t1.ID >= 1000

BeforeExecute
-- Oracle.Managed Oracle12
DECLARE @p1 Clob(4000) -- Object
SET     @p1 = NULL
DECLARE @p2 NClob(4000) -- Object
SET     @p2 = NULL

INSERT ALL
	INTO ALLTYPES (ID, BIGINTDATATYPE, NUMERICDATATYPE, BITDATATYPE, SMALLINTDATATYPE, DECIMALDATATYPE, SMALLMONEYDATATYPE, INTDATATYPE, TINYINTDATATYPE, MONEYDATATYPE, FLOATDATATYPE, REALDATATYPE, DATETIMEDATATYPE, DATETIME2DATATYPE, DATETIMEOFFSETDATATYPE, LOCALZONEDATATYPE, CHARDATATYPE, VARCHARDATATYPE, TEXTDATATYPE, NCHARDATATYPE, NVARCHARDATATYPE, NTEXTDATATYPE, BINARYDATATYPE, BFILEDATATYPE, GUIDDATATYPE, LONGDATATYPE, URIDATATYPE, XMLDATATYPE) VALUES (1000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,TO_TIMESTAMP('2020-02-29 17:54:55.1231234', 'YYYY-MM-DD HH24:MI:SS.FF7'),TO_TIMESTAMP('2020-02-29 17:54:55.1231234', 'YYYY-MM-DD HH24:MI:SS.FF7'),NULL,NULL,NULL,NULL,:p1,NULL,NULL,:p2,NULL,NULL,NULL,NULL,NULL,NULL)
SELECT * FROM dual

