BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791Table"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Issue3791Table"
(
	"Id"      Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"OtherId" NVarChar(255)                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791GuidTable"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Issue3791GuidTable"
(
	"Id" Char (36) NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."Id",
	"t1"."OtherId",
	"a_Association"."Id"
FROM
	"Issue3791Table" "t1"
		LEFT JOIN "Issue3791GuidTable" "a_Association" ON "t1"."OtherId" = CAST("a_Association"."Id" AS NVarChar(36))

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791GuidTable"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791Table"

