BeforeExecute
-- SapHana.Native SapHana

RENAME TABLE "AllTypes" TO "AllTypes_OLD"

BeforeExecute
-- SapHana.Native SapHana


CREATE COLUMN TABLE "AllTypes"
(
	ID INTEGER CS_INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"bigintDataType" BIGINT NULL,
	"smallintDataType" SMALLINT NULL,
	"decimalDataType" DECIMAL NULL,
	"smalldecimalDataType" SMALLDECIMAL NULL,
	"intDataType" INTEGER NULL,
	"tinyintDataType" TINYINT NULL,
	"floatDataType" FLOAT NULL,
	"realDataType" REAL NULL,

	"dateDataType" DATE NULL,
	"timeDataType" TIME NULL,
	"seconddateDataType" SECONDDATE NULL,
	"timestampDataType" TIMESTAMP NULL,

	"charDataType" CHAR(1) NULL,
	"char20DataType" CHAR(20) NULL,
	"varcharDataType" VARCHAR(20) NULL,
	"textDataType" TEXT NULL,
	"shorttextDataType" SHORTTEXT(20) NULL,
	"ncharDataType" NCHAR(1) NULL,
	"nchar20DataType" NCHAR(20) NULL,
	"nvarcharDataType" NVARCHAR(20) NULL,
	"alphanumDataType" ALPHANUM(20) NULL,

	"binaryDataType" BINARY(10) NULL,
	"varbinaryDataType" VARBINARY(10) NULL,

	"blobDataType" BLOB NULL,
	"clobDataType" CLOB NULL,
	"nclobDataType" NCLOB NULL,
	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "AllTypes" SELECT ID, "bigintDataType", "smallintDataType", "decimalDataType", "smalldecimalDataType", "intDataType", "tinyintDataType", "floatDataType", "realDataType", "dateDataType", "timeDataType", "seconddateDataType", "timestampDataType", "charDataType", "char20DataType", "varcharDataType", "textDataType", "shorttextDataType", "ncharDataType", "nchar20DataType", "nvarcharDataType", "alphanumDataType", "binaryDataType", "varbinaryDataType", "blobDataType", "clobDataType", "nclobDataType" FROM "AllTypes_OLD"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "AllTypes_OLD"

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "AllTypes"
(
	"charDataType",
	"ncharDataType"
)
VALUES
(
	char(0),
	char(0)
)

BeforeExecute
-- SapHana.Native SapHana

SELECT MAX("ID") FROM "AllTypes"

BeforeExecute
-- SapHana.Native SapHana
DECLARE @id_1  -- Int32
SET     @id_1 = 1003

MERGE INTO "AllTypes" "Target"
USING (
	SELECT
		"t"."ID",
		"t"."charDataType",
		"t"."ncharDataType",
		"t"."nvarcharDataType"
	FROM
		"AllTypes" "t"
	WHERE
		"t"."ID" = :"id_1"
) "Source"
ON ("Target"."ID" = "Source"."ID")

WHEN MATCHED THEN
UPDATE
SET
	"Target"."charDataType" = "Source"."charDataType",
	"Target"."ncharDataType" = "Source"."ncharDataType",
	"Target"."nvarcharDataType" = "Source"."nvarcharDataType"

WHEN NOT MATCHED THEN
INSERT
(
	"charDataType",
	"ncharDataType",
	"nvarcharDataType"
)
VALUES
(
	"Source"."charDataType",
	"Source"."ncharDataType",
	"Source"."nvarcharDataType"
)

