BeforeExecute
-- SapHana.Native SapHana

CREATE COLUMN TABLE "Parent564"
(
	"Id"          Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Type"        NVarChar(255)                                      NULL,
	"StringValue" NVarChar(20)                                       NULL,
	"IntValue"    Integer                                            NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Type_1 NVarChar(9) -- String
SET     @Type_1 = 'Child564A'
DECLARE @StringValue NVarChar(9) -- String
SET     @StringValue = 'SomeValue'

INSERT INTO "Parent564"
(
	"Type",
	"StringValue"
)
VALUES
(
	:"Type_1",
	:"StringValue"
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Type_1 NVarChar(9) -- String
SET     @Type_1 = 'Child564B'
DECLARE @IntValue  -- Int32
SET     @IntValue = 911

INSERT INTO "Parent564"
(
	"Type",
	"IntValue"
)
VALUES
(
	:"Type_1",
	:"IntValue"
)

BeforeExecute
-- SapHana.Native SapHana

SELECT
	Count(*)
FROM
	"Parent564" "t1"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "Parent564"

