-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "TestTrun"';
END

-- DB2 DB2.LUW DB2LUW

CREATE TABLE "TestTrun"
(
	ID       Int             NOT NULL,
	"Field1" Decimal(18, 10) NOT NULL,

	CONSTRAINT "PK_TestTrun" PRIMARY KEY (ID)
)

-- DB2 DB2.LUW DB2LUW

TRUNCATE TABLE "TestTrun" IMMEDIATE

-- DB2 DB2.LUW DB2LUW

DROP TABLE "TestTrun"

