BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791Table"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Issue3791Table"
(
	"Id"      Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"OtherId" NVarChar(255)                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791GuidTable"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Issue3791GuidTable"
(
	"Id" Char (36) NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"t2"."Id",
	"t2"."OtherId",
	"t1"."Id"
FROM
	"Issue3791Table" "t2"
		LEFT JOIN (
			SELECT
				"a_Association"."Id",
				CAST("a_Association"."Id" AS NVarChar(36)) as "c1"
			FROM
				"Issue3791GuidTable" "a_Association"
		) "t1" ON ("t2"."OtherId" = "t1"."c1" OR "t2"."OtherId" IS NULL AND "t1"."c1" IS NULL)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791GuidTable"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue3791Table"

