-- SqlServer.2008

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[Parent] [p]
			WHERE
				[p].[ParentID] = 3 AND (COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) = [p].[Value1] OR COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) IS NULL AND [p].[Value1] IS NULL)
		)
			THEN 1
		ELSE 0
	END

