-- PostgreSQL.14 PostgreSQL.13 PostgreSQL

SELECT
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE CURRENT ROW),
	AVG(t."DoubleValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE TIES)
FROM
	"WindowFunctionTestEntity" t

