BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "activity649"
(
	"activityid" Integer   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personid"   Integer                                    NOT NULL,
	"added"      Timestamp                                  NOT NULL,

	PRIMARY KEY ("activityid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "person649"
(
	"personid"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personname" NVarChar(255)                                  NOT NULL,

	PRIMARY KEY ("personid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "person649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "activity649"

