BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Categories"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Categories"
(
	"CategoryID"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CategoryName" NVarChar(255)                                  NOT NULL,
	"Description"  NVarChar(255)                                      NULL,

	PRIMARY KEY ("CategoryID")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @CategoryName NVarChar(6) -- String
SET     @CategoryName = 'Name 1'
DECLARE @Description NVarChar(6) -- String
SET     @Description = 'Desc 1'

INSERT INTO "Categories"
(
	"CategoryName",
	"Description"
)
VALUES
(
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @CategoryName NVarChar(6) -- String
SET     @CategoryName = 'Name 2'
DECLARE @Description NVarChar(6) -- String
SET     @Description = 'Desc 2'

INSERT INTO "Categories"
(
	"CategoryName",
	"Description"
)
VALUES
(
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Products"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Products"
(
	"ProductID"       Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ProductName"     NVarChar(255)                                  NOT NULL,
	"CategoryID"      Integer                                            NULL,
	"QuantityPerUnit" NVarChar(255)                                      NULL,

	PRIMARY KEY ("ProductID")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @ProductName NVarChar(6) -- String
SET     @ProductName = 'Prod 1'
DECLARE @CategoryID  -- Int32
SET     @CategoryID = 1
DECLARE @QuantityPerUnit NVarChar(3) -- String
SET     @QuantityPerUnit = 'q 1'

INSERT INTO "Products"
(
	"ProductName",
	"CategoryID",
	"QuantityPerUnit"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @ProductName NVarChar(6) -- String
SET     @ProductName = 'Prod 2'
DECLARE @CategoryID  -- Int32
SET     @CategoryID = 1
DECLARE @QuantityPerUnit NVarChar(3) -- String
SET     @QuantityPerUnit = 'q 2'

INSERT INTO "Products"
(
	"ProductName",
	"CategoryID",
	"QuantityPerUnit"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @ProductName NVarChar(6) -- String
SET     @ProductName = 'Prod 3'
DECLARE @CategoryID  -- Int32
SET     @CategoryID = 3
DECLARE @QuantityPerUnit NVarChar(3) -- String
SET     @QuantityPerUnit = 'q 3'

INSERT INTO "Products"
(
	"ProductName",
	"CategoryID",
	"QuantityPerUnit"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @ProductName NVarChar(6) -- String
SET     @ProductName = 'Prod 4'
DECLARE @CategoryID  -- Int32
SET     @CategoryID = 3
DECLARE @QuantityPerUnit NVarChar(3) -- String
SET     @QuantityPerUnit = 'q 4'

INSERT INTO "Products"
(
	"ProductName",
	"CategoryID",
	"QuantityPerUnit"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @ProductName NVarChar(6) -- String
SET     @ProductName = 'Prod 5'
DECLARE @CategoryID  -- Int32
SET     @CategoryID = 1
DECLARE @QuantityPerUnit NVarChar(3) -- String
SET     @QuantityPerUnit = 'q 5'

INSERT INTO "Products"
(
	"ProductName",
	"CategoryID",
	"QuantityPerUnit"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @ProductName NVarChar(6) -- String
SET     @ProductName = 'Prod 6'
DECLARE @CategoryID  -- Int32
SET     @CategoryID = 1
DECLARE @QuantityPerUnit NVarChar(3) -- String
SET     @QuantityPerUnit = 'q 6'

INSERT INTO "Products"
(
	"ProductName",
	"CategoryID",
	"QuantityPerUnit"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
BeginTransaction(RepeatableRead)
BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"m_1"."CategoryID",
	"d"."ProductID",
	"d"."ProductName",
	"d"."CategoryID",
	"d"."QuantityPerUnit"
FROM
	"Categories" "m_1"
		INNER JOIN "Products" "d" ON "m_1"."CategoryID" = "d"."CategoryID" AND "d"."CategoryID" IS NOT NULL

BeforeExecute
DisposeTransaction
BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."CategoryID",
	"t1"."CategoryName",
	"t1"."Description"
FROM
	"Categories" "t1"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Products"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Categories"

