-- DB2 DB2.LUW DB2LUW

DECLARE GLOBAL TEMPORARY TABLE SESSION."TableWithPrimaryKey2"
(
	"Key" Int NOT NULL
)
ON COMMIT PRESERVE ROWS

-- DB2 DB2.LUW DB2LUW

INSERT INTO SESSION."TableWithPrimaryKey2"
(
	"Key"
)
VALUES
(1)

-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE SESSION."TableWithPrimaryKey2"';
END

