BeforeExecute
-- SqlServer.Contained.MS SqlServer.2019

SELECT
	IIF(EXISTS(
		SELECT
			*
		FROM
			[Parent] [p]
		WHERE
			[p].[ParentID] = 3 AND (COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) = [p].[Value1] OR COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) IS NULL AND [p].[Value1] IS NULL)
	), 1, 0)

