BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE MRECEIPT';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE MRECEIPT
		(
			RECEIPT_NO NVarChar(255)     NULL,
			CUSTKEY    NVarChar(255)     NULL
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE EXTERNAL_RECEIPTS';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE EXTERNAL_RECEIPTS
		(
			RECEIPT_NO NVarChar(255)     NULL,
			CUSTKEY    NVarChar(255)     NULL
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE CUST_DTL';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE CUST_DTL
		(
			CUSTKEY   NVarChar(255)     NULL,
			BILLGROUP NVarChar(255)     NULL
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"i_1"."ReceiptNo",
	"a_Customer".BILLGROUP
FROM
	(
		SELECT
			"i".RECEIPT_NO as "ReceiptNo",
			"i".CUSTKEY as "Custkey"
		FROM
			MRECEIPT "i"
		UNION ALL
		SELECT
			"t1".RECEIPT_NO as "ReceiptNo",
			"t1".CUSTKEY as "Custkey"
		FROM
			EXTERNAL_RECEIPTS "t1"
	) "i_1"
		LEFT JOIN CUST_DTL "a_Customer" ON ("i_1"."Custkey" = "a_Customer".CUSTKEY OR "i_1"."Custkey" IS NULL AND "a_Customer".CUSTKEY IS NULL)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE CUST_DTL';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE EXTERNAL_RECEIPTS';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE MRECEIPT';
END

