BeforeExecute
-- Oracle.11.Managed Oracle.Managed Oracle11
DECLARE @date_1 Date
SET     @date_1 = TO_TIMESTAMP('2020-02-29 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6')
DECLARE @take Int32
SET     @take = 1

SELECT 
	a.ID, 
	a.BIGINTDATATYPE, 
	a.NUMERICDATATYPE, 
	a.BITDATATYPE, 
	a.SMALLINTDATATYPE, 
	a.DECIMALDATATYPE, 
	a.SMALLMONEYDATATYPE, 
	a.INTDATATYPE, 
	a.TINYINTDATATYPE, 
	a.MONEYDATATYPE, 
	a.FLOATDATATYPE, 
	a.REALDATATYPE, 
	a.DATETIMEDATATYPE, 
	a.DATETIME2DATATYPE, 
	a.DATETIMEOFFSETDATATYPE, 
	a.LOCALZONEDATATYPE, 
	a.CHARDATATYPE, 
	a.VARCHARDATATYPE, 
	a.TEXTDATATYPE, 
	a.NCHARDATATYPE, 
	a.NVARCHARDATATYPE, 
	a.NTEXTDATATYPE, 
	a.BINARYDATATYPE, 
	a.BFILEDATATYPE, 
	a.GUIDDATATYPE, 
	a.LONGDATATYPE, 
	a.URIDATATYPE, 
	a.XMLDATATYPE
FROM
	ALLTYPES a
WHERE
	a.DATETIMEDATATYPE = :date_1 AND ROWNUM <= :take

