BeforeExecute
-- Oracle.11.Managed Oracle.Managed Oracle11

CREATE TABLE ISSUE723TABLE
(
	"Id" Int  NOT NULL,

	CONSTRAINT PK_ISSUE723TABLE PRIMARY KEY ("Id")
)

BeforeExecute
-- Oracle.11.Managed Oracle.Managed Oracle11

CREATE SEQUENCE SIDENTITY_ISSUE723TABLE

BeforeExecute
-- Oracle.11.Managed Oracle.Managed Oracle11

CREATE OR REPLACE TRIGGER TIDENTITY_ISSUE723TABLE
BEFORE INSERT ON ISSUE723TABLE FOR EACH ROW
BEGIN
	SELECT SIDENTITY_ISSUE723TABLE.NEXTVAL INTO :NEW."Id" FROM dual;
END;

BeforeExecute
-- Oracle.11.Managed Oracle.Managed Oracle11

BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIDENTITY_ISSUE723TABLE';
	EXECUTE IMMEDIATE 'DROP SEQUENCE SIDENTITY_ISSUE723TABLE';
	EXECUTE IMMEDIATE 'DROP TABLE ISSUE723TABLE';
END;

