BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue3791Table"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Issue3791Table"
		(
			"Id"      Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"OtherId" NVarChar(255)                                  NULL,

			CONSTRAINT "PK_Issue3791Table" PRIMARY KEY ("Id")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue3791GuidTable"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Issue3791GuidTable"
		(
			"Id" char(16) for bit data NOT NULL,

			CONSTRAINT "PK_Issue3791GuidTable" PRIMARY KEY ("Id")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"t2"."Id",
	"t2"."OtherId",
	"t1"."Id"
FROM
	"Issue3791Table" "t2"
		LEFT JOIN (
			SELECT
				"a_Association"."Id",
				RTrim(Char("a_Association"."Id")) as "c1"
			FROM
				"Issue3791GuidTable" "a_Association"
		) "t1" ON ("t2"."OtherId" = "t1"."c1" OR "t2"."OtherId" IS NULL AND "t1"."c1" IS NULL)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue3791GuidTable"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Issue3791Table"';
END

