BeforeExecute
-- Oracle.11.Managed Oracle11

SELECT
	TO_TIMESTAMP(EXTRACT(YEAR FROM p."DateTimeValue") || '-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM
	"LinqDataTypes" p
WHERE
	EXTRACT(DAY FROM TO_TIMESTAMP(EXTRACT(YEAR FROM p."DateTimeValue") || '-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')) > 0

