-- SqlServer.2014.MS SqlServer.2014
SELECT
	[t].[Id],
	LAST_VALUE(IIF([t].[IntValue] = 20, 1, 0)) OVER (PARTITION BY [t].[CategoryId] ORDER BY [t].[Id] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING),
	LAST_VALUE([t].[IntValue]) OVER (PARTITION BY [t].[CategoryId] ORDER BY [t].[Id] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
FROM
	[WindowFunctionTestEntity] [t]
ORDER BY
	[t].[Id]

