-- DB2 DB2.LUW DB2LUW

SELECT
	SUM("t"."IntValue") OVER (PARTITION BY "t"."CategoryId" ORDER BY "t"."Id" RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM("t"."IntValue") OVER (PARTITION BY "t"."CategoryId" ORDER BY "t"."Id" RANGE BETWEEN CURRENT ROW AND CURRENT ROW),
	SUM("t"."IntValue") OVER (PARTITION BY "t"."CategoryId" ORDER BY "t"."Id" RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM("t"."IntValue") OVER (PARTITION BY "t"."CategoryId" ORDER BY "t"."Id" RANGE BETWEEN CURRENT ROW AND CURRENT ROW)
FROM
	"WindowFunctionTestEntity" "t"

