-- SqlServer.2017

SELECT
	IIF(EXISTS(
		SELECT
			*
		FROM
			[Parent] [p]
		WHERE
			[p].[ParentID] = 3 AND ([p].[Value1] = COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) OR [p].[Value1] IS NULL AND COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) IS NULL)
	), 1, 0)

