-- ClickHouse.MySql ClickHouse
SELECT
	longLongLongLongVeryLongVeryVeryLongVeryVeryLongLongAliasNameTestParent.ParentID,
	longLongLongLongVeryLongVeryVeryLongVeryVeryLongLongAliasNameTestParent.Value1
FROM
	Parent longLongLongLongVeryLongVeryVeryLongVeryVeryLongLongAliasNameTestParent
		INNER JOIN Child longLongLongLongVeryLongVeryVeryLongVeryVeryLongLongAliasNameTestChild ON longLongLongLongVeryLongVeryVeryLongVeryVeryLongLongAliasNameTestChild.ParentID = longLongLongLongVeryLongVeryVeryLongVeryVeryLongLongAliasNameTestParent.ParentID
WHERE
	longLongLongLongVeryLongVeryVeryLongVeryVeryLongLongAliasNameTestParent.ParentID = 1

