-- SqlServer.2016.MS SqlServer.2016

SELECT
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)
FROM
	[WindowFunctionTestEntity] [t]

