-- SqlServer.Northwind SqlServer.2019

SELECT
	[bind2].[OrderID],
	[bind2].[EmployeeID],
	[bind2].[OrderDate],
	[bind2].[RequiredDate],
	[bind2].[ShippedDate],
	[bind2].[ShipVia],
	[bind2].[Freight],
	[a_Shipper].[ShipperID],
	[a_Shipper].[CompanyName],
	[a_Shipper].[Phone],
	[a_Employee].[EmployeeID],
	[a_Employee].[LastName],
	[a_Employee].[FirstName],
	[a_Employee].[Title],
	[a_Employee].[TitleOfCourtesy],
	[a_Employee].[BirthDate],
	[a_Employee].[HireDate],
	[a_Employee].[Address],
	[a_Employee].[City],
	[a_Employee].[Region],
	[a_Employee].[PostalCode],
	[a_Employee].[Country],
	[a_Employee].[HomePhone],
	[a_Employee].[Extension],
	[a_Employee].[Photo],
	[a_Employee].[Notes],
	[a_Employee].[ReportsTo],
	[a_Employee].[PhotoPath],
	[a_Customer].[CustomerID],
	[a_Customer].[CompanyName],
	[a_Customer].[ContactName],
	[a_Customer].[ContactTitle],
	[a_Customer].[Address],
	[a_Customer].[City],
	[a_Customer].[Region],
	[a_Customer].[PostalCode],
	[a_Customer].[Country],
	[a_Customer].[Phone],
	[a_Customer].[Fax],
	[bind3].[OrderID],
	[bind3].[ProductID],
	[bind3].[UnitPrice],
	[bind3].[Quantity],
	[bind3].[Discount],
	[e].[EmployeeID],
	[e].[BirthDate],
	[e].[HireDate],
	[e].[ReportsTo],
	[bind1].[EmployeeID],
	[bind1].[LastName],
	[bind1].[FirstName],
	[bind1].[Title],
	[bind1].[TitleOfCourtesy],
	[bind1].[BirthDate],
	[bind1].[HireDate],
	[bind1].[Address],
	[bind1].[City],
	[bind1].[Region],
	[bind1].[PostalCode],
	[bind1].[Country],
	[bind1].[HomePhone],
	[bind1].[Extension],
	[bind1].[Photo],
	[bind1].[Notes],
	[bind1].[ReportsTo],
	[bind1].[PhotoPath],
	[bind4].[EmployeeID],
	[a_Employee_1].[EmployeeID],
	[a_Employee_1].[LastName],
	[a_Employee_1].[FirstName],
	[a_Employee_1].[Title],
	[a_Employee_1].[TitleOfCourtesy],
	[a_Employee_1].[BirthDate],
	[a_Employee_1].[HireDate],
	[a_Employee_1].[Address],
	[a_Employee_1].[City],
	[a_Employee_1].[Region],
	[a_Employee_1].[PostalCode],
	[a_Employee_1].[Country],
	[a_Employee_1].[HomePhone],
	[a_Employee_1].[Extension],
	[a_Employee_1].[Photo],
	[a_Employee_1].[Notes],
	[a_Employee_1].[ReportsTo],
	[a_Employee_1].[PhotoPath],
	[bind5].[TerritoryID],
	[bind5].[TerritoryDescription],
	[bind5].[RegionID],
	[bind6].[RegionID],
	[bind6].[RegionDescription]
FROM
	[Employees] [e]
		LEFT JOIN [Employees] [bind1] ON [e].[ReportsTo] = [bind1].[EmployeeID]
		LEFT JOIN [Orders] [bind2] ON [e].[EmployeeID] = [bind2].[EmployeeID]
		LEFT JOIN [Shippers] [a_Shipper] ON [bind2].[ShipVia] = [a_Shipper].[ShipperID]
		LEFT JOIN [Employees] [a_Employee] ON [bind2].[EmployeeID] = [a_Employee].[EmployeeID]
		INNER JOIN [Customers] [a_Customer] ON [bind2].[CustomerID] = [a_Customer].[CustomerID]
		LEFT JOIN [Order Details] [bind3] ON [bind2].[OrderID] = [bind3].[OrderID]
		LEFT JOIN [EmployeeTerritories] [bind4] ON [e].[EmployeeID] = [bind4].[EmployeeID]
		LEFT JOIN [Employees] [a_Employee_1] ON [bind4].[EmployeeID] = [a_Employee_1].[EmployeeID]
		LEFT JOIN [Territories] [bind5] ON [bind4].[TerritoryID] = [bind5].[TerritoryID]
		LEFT JOIN [Region] [bind6] ON [bind5].[RegionID] = [bind6].[RegionID]
WHERE
	[e].[EmployeeID] = 5

