-- SqlServer.Northwind SqlServer.2019

SELECT
	[bind_1].[OrderID],
	[bind_1].[EmployeeID],
	[bind_1].[OrderDate],
	[bind_1].[RequiredDate],
	[bind_1].[ShippedDate],
	[bind_1].[ShipVia],
	[bind_1].[Freight],
	[a_Shipper].[ShipperID],
	[a_Shipper].[CompanyName],
	[a_Shipper].[Phone],
	[a_Employee].[EmployeeID],
	[a_Employee].[LastName],
	[a_Employee].[FirstName],
	[a_Employee].[Title],
	[a_Employee].[TitleOfCourtesy],
	[a_Employee].[BirthDate],
	[a_Employee].[HireDate],
	[a_Employee].[Address],
	[a_Employee].[City],
	[a_Employee].[Region],
	[a_Employee].[PostalCode],
	[a_Employee].[Country],
	[a_Employee].[HomePhone],
	[a_Employee].[Extension],
	[a_Employee].[Photo],
	[a_Employee].[Notes],
	[a_Employee].[ReportsTo],
	[a_Employee].[PhotoPath],
	[a_Customer].[CustomerID],
	[a_Customer].[CompanyName],
	[a_Customer].[ContactName],
	[a_Customer].[ContactTitle],
	[a_Customer].[Address],
	[a_Customer].[City],
	[a_Customer].[Region],
	[a_Customer].[PostalCode],
	[a_Customer].[Country],
	[a_Customer].[Phone],
	[a_Customer].[Fax],
	[bind_2].[OrderID],
	[bind_2].[ProductID],
	[bind_2].[UnitPrice],
	[bind_2].[Quantity],
	[bind_2].[Discount],
	[e].[EmployeeID],
	[e].[BirthDate],
	[e].[HireDate],
	[e].[ReportsTo],
	[bind].[EmployeeID],
	[bind].[LastName],
	[bind].[FirstName],
	[bind].[Title],
	[bind].[TitleOfCourtesy],
	[bind].[BirthDate],
	[bind].[HireDate],
	[bind].[Address],
	[bind].[City],
	[bind].[Region],
	[bind].[PostalCode],
	[bind].[Country],
	[bind].[HomePhone],
	[bind].[Extension],
	[bind].[Photo],
	[bind].[Notes],
	[bind].[ReportsTo],
	[bind].[PhotoPath],
	[bind_3].[EmployeeID],
	[a_Employee_1].[EmployeeID],
	[a_Employee_1].[LastName],
	[a_Employee_1].[FirstName],
	[a_Employee_1].[Title],
	[a_Employee_1].[TitleOfCourtesy],
	[a_Employee_1].[BirthDate],
	[a_Employee_1].[HireDate],
	[a_Employee_1].[Address],
	[a_Employee_1].[City],
	[a_Employee_1].[Region],
	[a_Employee_1].[PostalCode],
	[a_Employee_1].[Country],
	[a_Employee_1].[HomePhone],
	[a_Employee_1].[Extension],
	[a_Employee_1].[Photo],
	[a_Employee_1].[Notes],
	[a_Employee_1].[ReportsTo],
	[a_Employee_1].[PhotoPath],
	[bind_4].[TerritoryID],
	[bind_4].[TerritoryDescription],
	[bind_4].[RegionID],
	[bind_5].[RegionID],
	[bind_5].[RegionDescription]
FROM
	[Employees] [e]
		LEFT JOIN [Employees] [bind] ON [e].[ReportsTo] = [bind].[EmployeeID]
		LEFT JOIN [Orders] [bind_1] ON [e].[EmployeeID] = [bind_1].[EmployeeID]
		LEFT JOIN [Shippers] [a_Shipper] ON [bind_1].[ShipVia] = [a_Shipper].[ShipperID]
		LEFT JOIN [Employees] [a_Employee] ON [bind_1].[EmployeeID] = [a_Employee].[EmployeeID]
		INNER JOIN [Customers] [a_Customer] ON [bind_1].[CustomerID] = [a_Customer].[CustomerID]
		LEFT JOIN [Order Details] [bind_2] ON [bind_1].[OrderID] = [bind_2].[OrderID]
		LEFT JOIN [EmployeeTerritories] [bind_3] ON [e].[EmployeeID] = [bind_3].[EmployeeID]
		LEFT JOIN [Employees] [a_Employee_1] ON [bind_3].[EmployeeID] = [a_Employee_1].[EmployeeID]
		LEFT JOIN [Territories] [bind_4] ON [bind_3].[TerritoryID] = [bind_4].[TerritoryID]
		LEFT JOIN [Region] [bind_5] ON [bind_4].[RegionID] = [bind_5].[RegionID]
WHERE
	[e].[EmployeeID] = 5

