BeforeExecute
-- ClickHouse.Client ClickHouse

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				AllTypes p
			WHERE
				p.ID = toInt32(2) AND (COALESCE(CASE WHEN p.char20DataType IS NULL THEN NULL ELSE CAST('1' AS INT) END, CASE WHEN p.char20DataType IS NULL THEN NULL ELSE CAST('1' AS INT) END) <> p.intDataType OR COALESCE(CASE WHEN p.char20DataType IS NULL THEN NULL ELSE CAST('1' AS INT) END, CASE WHEN p.char20DataType IS NULL THEN NULL ELSE CAST('1' AS INT) END) IS NULL AND p.intDataType IS NOT NULL OR COALESCE(CASE WHEN p.char20DataType IS NULL THEN NULL ELSE CAST('1' AS INT) END, CASE WHEN p.char20DataType IS NULL THEN NULL ELSE CAST('1' AS INT) END) IS NOT NULL AND p.intDataType IS NULL)
		)
			THEN toInt32(1)
		ELSE toInt32(0)
	END

