BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Table1"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Table1"
(
	"Field1" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Field2" Integer                                  NOT NULL,

	PRIMARY KEY ("Field1")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Table2"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Table2"
(
	"Field2" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Field2")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."Field2"
FROM
	"Table2" "t1"
WHERE
	 EXISTS (
		SELECT
			*
		FROM
			"Table1" "x"
		WHERE
			"t1"."Field2" = "x"."Field2" AND CAST("x"."Field1" AS BigInt) IN (1, 2, 3)
	)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Table2"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Table1"

