BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "DctSetpointtype"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "VWellTree"
(
	"ShopId" Decimal     NULL,
	"WellId" Integer     NULL
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "DctOu"
(
	"ParentId" Integer                                      NULL,
	"Id"       Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "UacUsersDatagroup"
(
	"Inheritablepermission" Integer NOT NULL,
	"Permission"            Integer NOT NULL,
	"DatagroupId"           Integer NOT NULL,
	"UserId"                Integer NOT NULL,

	PRIMARY KEY ("UserId", "DatagroupId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Deviation"
(
	"WellId"         Integer NOT NULL,
	"SetpointtypeId" Integer NOT NULL
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"spt"."Id"
FROM
	"DctSetpointtype" "spt"
		LEFT JOIN (
			SELECT
				"d"."SetpointtypeId",
				"cudg"."Permission",
				"oudg"."Inheritablepermission"
			FROM
				"VWellTree" "w"
					INNER JOIN "DctOu" "c_1" ON "w"."ShopId" = "c_1"."Id"
					LEFT JOIN "UacUsersDatagroup" "oudg" ON "c_1"."ParentId" = "oudg"."DatagroupId" AND "oudg"."UserId" = 150 AND "oudg"."Inheritablepermission" > 0
					LEFT JOIN "UacUsersDatagroup" "cudg" ON "c_1"."Id" = "cudg"."DatagroupId" AND "cudg"."UserId" = 150
					INNER JOIN "Deviation" "d" ON "w"."WellId" = "d"."WellId"
		) "t1" ON "t1"."SetpointtypeId" = "spt"."Id" AND Cast(("t1"."Permission" + "t1"."Inheritablepermission") as Decimal(29, 10)) IS NOT NULL

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Deviation"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "UacUsersDatagroup"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DctOu"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "VWellTree"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DctSetpointtype"

