BeforeExecute
-- SqlServer.2016 (asynchronously)

SELECT
	IIF(EXISTS(
		SELECT
			*
		FROM
			[Parent] [p]
		WHERE
			[p].[ParentID] = 3 AND ([p].[Value1] <> COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END) OR [p].[Value1] IS NULL AND COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END) IS NOT NULL OR [p].[Value1] IS NOT NULL AND COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END) IS NULL)
	), 1, 0)

