BeforeExecute
-- SapHana.Native SapHana

CREATE COLUMN TABLE "Stone"
(
	"Id"           Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Name"         NVarChar(255)                                  NOT NULL,
	"Enabled"      TinyInt                                            NULL,
	"ImageFullUrl" NVarChar(255)                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group1'
DECLARE @Enabled  -- Byte
SET     @Enabled = 1
DECLARE @ImageFullUrl NVarChar(3) -- String
SET     @ImageFullUrl = '123'

INSERT INTO "Stone"
(
	"Name",
	"Enabled",
	"ImageFullUrl"
)
VALUES
(
	:"Name",
	:"Enabled",
	:"ImageFullUrl"
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group1'
DECLARE @Enabled  -- Byte
SET     @Enabled = 1
DECLARE @ImageFullUrl NVarChar(3) -- String
SET     @ImageFullUrl = '123'

INSERT INTO "Stone"
(
	"Name",
	"Enabled",
	"ImageFullUrl"
)
VALUES
(
	:"Name",
	:"Enabled",
	:"ImageFullUrl"
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group2'
DECLARE @Enabled  -- Byte
SET     @Enabled = 1
DECLARE @ImageFullUrl NVarChar(3) -- String
SET     @ImageFullUrl = '123'

INSERT INTO "Stone"
(
	"Name",
	"Enabled",
	"ImageFullUrl"
)
VALUES
(
	:"Name",
	:"Enabled",
	:"ImageFullUrl"
)

BeforeExecute
-- SapHana.Native SapHana

SELECT
	"s"."Name"
FROM
	"Stone" "s"
WHERE
	("s"."Enabled" = 1 AND "s"."Enabled" IS NOT NULL) AND
	"s"."Name" NOT LIKE 'level - %' AND Length("s"."ImageFullUrl") > 0
GROUP BY
	"s"."Name"

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Name_1 NVarChar(6) -- String
SET     @Name_1 = 'group1'

SELECT
	"s"."Id",
	"s"."Name",
	"s"."Enabled",
	"s"."ImageFullUrl"
FROM
	"Stone" "s"
WHERE
	("s"."Enabled" = 1 AND "s"."Enabled" IS NOT NULL) AND
	"s"."Name" NOT LIKE 'level - %' AND
	Length("s"."ImageFullUrl") > 0 AND
	"s"."Name" = :"Name_1"

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Name_1 NVarChar(6) -- String
SET     @Name_1 = 'group2'

SELECT
	"s"."Id",
	"s"."Name",
	"s"."Enabled",
	"s"."ImageFullUrl"
FROM
	"Stone" "s"
WHERE
	("s"."Enabled" = 1 AND "s"."Enabled" IS NOT NULL) AND
	"s"."Name" NOT LIKE 'level - %' AND
	Length("s"."ImageFullUrl") > 0 AND
	"s"."Name" = :"Name_1"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "Stone"

