-- PostgreSQL.9.2 PostgreSQL
SELECT
	t."Id",
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" RANGE BETWEEN CURRENT ROW AND CURRENT ROW),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" RANGE BETWEEN CURRENT ROW AND CURRENT ROW)
FROM
	"WindowFunctionTestEntity" t

