BeforeExecute
-- SqlServer.2008.MS SqlServer.2008 (asynchronously)

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[Parent] [p]
			WHERE
				[p].[ParentID] = 2 AND (COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) <> [p].[Value1] OR COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) IS NULL AND [p].[Value1] IS NOT NULL OR COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) IS NOT NULL AND [p].[Value1] IS NULL)
		)
			THEN 1
		ELSE 0
	END

