BeforeExecute
-- SqlServer.2008.MS SqlServer.2008 (asynchronously)

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[AllTypes] [p]
			WHERE
				[p].[ID] = 2 AND (COALESCE(CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) <> [p].[intDataType] OR COALESCE(CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) IS NULL AND [p].[intDataType] IS NOT NULL OR COALESCE(CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[char20DataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) IS NOT NULL AND [p].[intDataType] IS NULL)
		)
			THEN 1
		ELSE 0
	END

