-- SqlServer.2005.MS SqlServer.2005

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[Parent] [p]
			WHERE
				[p].[ParentID] = 2 AND ([p].[Value1] <> COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) OR [p].[Value1] IS NULL AND COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) IS NOT NULL OR [p].[Value1] IS NOT NULL AND COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) IS NULL)
		)
			THEN 1
		ELSE 0
	END

