-- SqlServer.2025 SqlServer.2022

SELECT
	IIF(EXISTS(
		SELECT
			*
		FROM
			[Parent] [p]
		WHERE
			[p].[ParentID] = 2 AND ([p].[Value1] <> COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) OR [p].[Value1] IS NULL AND COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) IS NOT NULL OR [p].[Value1] IS NOT NULL AND COALESCE(CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END, CASE WHEN N'4' IS NULL THEN NULL ELSE CAST(N'4' AS INT) END) IS NULL)
	), 1, 0)

