BeforeExecute
-- Oracle.21.Managed Oracle.Managed Oracle12

INSERT ALL
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (375,1,20224,'Gas Month',NULL,NULL,NULL)
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (328,1,20224,'Gas Month',NULL,NULL,NULL)
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (348,1,20224,'Gas Month',NULL,NULL,NULL)
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (357,1,20224,'Gas Month',NULL,NULL,NULL)
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (371,1,20224,'Gas Month',NULL,NULL,NULL)
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (333,1,20224,'Gas Month',NULL,1,TIMESTAMP '2011-01-05 00:00:00.000000')
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (353,1,20224,'Gas Month',NULL,1000000000,NULL)
	INTO STG_TRADE_INFORMATION (STG_TRADE_ID, STG_TRADE_VERSION, INFORMATION_TYPE_ID, INFORMATION_TYPE_NAME, VALUE, VALUE_AS_INTEGER, VALUE_AS_DATE) VALUES (973,1,20160,'EU Allowances',NULL,NULL,NULL)
SELECT * FROM dual

