BeforeExecute
-- Oracle.21.Managed Oracle.Managed Oracle12

SELECT
	sys_context('userenv','service_name')
FROM SYS.DUAL

BeforeExecute
-- Oracle.21.Managed Oracle.Managed Oracle12

INSERT ALL
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (1)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (2)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (3)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (4)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (5)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (6)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (7)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (8)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (9)
	INTO BULKCOPYTABLE@"xe" (ID) VALUES (10)
SELECT * FROM dual

