BeforeExecute
-- Firebird.4 Firebird4

EXECUTE BLOCK AS BEGIN
	IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'VEMPLOYEE_SCH_SEC')) THEN
		EXECUTE STATEMENT 'DROP TABLE VEMPLOYEE_SCH_SEC';
END

BeforeExecute
-- Firebird.4 Firebird4

EXECUTE BLOCK AS BEGIN
	IF (NOT EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'VEMPLOYEE_SCH_SEC')) THEN
		EXECUTE STATEMENT '
			CREATE TABLE VEMPLOYEE_SCH_SEC
			(
				ACTIVE BOOLEAN                                NOT NULL,
				ID     Int                                    NOT NULL,
				NAME   VarChar(255) CHARACTER SET UNICODE_FSS NOT NULL,

				CONSTRAINT PK_VEMPLOYEE_SCH_SEC PRIMARY KEY (ID)
			)
		';
END

BeforeExecute
-- Firebird.4 Firebird4

EXECUTE BLOCK AS BEGIN
	IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'VEMPLOYEE_SCHDL_PERM')) THEN
		EXECUTE STATEMENT 'DROP TABLE VEMPLOYEE_SCHDL_PERM';
END

BeforeExecute
-- Firebird.4 Firebird4

EXECUTE BLOCK AS BEGIN
	IF (NOT EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'VEMPLOYEE_SCHDL_PERM')) THEN
		EXECUTE STATEMENT '
			CREATE TABLE VEMPLOYEE_SCHDL_PERM
			(
				ID        Int     NOT NULL,
				IS_ACTIVE BOOLEAN NOT NULL,

				CONSTRAINT PK_VEMPLOYEE_SCHDL_PERM PRIMARY KEY (ID)
			)
		';
END

BeforeExecute
-- Firebird.4 Firebird4

SELECT
	"ess".ID
FROM
	VEMPLOYEE_SCH_SEC "ess"
WHERE
	EXISTS(
		SELECT
			1
		FROM
			VEMPLOYEE_SCHDL_PERM "y"
		WHERE
			"ess".ID = "y".ID AND "y".IS_ACTIVE = TRUE
	)

BeforeExecute
-- Firebird.4 Firebird4

EXECUTE BLOCK AS BEGIN
	IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'VEMPLOYEE_SCHDL_PERM')) THEN
		EXECUTE STATEMENT 'DROP TABLE VEMPLOYEE_SCHDL_PERM';
END

BeforeExecute
-- Firebird.4 Firebird4

EXECUTE BLOCK AS BEGIN
	IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'VEMPLOYEE_SCH_SEC')) THEN
		EXECUTE STATEMENT 'DROP TABLE VEMPLOYEE_SCH_SEC';
END

