BeforeExecute
--  Oracle.12.Managed Oracle.Managed Oracle12

SELECT
	sys_context('userenv','service_name')
FROM SYS.DUAL

BeforeExecute
--  Oracle.12.Managed Oracle.Managed Oracle12

INSERT ALL
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (1)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (2)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (3)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (4)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (5)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (6)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (7)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (8)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (9)
	INTO BULKCOPYTABLE@ORC12 (ID) VALUES (10)
SELECT * FROM dual

