-- Oracle.12.Managed Oracle.Managed Oracle12

CREATE TABLE "UseAlternativeBulkCopy"
(
	"Id"    Int NOT NULL,
	"Value" Int NOT NULL
)

-- Oracle.12.Managed Oracle.Managed Oracle12

INSERT INTO "UseAlternativeBulkCopy"
(
	"Id",
	"Value"
)

	SELECT 0,0 FROM DUAL  UNION ALL
	SELECT 1,1 FROM DUAL  UNION ALL
	SELECT 2,2 FROM DUAL  UNION ALL
	SELECT 3,3 FROM DUAL  UNION ALL
	SELECT 4,4 FROM DUAL  UNION ALL
	SELECT 5,5 FROM DUAL  UNION ALL
	SELECT 6,6 FROM DUAL  UNION ALL
	SELECT 7,7 FROM DUAL  UNION ALL
	SELECT 8,8 FROM DUAL  UNION ALL
	SELECT 9,9 FROM DUAL  UNION ALL
	SELECT 10,10 FROM DUAL  UNION ALL
	SELECT 11,11 FROM DUAL  UNION ALL
	SELECT 12,12 FROM DUAL  UNION ALL
	SELECT 13,13 FROM DUAL  UNION ALL
	SELECT 14,14 FROM DUAL  UNION ALL
	SELECT 15,15 FROM DUAL  UNION ALL
	SELECT 16,16 FROM DUAL  UNION ALL
	SELECT 17,17 FROM DUAL  UNION ALL
	SELECT 18,18 FROM DUAL  UNION ALL
	SELECT 19,19 FROM DUAL  UNION ALL
	SELECT 20,20 FROM DUAL  UNION ALL
	SELECT 21,21 FROM DUAL  UNION ALL
	SELECT 22,22 FROM DUAL  UNION ALL
	SELECT 23,23 FROM DUAL  UNION ALL
	SELECT 24,24 FROM DUAL 

-- Oracle.12.Managed Oracle.Managed Oracle12

INSERT INTO "UseAlternativeBulkCopy"
(
	"Id",
	"Value"
)

	SELECT 25,25 FROM DUAL  UNION ALL
	SELECT 26,26 FROM DUAL  UNION ALL
	SELECT 27,27 FROM DUAL  UNION ALL
	SELECT 28,28 FROM DUAL  UNION ALL
	SELECT 29,29 FROM DUAL  UNION ALL
	SELECT 30,30 FROM DUAL  UNION ALL
	SELECT 31,31 FROM DUAL  UNION ALL
	SELECT 32,32 FROM DUAL  UNION ALL
	SELECT 33,33 FROM DUAL  UNION ALL
	SELECT 34,34 FROM DUAL  UNION ALL
	SELECT 35,35 FROM DUAL  UNION ALL
	SELECT 36,36 FROM DUAL  UNION ALL
	SELECT 37,37 FROM DUAL  UNION ALL
	SELECT 38,38 FROM DUAL  UNION ALL
	SELECT 39,39 FROM DUAL  UNION ALL
	SELECT 40,40 FROM DUAL  UNION ALL
	SELECT 41,41 FROM DUAL  UNION ALL
	SELECT 42,42 FROM DUAL  UNION ALL
	SELECT 43,43 FROM DUAL  UNION ALL
	SELECT 44,44 FROM DUAL  UNION ALL
	SELECT 45,45 FROM DUAL  UNION ALL
	SELECT 46,46 FROM DUAL  UNION ALL
	SELECT 47,47 FROM DUAL  UNION ALL
	SELECT 48,48 FROM DUAL  UNION ALL
	SELECT 49,49 FROM DUAL 

-- Oracle.12.Managed Oracle.Managed Oracle12

INSERT INTO "UseAlternativeBulkCopy"
(
	"Id",
	"Value"
)

	SELECT 50,50 FROM DUAL  UNION ALL
	SELECT 51,51 FROM DUAL  UNION ALL
	SELECT 52,52 FROM DUAL  UNION ALL
	SELECT 53,53 FROM DUAL  UNION ALL
	SELECT 54,54 FROM DUAL  UNION ALL
	SELECT 55,55 FROM DUAL  UNION ALL
	SELECT 56,56 FROM DUAL  UNION ALL
	SELECT 57,57 FROM DUAL  UNION ALL
	SELECT 58,58 FROM DUAL  UNION ALL
	SELECT 59,59 FROM DUAL  UNION ALL
	SELECT 60,60 FROM DUAL  UNION ALL
	SELECT 61,61 FROM DUAL  UNION ALL
	SELECT 62,62 FROM DUAL  UNION ALL
	SELECT 63,63 FROM DUAL  UNION ALL
	SELECT 64,64 FROM DUAL  UNION ALL
	SELECT 65,65 FROM DUAL  UNION ALL
	SELECT 66,66 FROM DUAL  UNION ALL
	SELECT 67,67 FROM DUAL  UNION ALL
	SELECT 68,68 FROM DUAL  UNION ALL
	SELECT 69,69 FROM DUAL  UNION ALL
	SELECT 70,70 FROM DUAL  UNION ALL
	SELECT 71,71 FROM DUAL  UNION ALL
	SELECT 72,72 FROM DUAL  UNION ALL
	SELECT 73,73 FROM DUAL  UNION ALL
	SELECT 74,74 FROM DUAL 

-- Oracle.12.Managed Oracle.Managed Oracle12

INSERT INTO "UseAlternativeBulkCopy"
(
	"Id",
	"Value"
)

	SELECT 75,75 FROM DUAL  UNION ALL
	SELECT 76,76 FROM DUAL  UNION ALL
	SELECT 77,77 FROM DUAL  UNION ALL
	SELECT 78,78 FROM DUAL  UNION ALL
	SELECT 79,79 FROM DUAL  UNION ALL
	SELECT 80,80 FROM DUAL  UNION ALL
	SELECT 81,81 FROM DUAL  UNION ALL
	SELECT 82,82 FROM DUAL  UNION ALL
	SELECT 83,83 FROM DUAL  UNION ALL
	SELECT 84,84 FROM DUAL  UNION ALL
	SELECT 85,85 FROM DUAL  UNION ALL
	SELECT 86,86 FROM DUAL  UNION ALL
	SELECT 87,87 FROM DUAL  UNION ALL
	SELECT 88,88 FROM DUAL  UNION ALL
	SELECT 89,89 FROM DUAL  UNION ALL
	SELECT 90,90 FROM DUAL  UNION ALL
	SELECT 91,91 FROM DUAL  UNION ALL
	SELECT 92,92 FROM DUAL  UNION ALL
	SELECT 93,93 FROM DUAL  UNION ALL
	SELECT 94,94 FROM DUAL  UNION ALL
	SELECT 95,95 FROM DUAL  UNION ALL
	SELECT 96,96 FROM DUAL  UNION ALL
	SELECT 97,97 FROM DUAL  UNION ALL
	SELECT 98,98 FROM DUAL  UNION ALL
	SELECT 99,99 FROM DUAL 

-- Oracle.12.Managed Oracle.Managed Oracle12

SELECT
	t1."Id",
	t1."Value"
FROM
	"UseAlternativeBulkCopy" t1

-- Oracle.12.Managed Oracle.Managed Oracle12

DROP TABLE "UseAlternativeBulkCopy"

