BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "PriceList"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "PriceList"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Product"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Product"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "AccessTariff"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "AccessTariff"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CountryState"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "CountryState"
(
	"Id"                    Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CountryId"             Integer                                  NOT NULL,
	"AutonomousCommunityId" Integer                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "AutonomousCommunity"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "AutonomousCommunity"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Country"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Country"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "InvoicePendingState"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "InvoicePendingState"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TypeBMeasures"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "TypeBMeasures"
(
	"Id"              Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CustomInvoiceId" Integer                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Town"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Town"
(
	"Id"      Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"StateId" Integer                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "InvoiceLine"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "InvoiceLine"
(
	"Id"            Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ProductUnitId" Integer                                      NULL,
	"InvoiceId"     Integer                                      NULL,
	"ProductId"     Integer                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "AccountTax"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "AccountTax"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "InvoiceTaxLine"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "InvoiceTaxLine"
(
	"Id"        Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"InvoiceId" Integer                                      NULL,
	"TaxId"     Integer                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Invoice"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Invoice"
(
	"Id"                  Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"PendingStateId"      Integer                                      NULL,
	"RectifyingInvoiceId" Integer                                      NULL,
	"RefundByInvoiceId"   Integer                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "MeasureSource"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "MeasureSource"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TypeAMeasures"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "TypeAMeasures"
(
	"Id"               Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CustomInvoiceId"  Integer                                  NOT NULL,
	"MeasuresSourceId" Integer                                  NOT NULL,
	"PreviousSourceId" Integer                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "StreetType"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "StreetType"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "ServicePoint"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "ServicePoint"
(
	"Id"           Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"TownId"       Integer                                  NOT NULL,
	"StreetTypeId" Integer                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "ProductUnit"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "ProductUnit"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Contract"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Contract"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomInvoice"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "CustomInvoice"
(
	"Id"             Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ContractId"     Integer                                  NOT NULL,
	"InvoiceId"      Integer                                  NOT NULL,
	"ServicePointId" Integer                                  NOT NULL,
	"AccessTariffId" Integer                                  NOT NULL,
	"PriceListId"    Integer                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomInvoiceLine"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "CustomInvoiceLine"
(
	"Id"              Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CustomInvoiceId" Integer                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
BeginTransaction(RepeatableRead)
BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"m_1"."Id",
	"d"."Id",
	"d"."ProductUnitId",
	"d"."InvoiceId",
	"d"."ProductId",
	"a_ProductUnit"."Id",
	"a_Product"."Id"
FROM
	(
		SELECT DISTINCT
			"a_Invoice"."Id"
		FROM
			"CustomInvoice" "f"
				INNER JOIN "Invoice" "a_Invoice" ON "f"."InvoiceId" = "a_Invoice"."Id"
				INNER JOIN "Contract" "a_Contract" ON "f"."ContractId" = "a_Contract"."Id"
				INNER JOIN "AccessTariff" "a_AccessTariff" ON "f"."AccessTariffId" = "a_AccessTariff"."Id"
				INNER JOIN "ServicePoint" "a_ServicePoint" ON "f"."ServicePointId" = "a_ServicePoint"."Id"
		WHERE
			"f"."Id" = 1
	) "m_1"
		INNER JOIN "InvoiceLine" "d" ON "m_1"."Id" = "d"."InvoiceId" AND "d"."InvoiceId" IS NOT NULL
		LEFT JOIN "ProductUnit" "a_ProductUnit" ON "d"."ProductUnitId" = "a_ProductUnit"."Id" AND "d"."ProductUnitId" IS NOT NULL
		LEFT JOIN "Product" "a_Product" ON "d"."ProductId" = "a_Product"."Id" AND "d"."ProductId" IS NOT NULL

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"m_1"."Id",
	"d"."Id",
	"d"."InvoiceId",
	"d"."TaxId",
	"a_Tax"."Id"
FROM
	(
		SELECT DISTINCT
			"a_Invoice"."Id"
		FROM
			"CustomInvoice" "f"
				INNER JOIN "Invoice" "a_Invoice" ON "f"."InvoiceId" = "a_Invoice"."Id"
				INNER JOIN "Contract" "a_Contract" ON "f"."ContractId" = "a_Contract"."Id"
				INNER JOIN "AccessTariff" "a_AccessTariff" ON "f"."AccessTariffId" = "a_AccessTariff"."Id"
				INNER JOIN "ServicePoint" "a_ServicePoint" ON "f"."ServicePointId" = "a_ServicePoint"."Id"
		WHERE
			"f"."Id" = 1
	) "m_1"
		INNER JOIN "InvoiceTaxLine" "d" ON "m_1"."Id" = "d"."InvoiceId" AND "d"."InvoiceId" IS NOT NULL
		INNER JOIN "AccountTax" "a_Tax" ON "d"."TaxId" = "a_Tax"."Id" AND "d"."TaxId" IS NOT NULL

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"m_1"."Id",
	"d"."Id",
	"d"."CustomInvoiceId"
FROM
	(
		SELECT DISTINCT
			"f"."Id"
		FROM
			"CustomInvoice" "f"
				INNER JOIN "Invoice" "a_Invoice" ON "f"."InvoiceId" = "a_Invoice"."Id"
				INNER JOIN "Contract" "a_Contract" ON "f"."ContractId" = "a_Contract"."Id"
				INNER JOIN "AccessTariff" "a_AccessTariff" ON "f"."AccessTariffId" = "a_AccessTariff"."Id"
				INNER JOIN "ServicePoint" "a_ServicePoint" ON "f"."ServicePointId" = "a_ServicePoint"."Id"
		WHERE
			"f"."Id" = 1
	) "m_1"
		INNER JOIN "CustomInvoiceLine" "d" ON "m_1"."Id" = "d"."CustomInvoiceId"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"m_1"."Id",
	"d"."Id",
	"d"."CustomInvoiceId",
	"d"."MeasuresSourceId",
	"d"."PreviousSourceId",
	"a_Source"."Id",
	"a_PreviousSource"."Id"
FROM
	(
		SELECT DISTINCT
			"f"."Id"
		FROM
			"CustomInvoice" "f"
				INNER JOIN "Invoice" "a_Invoice" ON "f"."InvoiceId" = "a_Invoice"."Id"
				INNER JOIN "Contract" "a_Contract" ON "f"."ContractId" = "a_Contract"."Id"
				INNER JOIN "AccessTariff" "a_AccessTariff" ON "f"."AccessTariffId" = "a_AccessTariff"."Id"
				INNER JOIN "ServicePoint" "a_ServicePoint" ON "f"."ServicePointId" = "a_ServicePoint"."Id"
		WHERE
			"f"."Id" = 1
	) "m_1"
		INNER JOIN "TypeAMeasures" "d" ON "m_1"."Id" = "d"."CustomInvoiceId"
		LEFT JOIN "MeasureSource" "a_Source" ON "d"."MeasuresSourceId" = "a_Source"."Id"
		LEFT JOIN "MeasureSource" "a_PreviousSource" ON "d"."PreviousSourceId" = "a_PreviousSource"."Id"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"m_1"."Id",
	"d"."Id",
	"d"."CustomInvoiceId"
FROM
	(
		SELECT DISTINCT
			"f"."Id"
		FROM
			"CustomInvoice" "f"
				INNER JOIN "Invoice" "a_Invoice" ON "f"."InvoiceId" = "a_Invoice"."Id"
				INNER JOIN "Contract" "a_Contract" ON "f"."ContractId" = "a_Contract"."Id"
				INNER JOIN "AccessTariff" "a_AccessTariff" ON "f"."AccessTariffId" = "a_AccessTariff"."Id"
				INNER JOIN "ServicePoint" "a_ServicePoint" ON "f"."ServicePointId" = "a_ServicePoint"."Id"
		WHERE
			"f"."Id" = 1
	) "m_1"
		INNER JOIN "TypeBMeasures" "d" ON "m_1"."Id" = "d"."CustomInvoiceId"

BeforeExecute
DisposeTransaction
BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"f"."Id",
	"f"."ContractId",
	"f"."InvoiceId",
	"f"."ServicePointId",
	"f"."AccessTariffId",
	"f"."PriceListId",
	"a_Invoice"."Id",
	"a_Invoice"."PendingStateId",
	"a_Invoice"."RectifyingInvoiceId",
	"a_Invoice"."RefundByInvoiceId",
	"a_Rectifying"."Id",
	"a_Rectifying"."PendingStateId",
	"a_Rectifying"."RectifyingInvoiceId",
	"a_Rectifying"."RefundByInvoiceId",
	"a_RefundBy"."Id",
	"a_RefundBy"."PendingStateId",
	"a_RefundBy"."RectifyingInvoiceId",
	"a_RefundBy"."RefundByInvoiceId",
	"a_PendingState"."Id",
	"a_Invoice"."Id",
	"a_Contract"."Id",
	"a_AccessTariff"."Id",
	"a_ServicePoint"."Id",
	"a_ServicePoint"."TownId",
	"a_ServicePoint"."StreetTypeId",
	"a_Town"."Id",
	"a_Town"."StateId",
	"a_State"."Id",
	"a_State"."CountryId",
	"a_State"."AutonomousCommunityId",
	"a_Community"."Id",
	"a_StreetType"."Id",
	"f"."Id",
	"a_PriceList"."Id"
FROM
	"CustomInvoice" "f"
		INNER JOIN "Invoice" "a_Invoice" ON "f"."InvoiceId" = "a_Invoice"."Id"
		LEFT JOIN "Invoice" "a_Rectifying" ON "a_Invoice"."RectifyingInvoiceId" = "a_Rectifying"."Id" AND "a_Invoice"."RectifyingInvoiceId" IS NOT NULL
		LEFT JOIN "Invoice" "a_RefundBy" ON "a_Invoice"."RefundByInvoiceId" = "a_RefundBy"."Id" AND "a_Invoice"."RefundByInvoiceId" IS NOT NULL
		LEFT JOIN "InvoicePendingState" "a_PendingState" ON "a_Invoice"."PendingStateId" = "a_PendingState"."Id" AND "a_Invoice"."PendingStateId" IS NOT NULL
		INNER JOIN "Contract" "a_Contract" ON "f"."ContractId" = "a_Contract"."Id"
		INNER JOIN "AccessTariff" "a_AccessTariff" ON "f"."AccessTariffId" = "a_AccessTariff"."Id"
		INNER JOIN "ServicePoint" "a_ServicePoint" ON "f"."ServicePointId" = "a_ServicePoint"."Id"
		LEFT JOIN "Town" "a_Town" ON "a_ServicePoint"."TownId" = "a_Town"."Id"
		LEFT JOIN "CountryState" "a_State" ON "a_Town"."StateId" = "a_State"."Id" AND "a_Town"."StateId" IS NOT NULL
		LEFT JOIN "AutonomousCommunity" "a_Community" ON "a_State"."AutonomousCommunityId" = "a_Community"."Id" AND "a_State"."AutonomousCommunityId" IS NOT NULL
		LEFT JOIN "StreetType" "a_StreetType" ON "a_ServicePoint"."StreetTypeId" = "a_StreetType"."Id"
		LEFT JOIN "PriceList" "a_PriceList" ON "f"."PriceListId" = "a_PriceList"."Id"
WHERE
	"f"."Id" = 1

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomInvoiceLine"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomInvoice"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Contract"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "ProductUnit"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "ServicePoint"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "StreetType"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TypeAMeasures"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "MeasureSource"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Invoice"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "InvoiceTaxLine"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "AccountTax"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "InvoiceLine"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Town"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TypeBMeasures"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "InvoicePendingState"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Country"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "AutonomousCommunity"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CountryState"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "AccessTariff"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Product"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "PriceList"

