BeforeExecute
-- DB2 DB2.LUW DB2LUW

CREATE TABLE VEMPLOYEE_SCH_SEC
(
	ACTIVE smallint      NOT NULL,
	ID     Int           NOT NULL,
	NAME   NVarChar(255) NOT NULL,

	CONSTRAINT PK_VEMPLOYEE_SCH_SEC PRIMARY KEY (ID)
)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

CREATE TABLE VEMPLOYEE_SCHDL_PERM
(
	ID        Int      NOT NULL,
	IS_ACTIVE smallint NOT NULL,

	CONSTRAINT PK_VEMPLOYEE_SCHDL_PERM PRIMARY KEY (ID)
)

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"t1".ID
FROM
	(
		SELECT
			CASE
				WHEN EXISTS(
					SELECT
						*
					FROM
						VEMPLOYEE_SCHDL_PERM "y"
					WHERE
						"ess".ID = "y".ID AND "y".IS_ACTIVE = 1
				)
					THEN 1
				ELSE 0
			END as "hasAdditionalPermissions",
			"ess".ID
		FROM
			VEMPLOYEE_SCH_SEC "ess"
	) "t1"
WHERE
	"t1"."hasAdditionalPermissions" = 1 AND "t1"."hasAdditionalPermissions" IS NOT NULL

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE VEMPLOYEE_SCHDL_PERM';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE VEMPLOYEE_SCH_SEC';
END

