BeforeExecute
-- SqlServer.2016 SqlServer.2012

SELECT 
	CASE WHEN EXISTS(
		SELECT 
			*
		FROM
			[AllTypes] [p]
		WHERE
			[p].[ID] = 2 AND ([p].[intDataType] IS NULL AND COALESCE(CASE WHEN [p].[varcharDataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[varcharDataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) IS NOT NULL OR [p].[intDataType] IS NOT NULL AND COALESCE(CASE WHEN [p].[varcharDataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[varcharDataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END) IS NULL OR [p].[intDataType] <> COALESCE(CASE WHEN [p].[varcharDataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END, CASE WHEN [p].[varcharDataType] IS NULL THEN NULL ELSE CAST(N'1' AS INT) END))
	) THEN 1 ELSE 0 END

