BeforeExecute
-- SqlServer.Northwind.MS SqlServer.2019

SELECT
	[join_2].[OrderID],
	[join_2].[EmployeeID],
	[join_2].[OrderDate],
	[join_2].[RequiredDate],
	[join_2].[ShippedDate],
	[join_2].[ShipVia],
	[join_2].[Freight],
	[a_Shipper].[ShipperID],
	[a_Shipper].[CompanyName],
	[a_Shipper].[Phone],
	[a_Employee].[EmployeeID],
	[a_Employee].[LastName],
	[a_Employee].[FirstName],
	[a_Employee].[Title],
	[a_Employee].[TitleOfCourtesy],
	[a_Employee].[BirthDate],
	[a_Employee].[HireDate],
	[a_Employee].[Address],
	[a_Employee].[City],
	[a_Employee].[Region],
	[a_Employee].[PostalCode],
	[a_Employee].[Country],
	[a_Employee].[HomePhone],
	[a_Employee].[Extension],
	[a_Employee].[Photo],
	[a_Employee].[Notes],
	[a_Employee].[ReportsTo],
	[a_Employee].[PhotoPath],
	[a_Customer].[CustomerID],
	[a_Customer].[CompanyName],
	[a_Customer].[ContactName],
	[a_Customer].[ContactTitle],
	[a_Customer].[Address],
	[a_Customer].[City],
	[a_Customer].[Region],
	[a_Customer].[PostalCode],
	[a_Customer].[Country],
	[a_Customer].[Phone],
	[a_Customer].[Fax],
	[join_3].[OrderID],
	[join_3].[ProductID],
	[join_3].[UnitPrice],
	[join_3].[Quantity],
	[join_3].[Discount],
	[query].[EmployeeID],
	[query].[BirthDate],
	[query].[HireDate],
	[query].[ReportsTo],
	[join_1].[EmployeeID],
	[join_1].[LastName],
	[join_1].[FirstName],
	[join_1].[Title],
	[join_1].[TitleOfCourtesy],
	[join_1].[BirthDate],
	[join_1].[HireDate],
	[join_1].[Address],
	[join_1].[City],
	[join_1].[Region],
	[join_1].[PostalCode],
	[join_1].[Country],
	[join_1].[HomePhone],
	[join_1].[Extension],
	[join_1].[Photo],
	[join_1].[Notes],
	[join_1].[ReportsTo],
	[join_1].[PhotoPath],
	[join_4].[EmployeeID],
	[a_Employee_1].[EmployeeID],
	[a_Employee_1].[LastName],
	[a_Employee_1].[FirstName],
	[a_Employee_1].[Title],
	[a_Employee_1].[TitleOfCourtesy],
	[a_Employee_1].[BirthDate],
	[a_Employee_1].[HireDate],
	[a_Employee_1].[Address],
	[a_Employee_1].[City],
	[a_Employee_1].[Region],
	[a_Employee_1].[PostalCode],
	[a_Employee_1].[Country],
	[a_Employee_1].[HomePhone],
	[a_Employee_1].[Extension],
	[a_Employee_1].[Photo],
	[a_Employee_1].[Notes],
	[a_Employee_1].[ReportsTo],
	[a_Employee_1].[PhotoPath],
	[join_5].[TerritoryID],
	[join_5].[RegionID],
	[join_5].[TerritoryDescription],
	[join_6].[RegionID],
	[join_6].[RegionDescription]
FROM
	[Employees] [query]
		LEFT JOIN [Employees] [join_1] ON [query].[ReportsTo] = [join_1].[EmployeeID]
		LEFT JOIN [Orders] [join_2] ON [query].[EmployeeID] = [join_2].[EmployeeID]
		LEFT JOIN [Customers] [a_Customer] ON ([join_2].[CustomerID] = [a_Customer].[CustomerID] OR [join_2].[CustomerID] IS NULL AND [a_Customer].[CustomerID] IS NULL)
		LEFT JOIN [Employees] [a_Employee] ON [join_2].[EmployeeID] = [a_Employee].[EmployeeID]
		LEFT JOIN [Shippers] [a_Shipper] ON [join_2].[ShipVia] = [a_Shipper].[ShipperID]
		LEFT JOIN [Order Details] [join_3] ON [join_2].[OrderID] = [join_3].[OrderID]
		LEFT JOIN [EmployeeTerritories] [join_4] ON [query].[EmployeeID] = [join_4].[EmployeeID]
		LEFT JOIN [Employees] [a_Employee_1] ON [join_4].[EmployeeID] = [a_Employee_1].[EmployeeID]
		LEFT JOIN [Territories] [join_5] ON [join_4].[TerritoryID] = [join_5].[TerritoryID]
		LEFT JOIN [Region] [join_6] ON [join_5].[RegionID] = [join_6].[RegionID]
WHERE
	[query].[EmployeeID] = 5

