BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "CustomerBase"
(
	"Id"           Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ClientType"   NChar(6)                                       NOT NULL,
	"Name"         NVarChar(255)                                      NULL,
	"ContactEmail" NVarChar(255)                                      NULL,
	"Enabled"      TinyInt                                            NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomerBase"

