BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "billing_devtypes"
(
	"devtypeid"  Integer      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"typename"   NVarChar(50)                                  NOT NULL,
	"GlobalType" Integer                                       NOT NULL,

	PRIMARY KEY ("devtypeid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "billing_devices"
(
	"devid"     NVarChar(50) NOT NULL,
	"sernum"    NVarChar(50)     NULL,
	"devtypeid" Integer      NOT NULL,

	PRIMARY KEY ("devid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "billing_DevReadingType"
(
	"Id"             Integer      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"DevTypeId"      Integer                                       NOT NULL,
	"Name"           NVarChar(50)                                  NOT NULL,
	"Responsibility" Integer                                       NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "billing_TempReading"
(
	"id"               Integer      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"DevSerNum"        NVarChar(50)                                  NOT NULL,
	"devid"            NVarChar(50)                                      NULL,
	"tsdevice"         Timestamp                                     NOT NULL,
	"value"            Decimal                                       NOT NULL,
	"Devtypeid"        Integer                                           NULL,
	"DevReadingTypeId" Integer                                           NULL,
	"ReadingTypeName"  NVarChar(50)                                      NULL,
	"DevGlobalType"    Integer                                       NOT NULL,
	"Responsibility"   Integer                                       NOT NULL,

	PRIMARY KEY ("id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

UPDATE
	"billing_TempReading"
SET
	"billing_TempReading"."DevReadingTypeId" = (
		SELECT
			"drt"."Id"
		FROM
			"billing_TempReading" "tr"
				INNER JOIN "billing_DevReadingType" "drt" ON "drt"."Name" = "tr"."ReadingTypeName" AND "drt"."DevTypeId" = "tr"."Devtypeid"
		WHERE
			"billing_TempReading"."id" = "tr"."id"
	),
	"billing_TempReading"."Responsibility" = (
		SELECT
			"drt_1"."Responsibility"
		FROM
			"billing_TempReading" "tr_1"
				INNER JOIN "billing_DevReadingType" "drt_1" ON "drt_1"."Name" = "tr_1"."ReadingTypeName" AND "drt_1"."DevTypeId" = "tr_1"."Devtypeid"
		WHERE
			"billing_TempReading"."id" = "tr_1"."id"
	)
WHERE
	EXISTS(
		SELECT
			*
		FROM
			"billing_TempReading" "tr_2"
				INNER JOIN "billing_DevReadingType" "drt_2" ON "drt_2"."Name" = "tr_2"."ReadingTypeName" AND "drt_2"."DevTypeId" = "tr_2"."Devtypeid"
		WHERE
			"billing_TempReading"."id" = "tr_2"."id"
	)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

UPDATE
	"billing_TempReading"
SET
	"billing_TempReading"."DevReadingTypeId" = (
		SELECT
			"w"."Id"
		FROM
			"billing_DevReadingType" "w"
		WHERE
			"w"."Name" = "billing_TempReading"."ReadingTypeName" AND
			"w"."DevTypeId" = "billing_TempReading"."Devtypeid"
	),
	"billing_TempReading"."Responsibility" = (
		SELECT
			"w_1"."Responsibility"
		FROM
			"billing_DevReadingType" "w_1"
		WHERE
			"w_1"."Name" = "billing_TempReading"."ReadingTypeName" AND
			"w_1"."DevTypeId" = "billing_TempReading"."Devtypeid"
	)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "billing_TempReading"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "billing_DevReadingType"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "billing_devices"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "billing_devtypes"

