BeforeExecute
-- SQLite.Classic SQLite

DROP TABLE IF EXISTS [VEMPLOYEE_SCH_SEC]

BeforeExecute
-- SQLite.Classic SQLite

CREATE TABLE IF NOT EXISTS [VEMPLOYEE_SCH_SEC]
(
	[ACTIVE] Bit           NOT NULL,
	[ID]     INTEGER       NOT NULL,
	[NAME]   NVarChar(255) NOT NULL,

	CONSTRAINT [PK_VEMPLOYEE_SCH_SEC] PRIMARY KEY ([ID])
)

BeforeExecute
-- SQLite.Classic SQLite

DROP TABLE IF EXISTS [VEMPLOYEE_SCHDL_PERM]

BeforeExecute
-- SQLite.Classic SQLite

CREATE TABLE IF NOT EXISTS [VEMPLOYEE_SCHDL_PERM]
(
	[ID]        INTEGER NOT NULL,
	[IS_ACTIVE] Bit     NOT NULL,

	CONSTRAINT [PK_VEMPLOYEE_SCHDL_PERM] PRIMARY KEY ([ID])
)

BeforeExecute
-- SQLite.Classic SQLite

SELECT
	[ess].[ID]
FROM
	[VEMPLOYEE_SCH_SEC] [ess]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[VEMPLOYEE_SCHDL_PERM] [y]
		WHERE
			[y].[IS_ACTIVE] = 1 AND [ess].[ID] = [y].[ID]
	)

BeforeExecute
-- SQLite.Classic SQLite

DROP TABLE IF EXISTS [VEMPLOYEE_SCHDL_PERM]

BeforeExecute
-- SQLite.Classic SQLite

DROP TABLE IF EXISTS [VEMPLOYEE_SCH_SEC]

