-- YDB Ydb
SELECT
	t.Id as Id,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN 5 PRECEDING AND 2 PRECEDING) as c1,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN 1 FOLLOWING AND 3 FOLLOWING) as c2,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN 1 PRECEDING AND 2 FOLLOWING) as c3
FROM
	WindowFunctionTestEntity t

