-- YDB Ydb
SELECT
	FIRST_VALUE(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as c1,
	LAST_VALUE(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as c2
FROM
	WindowFunctionTestEntity t

