-- YDB Ydb

SELECT
	t.Id as Id,
	LAST_VALUE(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as c1
FROM
	WindowFunctionTestEntity t

