-- YDB Ydb

SELECT
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) as c1,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN CURRENT ROW AND CURRENT ROW) as c2,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN 1 PRECEDING AND 2 FOLLOWING) as c3,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) as c4,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN CURRENT ROW AND CURRENT ROW) as c5,
	SUM(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN 1 PRECEDING AND 2 FOLLOWING) as c6
FROM
	WindowFunctionTestEntity t

