-- YDB Ydb
SELECT
	t.Id as Id,
	LAST_VALUE(t.IntValue = 20) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as Boolean_1,
	LAST_VALUE(t.IntValue) OVER (PARTITION BY t.CategoryId ORDER BY t.Id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as Value_1
FROM
	WindowFunctionTestEntity t
ORDER BY
	t.Id

