-- Sybase.Managed Sybase

SELECT
	CAST(CASE WHEN '2010-' IS NULL OR RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) IS NULL OR '-01' IS NULL THEN NULL ELSE '2010-' + RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) + '-01' END AS Date)
FROM
	[LinqDataTypes] [t]
WHERE
	DatePart(year, CAST(CASE WHEN '2010-' IS NULL OR RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) IS NULL OR '-01' IS NULL THEN NULL ELSE '2010-' + RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) + '-01' END AS Date)) = 2010

