-- Sybase.Managed Sybase
DECLARE @year Integer -- Int32
SET     @year = 2010

SELECT
	CAST(CASE WHEN RIGHT(CASE WHEN '0' IS NULL OR CAST(@year AS VarChar(4)) IS NULL THEN NULL ELSE '0' + CAST(@year AS VarChar(4)) END, 4) IS NULL OR '-' IS NULL OR RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) IS NULL OR '-01' IS NULL THEN NULL ELSE RIGHT(CASE WHEN '0' IS NULL OR CAST(@year AS VarChar(4)) IS NULL THEN NULL ELSE '0' + CAST(@year AS VarChar(4)) END, 4) + '-' + RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) + '-01' END AS Date)
FROM
	[LinqDataTypes] [t]
WHERE
	DatePart(year, CAST(CASE WHEN RIGHT(CASE WHEN '0' IS NULL OR CAST(@year AS VarChar(4)) IS NULL THEN NULL ELSE '0' + CAST(@year AS VarChar(4)) END, 4) IS NULL OR '-' IS NULL OR RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) IS NULL OR '-01' IS NULL THEN NULL ELSE RIGHT(CASE WHEN '0' IS NULL OR CAST(@year AS VarChar(4)) IS NULL THEN NULL ELSE '0' + CAST(@year AS VarChar(4)) END, 4) + '-' + RIGHT(CASE WHEN '0' IS NULL OR CAST([t].[ID] AS VarChar(2)) IS NULL THEN NULL ELSE '0' + CAST([t].[ID] AS VarChar(2)) END, 2) + '-01' END AS Date)) = 2010

