BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue4654Customer"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Issue4654Customer"
(
	"Id"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Name" NVarChar(255)                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue4654Order"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Issue4654Order"
(
	"Id"          Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ProductName" NVarChar(255)                                      NULL,
	"Quantity"    Integer                                        NOT NULL,
	"CustomerId"  Integer                                        NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue4654Product"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Issue4654Product"
(
	"Id"    Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Name"  NVarChar(255)                                      NULL,
	"Price" Decimal                                        NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	CAST("c_1"."Id" AS NVarChar(5000)),
	"c_1"."Name"
FROM
	"Issue4654Customer" "c_1"
UNION
SELECT
	CAST("o"."Id" AS NVarChar(5000)),
	"o"."ProductName"
FROM
	"Issue4654Order" "o"
UNION
SELECT
	CAST("p"."Id" AS NVarChar(5000)),
	"p"."Name"
FROM
	"Issue4654Product" "p"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue4654Product"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue4654Order"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Issue4654Customer"

