BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "DropTableTestID"

BeforeExecute
-- SapHana.Native SapHana

CREATE COLUMN TABLE "DropTableTestID"
(
	"ID"  Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ID1" Integer                                  NOT NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "DropTableTestID"
(
	"ID1"
)
VALUES
(
	2
)

BeforeExecute
-- SapHana.Native SapHana

SELECT
	"t"."ID",
	"t"."ID1"
FROM
	"DropTableTestID" "t"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "DropTableTestID"

BeforeExecute
-- SapHana.Native SapHana

SELECT
	"t1"."ID",
	"t1"."ID1"
FROM
	"DropTableTestID" "t1"

