BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomerBase"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "CustomerBase"
(
	"Id"           Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ClientType"   NChar(6)                                       NOT NULL,
	"Name"         NVarChar(255)                                      NULL,
	"ContactEmail" NVarChar(255)                                      NULL,
	"Enabled"      TinyInt                                            NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"cb"."Id",
	"cb"."Name",
	"cb"."ContactEmail",
	Coalesce("cb"."Enabled", 0)
FROM
	"CustomerBase" "cb"
WHERE
	"cb"."ClientType" = 'Client'

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomerBase"

