BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "stLinks"
(
	"inId"          Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"inIdParent"    Integer                                        NOT NULL,
	"inIdChild"     Integer                                        NOT NULL,
	"inIdTypeRel"   Integer                                        NOT NULL,
	"inMaxQuantity" Double                                             NULL,
	"inMinQuantity" Double                                             NULL,
	"inIdMeasure"   Integer                                            NULL,
	"inIdUnit"      Integer                                            NULL,
	"State"         Integer                                            NULL,
	"dtModified"    Timestamp                                      NOT NULL,
	"inIdOrgOwner"  Integer                                            NULL,
	"dtSynchDate"   Timestamp                                          NULL,
	"stGUID"        NVarChar(255)                                  NOT NULL,

	PRIMARY KEY ("inId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "stVersions"
(
	"inId"     Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"inIdMain" Integer                                  NOT NULL,

	PRIMARY KEY ("inId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "stVersions"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "stLinks"

