-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DropTableTestID"

-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "DropTableTestID"
(
	"ID"  Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ID1" Integer                                  NOT NULL,

	PRIMARY KEY ("ID")
)

-- SapHana.Odbc SapHanaOdbc

INSERT INTO "DropTableTestID"
(
	"ID1"
)
VALUES
(
	2
)

-- SapHana.Odbc SapHanaOdbc

SELECT
	"t"."ID",
	"t"."ID1"
FROM
	"DropTableTestID" "t"

-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DropTableTestID"

-- SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."ID",
	"t1"."ID1"
FROM
	"DropTableTestID" "t1"

