-- PostgreSQL.18 PostgreSQL12
SELECT
	abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghi."FirstName",
	abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghi."PersonID",
	abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghi."LastName",
	abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghi."MiddleName",
	abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghi."Gender"
FROM
	"Person" abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghi
WHERE
	abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghi."PersonID" = 1

