BeforeExecute
-- DB2 DB2.LUW DB2LUW

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t1".SMALLINTDATATYPE
FROM
	(
		SELECT DISTINCT
			"c_1".SMALLINTDATATYPE
		FROM
			ALLTYPES "_"
				INNER JOIN ALLTYPES "c_1" ON "_".SMALLINTDATATYPE = "c_1".INTDATATYPE
		WHERE
			"_".SMALLINTDATATYPE IS NULL
	) "t1"

BeforeExecute
-- DB2 DB2.LUW DB2LUW
DECLARE @p_1 Integer(4) -- Int32
SET     @p_1 = 1234

INSERT INTO ALLTYPES
(
	SMALLINTDATATYPE,
	INTDATATYPE
)
SELECT
	123,
	"t1".SMALLINTDATATYPE
FROM
	(
		SELECT DISTINCT
			"c_1".SMALLINTDATATYPE
		FROM
			ALLTYPES "_"
				INNER JOIN ALLTYPES "c_1" ON "_".SMALLINTDATATYPE = "c_1".INTDATATYPE
		WHERE
			"_".SMALLINTDATATYPE = @p_1
	) "t1"

