-- DuckDB
SELECT
	CAST('p_' AS VARCHAR),
	e.Id,
	CAST('N' AS VARCHAR),
	CAST(NULL AS UUID),
	CAST(NULL AS VARCHAR),
	e.Name,
	CAST(NULL AS VARCHAR),
	CAST(NULL AS VARCHAR),
	CAST(NULL AS UUID),
	CAST(NULL AS VARCHAR)
FROM
	ConcatSetOpEntity e
WHERE
	e.ParentId IS NULL
UNION ALL
SELECT
	CAST(NULL AS VARCHAR),
	CAST(NULL AS UUID),
	CAST(NULL AS VARCHAR),
	e_1.Id,
	CAST('N' AS VARCHAR),
	e_1.Name,
	CAST(NULL AS VARCHAR),
	CAST('p_' AS VARCHAR),
	e_1.ParentId,
	CAST('N' AS VARCHAR)
FROM
	ConcatSetOpEntity e_1
WHERE
	e_1.ParentId IS NOT NULL

-- DuckDB
SELECT
	t1.Id,
	t1.ParentId,
	t1.Name
FROM
	ConcatSetOpEntity t1

