BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Books"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Books"
		(
			"Id"       Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"Title"    NVarChar(255)                              NOT NULL,
			"AuthorId" Int                                        NOT NULL,

			CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Authors"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "Authors"
		(
			"Id"   Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"Name" NVarChar(255)                              NOT NULL,

			CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

WITH "BooksCte" ("AuthorId", "Title")
AS
(
	SELECT
		"t1"."AuthorId",
		"t1"."Title"
	FROM
		"Books" "t1"
)
SELECT
	"b"."Title"
FROM
	"BooksCte" "b"
		INNER JOIN "Authors" "a_Author" ON "b"."AuthorId" = "a_Author"."Id"
WHERE
	"a_Author"."Name" = 'Steven'

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Authors"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "Books"';
END

