BeforeExecute
-- SapHana.Native SapHana

CREATE COLUMN TABLE "Issue1279Table"
(
	"Id"      Integer  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CharFld" NChar(1)                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @CharFld NChar -- StringFixedLength
SET     @CharFld = 'P'

INSERT INTO "Issue1279Table"
(
	"CharFld"
)
VALUES
(
	:"CharFld"
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @take  -- Int32
SET     @take = 1

SELECT
	"t1"."Id",
	"t1"."CharFld"
FROM
	"Issue1279Table" "t1"
LIMIT :"take"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "Issue1279Table"

