-- PostgreSQL.15 PostgreSQL

SELECT
	SUM(t."IntValue") FILTER (WHERE t."CategoryId" = 1) OVER (PARTITION BY t."CategoryId" ORDER BY t."Id"),
	SUM(t."IntValue") FILTER (WHERE t."IntValue" > 20) OVER (ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
	SUM(t."IntValue") FILTER (WHERE t."IntValue" > 10) OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING),
	AVG(t."DoubleValue") FILTER (WHERE t."DoubleValue" > 15) OVER (ORDER BY t."Id" RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
	MIN(t."IntValue") FILTER (WHERE t."IntValue" > 10) OVER (PARTITION BY t."CategoryId" ORDER BY t."Id"),
	MAX(t."IntValue") FILTER (WHERE t."IntValue" < 80) OVER (ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
	COUNT(*) FILTER (WHERE t."IntValue" > 20) OVER (PARTITION BY t."CategoryId" ORDER BY t."Id")
FROM
	"WindowFunctionTestEntity" t

