BeforeExecute
-- PostgreSQL.15 PostgreSQL

SELECT
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN CURRENT ROW AND CURRENT ROW),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN 1 PRECEDING AND 2 FOLLOWING),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN CURRENT ROW AND CURRENT ROW),
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN 1 PRECEDING AND 2 FOLLOWING)
FROM
	"WindowFunctionTestEntity" t

