-- SQLite.MS SQLite

SELECT
	[t3].[Id],
	[t3].[Status],
	[t3].[ResourceLabel],
	[t3].[ResourceLabelNVE],
	[t3].[ParentResourceID],
	[t3].[TypeID],
	[t3].[HeightClass],
	[t3].[CurrentWeightOfResource],
	[t3].[WidthClass],
	[t3].[LengthClass],
	[t3].[OriginalResourceID],
	[t3].[LastGlobalTaskID],
	[t3].[WashingDate],
	[t3].[ResourcePointID],
	[t3].[Height],
	[t3].[Width],
	[t3].[Length_1],
	[t3].[TechnicalValues],
	[t3].[RearrangementCount],
	[t3].[IsVirtual],
	[t3].[ErrorMessage],
	[t3].[FillingDegree],
	[t3].[LastInventoryCheckTimeStamp],
	[t3].[Segmentation],
	[t3].[DontTouch],
	[tp].[Id],
	[tp].[Name],
	[tp].[ShortName],
	[tp].[Height],
	[tp].[Depth],
	[tp].[Width]
FROM
	(
		SELECT
			[t1].[Id],
			[t1].[Status],
			[t1].[ResourceLabel],
			[t1].[ResourceLabelNVE],
			[t1].[ParentResourceID],
			[t1].[TypeID],
			[t1].[HeightClass],
			[t1].[CurrentWeightOfResource],
			[t1].[WidthClass],
			[t1].[LengthClass],
			[t1].[OriginalResourceID],
			[t1].[LastGlobalTaskID],
			[t1].[WashingDate],
			[t1].[ResourcePointID],
			[t1].[Height],
			[t1].[Width],
			[t1].[Length] as [Length_1],
			[t1].[TechnicalValues],
			[t1].[RearrangementCount],
			[t1].[IsVirtual],
			[t1].[ErrorMessage],
			[t1].[FillingDegree],
			[t1].[LastInventoryCheckTimeStamp],
			[t1].[Segmentation],
			[t1].[DontTouch]
		FROM
			[WmsLoadCarrierDTO] [t1]
		UNION
		SELECT
			[t2].[Id],
			[t2].[Status],
			[t2].[ResourceLabel],
			[t2].[ResourceLabelNVE],
			[t2].[ParentResourceID],
			[t2].[TypeID],
			[t2].[HeightClass],
			[t2].[CurrentWeightOfResource],
			[t2].[WidthClass],
			[t2].[LengthClass],
			[t2].[OriginalResourceID],
			[t2].[LastGlobalTaskID],
			[t2].[WashingDate],
			[t2].[ResourcePointID],
			[t2].[Height],
			[t2].[Width],
			[t2].[Length] as [Length_1],
			[t2].[TechnicalValues],
			[t2].[RearrangementCount],
			[t2].[IsVirtual],
			[t2].[ErrorMessage],
			[t2].[FillingDegree],
			[t2].[LastInventoryCheckTimeStamp],
			[t2].[Segmentation],
			[t2].[DontTouch]
		FROM
			[WMS_ResourceA] [t2]
	) [t3]
		LEFT JOIN [WmsResourceTypeDTO] [tp] ON [t3].[TypeID] = [tp].[Id]

