-- DB2 DB2.LUW DB2LUW
DECLARE @i Integer(4) -- Int32
SET     @i = 1

TEST_PROCEDURE

-- DB2 DB2.LUW DB2LUW
DECLARE @i Integer(4) -- Int32
SET     @i = 1

TEST_MODULE1.TEST_PROCEDURE

-- DB2 DB2.LUW DB2LUW
DECLARE @i Integer(4) -- Int32
SET     @i = 1

TEST_MODULE2.TEST_PROCEDURE

-- DB2 DB2.LUW DB2LUW

SELECT
	TEST_FUNCTION(1)
FROM
	"Person" "p"
FETCH NEXT 1 ROWS ONLY

-- DB2 DB2.LUW DB2LUW

SELECT
	TEST_MODULE1.TEST_FUNCTION(1)
FROM
	"Person" "p"
FETCH NEXT 1 ROWS ONLY

-- DB2 DB2.LUW DB2LUW

SELECT
	TEST_MODULE2.TEST_FUNCTION(1)
FROM
	"Person" "p"
FETCH NEXT 1 ROWS ONLY

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 1

SELECT
	"r".O
FROM
	TABLE(TEST_TABLE_FUNCTION(@p)) "r"
FETCH NEXT 1 ROWS ONLY

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 1

SELECT
	"r".O
FROM
	TABLE(TEST_MODULE1.TEST_TABLE_FUNCTION(@p)) "r"
FETCH NEXT 1 ROWS ONLY

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 1

SELECT
	"r".O
FROM
	TABLE(TEST_MODULE2.TEST_TABLE_FUNCTION(@p)) "r"
FETCH NEXT 1 ROWS ONLY

