-- DB2 DB2.LUW DB2LUW
SELECT (CAST(1 AS DECFLOAT)/CAST(0 AS DECFLOAT))  FROM SYSIBM.SYSDUMMY1

-- DB2 DB2.LUW DB2LUW
SELECT (CAST(1 AS DECFLOAT)/CAST(0 AS DECFLOAT))  FROM SYSIBM.SYSDUMMY1

-- DB2 DB2.LUW DB2LUW
SELECT (CAST(1 AS DECFLOAT)/CAST(0 AS DECFLOAT))  FROM SYSIBM.SYSDUMMY1

-- DB2 DB2.LUW DB2LUW
SELECT (CAST(1 AS DECFLOAT)/CAST(0 AS DECFLOAT))  FROM SYSIBM.SYSDUMMY1

-- DB2 DB2.LUW DB2LUW
SELECT (CAST(1 AS DECFLOAT)/CAST(0 AS DECFLOAT))  FROM SYSIBM.SYSDUMMY1

-- DB2 DB2.LUW DB2LUW
SELECT (CAST(1 AS DECFLOAT)/CAST(0 AS DECFLOAT))  FROM SYSIBM.SYSDUMMY1

