-- DB2 DB2.LUW DB2LUW

SELECT bigintDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt -- Int64
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND bigintDataType IS NULL OR @p IS NOT NULL AND bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt -- Int64
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND bigintDataType IS NULL OR @p IS NOT NULL AND bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND bigintDataType IS NULL OR @p IS NOT NULL AND bigintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT bigintDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt(8) -- Int64
SET     @p = 1000000

SELECT ID FROM ALLTYPES WHERE bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt(8) -- Int64
SET     @p = 1000000

SELECT ID FROM ALLTYPES WHERE bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt(8) -- Int64
SET     @p = 1000000

SELECT ID FROM ALLTYPES WHERE bigintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT bigintDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt -- Int64
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND bigintDataType IS NULL OR @p IS NOT NULL AND bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt -- Int64
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND bigintDataType IS NULL OR @p IS NOT NULL AND bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND bigintDataType IS NULL OR @p IS NOT NULL AND bigintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT bigintDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt(8) -- Int64
SET     @p = 1000000

SELECT ID FROM ALLTYPES WHERE bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt(8) -- Int64
SET     @p = 1000000

SELECT ID FROM ALLTYPES WHERE bigintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p BigInt(8) -- Int64
SET     @p = 1000000

SELECT ID FROM ALLTYPES WHERE bigintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT intDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer -- Int32
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND intDataType IS NULL OR @p IS NOT NULL AND intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer -- Int32
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND intDataType IS NULL OR @p IS NOT NULL AND intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND intDataType IS NULL OR @p IS NOT NULL AND intDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT intDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 7777777

SELECT ID FROM ALLTYPES WHERE intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 7777777

SELECT ID FROM ALLTYPES WHERE intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 7777777

SELECT ID FROM ALLTYPES WHERE intDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT intDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer -- Int32
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND intDataType IS NULL OR @p IS NOT NULL AND intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer -- Int32
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND intDataType IS NULL OR @p IS NOT NULL AND intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND intDataType IS NULL OR @p IS NOT NULL AND intDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT intDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 7777777

SELECT ID FROM ALLTYPES WHERE intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 7777777

SELECT ID FROM ALLTYPES WHERE intDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Integer(4) -- Int32
SET     @p = 7777777

SELECT ID FROM ALLTYPES WHERE intDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT smallintDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt -- Int16
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND smallintDataType IS NULL OR @p IS NOT NULL AND smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt -- Int16
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND smallintDataType IS NULL OR @p IS NOT NULL AND smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND smallintDataType IS NULL OR @p IS NOT NULL AND smallintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT smallintDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt(2) -- Int16
SET     @p = 100

SELECT ID FROM ALLTYPES WHERE smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt(2) -- Int16
SET     @p = 100

SELECT ID FROM ALLTYPES WHERE smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt(2) -- Int16
SET     @p = 100

SELECT ID FROM ALLTYPES WHERE smallintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT smallintDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt -- Int16
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND smallintDataType IS NULL OR @p IS NOT NULL AND smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt -- Int16
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND smallintDataType IS NULL OR @p IS NOT NULL AND smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND smallintDataType IS NULL OR @p IS NOT NULL AND smallintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT smallintDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt(2) -- Int16
SET     @p = 100

SELECT ID FROM ALLTYPES WHERE smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt(2) -- Int16
SET     @p = 100

SELECT ID FROM ALLTYPES WHERE smallintDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p SmallInt(2) -- Int16
SET     @p = 100

SELECT ID FROM ALLTYPES WHERE smallintDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT decimalDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decimalDataType IS NULL OR @p IS NOT NULL AND decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(18, 10)
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decimalDataType IS NULL OR @p IS NOT NULL AND decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decimalDataType IS NULL OR @p IS NOT NULL AND decimalDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT decimalDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p (7, 0) -- Decimal
SET     @p = 9999999

SELECT ID FROM ALLTYPES WHERE decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p (7, 0) -- Decimal
SET     @p = 9999999

SELECT ID FROM ALLTYPES WHERE decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p (7, 0) -- Decimal
SET     @p = 9999999

SELECT ID FROM ALLTYPES WHERE decimalDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT decfloatDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decfloatDataType IS NULL OR @p IS NOT NULL AND decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(18, 10)
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decfloatDataType IS NULL OR @p IS NOT NULL AND decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decfloatDataType IS NULL OR @p IS NOT NULL AND decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT decfloatDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p (7, 0) -- Decimal
SET     @p = 8888888

SELECT ID FROM ALLTYPES WHERE decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p (7, 0) -- Decimal
SET     @p = 8888888

SELECT ID FROM ALLTYPES WHERE decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p (7, 0) -- Decimal
SET     @p = 8888888

SELECT ID FROM ALLTYPES WHERE decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT realDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real -- Single
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND realDataType IS NULL OR @p IS NOT NULL AND realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real -- Single
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND realDataType IS NULL OR @p IS NOT NULL AND realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND realDataType IS NULL OR @p IS NOT NULL AND realDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT realDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real(4) -- Single
SET     @p = 20.3099995

SELECT ID FROM ALLTYPES WHERE realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real(4) -- Single
SET     @p = 20.3099995

SELECT ID FROM ALLTYPES WHERE realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real(4) -- Single
SET     @p = 20.3099995

SELECT ID FROM ALLTYPES WHERE realDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT realDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real -- Single
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND realDataType IS NULL OR @p IS NOT NULL AND realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real -- Single
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND realDataType IS NULL OR @p IS NOT NULL AND realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND realDataType IS NULL OR @p IS NOT NULL AND realDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT realDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real(4) -- Single
SET     @p = 20.31

SELECT ID FROM ALLTYPES WHERE realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real(4) -- Single
SET     @p = 20.31

SELECT ID FROM ALLTYPES WHERE realDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Real(4) -- Single
SET     @p = 20.31

SELECT ID FROM ALLTYPES WHERE realDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT doubleDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND doubleDataType IS NULL OR @p IS NOT NULL AND doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND doubleDataType IS NULL OR @p IS NOT NULL AND doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND doubleDataType IS NULL OR @p IS NOT NULL AND doubleDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT doubleDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double(8)
SET     @p = 16.199999999999999

SELECT ID FROM ALLTYPES WHERE doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double(8)
SET     @p = 16.199999999999999

SELECT ID FROM ALLTYPES WHERE doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double(8)
SET     @p = 16.199999999999999

SELECT ID FROM ALLTYPES WHERE doubleDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT doubleDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND doubleDataType IS NULL OR @p IS NOT NULL AND doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND doubleDataType IS NULL OR @p IS NOT NULL AND doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND doubleDataType IS NULL OR @p IS NOT NULL AND doubleDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT doubleDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double(8)
SET     @p = 16.2

SELECT ID FROM ALLTYPES WHERE doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double(8)
SET     @p = 16.2

SELECT ID FROM ALLTYPES WHERE doubleDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Double(8)
SET     @p = 16.2

SELECT ID FROM ALLTYPES WHERE doubleDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT charDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Char -- StringFixedLength
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT charDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Char(1) -- StringFixedLength
SET     @p = '1'

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = '1'

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(1) -- String
SET     @p = '1'

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT charDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Char -- StringFixedLength
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT charDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Char(1) -- StringFixedLength
SET     @p = '1'

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = '1'

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(1) -- String
SET     @p = '1'

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT charDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Char -- StringFixedLength
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND charDataType IS NULL OR @p IS NOT NULL AND charDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT charDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Char(1) -- StringFixedLength
SET     @p = 1

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(1) -- String
SET     @p = 1

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(1) -- String
SET     @p = 1

SELECT ID FROM ALLTYPES WHERE charDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varcharDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varcharDataType IS NULL OR @p IS NOT NULL AND varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varcharDataType IS NULL OR @p IS NOT NULL AND varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varcharDataType IS NULL OR @p IS NOT NULL AND varcharDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varcharDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(3) -- String
SET     @p = '234'

SELECT ID FROM ALLTYPES WHERE varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = '234'

SELECT ID FROM ALLTYPES WHERE varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(3) -- String
SET     @p = '234'

SELECT ID FROM ALLTYPES WHERE varcharDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varcharDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varcharDataType IS NULL OR @p IS NOT NULL AND varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varcharDataType IS NULL OR @p IS NOT NULL AND varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varcharDataType IS NULL OR @p IS NOT NULL AND varcharDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varcharDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(3) -- String
SET     @p = '234'

SELECT ID FROM ALLTYPES WHERE varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = '234'

SELECT ID FROM ALLTYPES WHERE varcharDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(3) -- String
SET     @p = '234'

SELECT ID FROM ALLTYPES WHERE varcharDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT clobDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND clobDataType IS NULL OR @p IS NOT NULL AND clobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND clobDataType IS NULL OR @p IS NOT NULL AND clobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND clobDataType IS NULL OR @p IS NOT NULL AND clobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT clobDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(5) -- String
SET     @p = '55645'

SELECT ID FROM ALLTYPES WHERE clobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = '55645'

SELECT ID FROM ALLTYPES WHERE clobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(5) -- String
SET     @p = '55645'

SELECT ID FROM ALLTYPES WHERE clobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT dbclobDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dbclobDataType IS NULL OR @p IS NOT NULL AND dbclobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dbclobDataType IS NULL OR @p IS NOT NULL AND dbclobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dbclobDataType IS NULL OR @p IS NOT NULL AND dbclobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT dbclobDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(4) -- String
SET     @p = '6687'

SELECT ID FROM ALLTYPES WHERE dbclobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = '6687'

SELECT ID FROM ALLTYPES WHERE dbclobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(4) -- String
SET     @p = '6687'

SELECT ID FROM ALLTYPES WHERE dbclobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT binaryDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND binaryDataType IS NULL OR @p IS NOT NULL AND binaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND binaryDataType IS NULL OR @p IS NOT NULL AND binaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND binaryDataType IS NULL OR @p IS NOT NULL AND binaryDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT binaryDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(5) -- Binary
SET     @p = BX'3132332020'

SELECT ID FROM ALLTYPES WHERE binaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(5) -- Binary
SET     @p = BX'3132332020'

SELECT ID FROM ALLTYPES WHERE binaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(5) -- Binary
SET     @p = BX'3132332020'

SELECT ID FROM ALLTYPES WHERE binaryDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varbinaryDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varbinaryDataType IS NULL OR @p IS NOT NULL AND varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varbinaryDataType IS NULL OR @p IS NOT NULL AND varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varbinaryDataType IS NULL OR @p IS NOT NULL AND varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varbinaryDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(4) -- Binary
SET     @p = BX'31323334'

SELECT ID FROM ALLTYPES WHERE varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(4) -- Binary
SET     @p = BX'31323334'

SELECT ID FROM ALLTYPES WHERE varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(4) -- Binary
SET     @p = BX'31323334'

SELECT ID FROM ALLTYPES WHERE varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT blobDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Blob -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND blobDataType IS NULL OR @p IS NOT NULL AND blobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT blobDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Blob(3) -- Binary
SET     @p = BX'323334'

SELECT ID FROM ALLTYPES WHERE blobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT blobDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND blobDataType IS NULL OR @p IS NOT NULL AND blobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT blobDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(3) -- Binary
SET     @p = BX'323334'

SELECT ID FROM ALLTYPES WHERE blobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT graphicDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND graphicDataType IS NULL OR @p IS NOT NULL AND graphicDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND graphicDataType IS NULL OR @p IS NOT NULL AND graphicDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND graphicDataType IS NULL OR @p IS NOT NULL AND graphicDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT graphicDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(10) -- String
SET     @p = '23        '

SELECT ID FROM ALLTYPES WHERE graphicDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(255) -- String
SET     @p = '23        '

SELECT ID FROM ALLTYPES WHERE graphicDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar(10) -- String
SET     @p = '23        '

SELECT ID FROM ALLTYPES WHERE graphicDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT dateDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Date
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dateDataType IS NULL OR @p IS NOT NULL AND dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp -- DateTime
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dateDataType IS NULL OR @p IS NOT NULL AND dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dateDataType IS NULL OR @p IS NOT NULL AND dateDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT dateDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Date(20)
SET     @p = '2012-12-12-00.00.00.000000'

SELECT ID FROM ALLTYPES WHERE dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = '2012-12-12-00.00.00.000000'

SELECT ID FROM ALLTYPES WHERE dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = '2012-12-12-00.00.00.000000'

SELECT ID FROM ALLTYPES WHERE dateDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT dateDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Date
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dateDataType IS NULL OR @p IS NOT NULL AND dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Date
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dateDataType IS NULL OR @p IS NOT NULL AND dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND dateDataType IS NULL OR @p IS NOT NULL AND dateDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT dateDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Date(6)
SET     @p = 12/12/2012

SELECT ID FROM ALLTYPES WHERE dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Date(6)
SET     @p = 12/12/2012

SELECT ID FROM ALLTYPES WHERE dateDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Date(6)
SET     @p = 12/12/2012

SELECT ID FROM ALLTYPES WHERE dateDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timeDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timeDataType IS NULL OR @p IS NOT NULL AND timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timeDataType IS NULL OR @p IS NOT NULL AND timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timeDataType IS NULL OR @p IS NOT NULL AND timeDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timeDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time(6)
SET     @p = '12:12:12'

SELECT ID FROM ALLTYPES WHERE timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time(6)
SET     @p = '12:12:12'

SELECT ID FROM ALLTYPES WHERE timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time(6)
SET     @p = '12:12:12'

SELECT ID FROM ALLTYPES WHERE timeDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timeDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timeDataType IS NULL OR @p IS NOT NULL AND timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timeDataType IS NULL OR @p IS NOT NULL AND timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timeDataType IS NULL OR @p IS NOT NULL AND timeDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timeDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time(6)
SET     @p = 12:12:12

SELECT ID FROM ALLTYPES WHERE timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time(6)
SET     @p = 12:12:12

SELECT ID FROM ALLTYPES WHERE timeDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Time(6)
SET     @p = 12:12:12

SELECT ID FROM ALLTYPES WHERE timeDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timestampDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp -- DateTime
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timestampDataType IS NULL OR @p IS NOT NULL AND timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp -- DateTime
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timestampDataType IS NULL OR @p IS NOT NULL AND timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timestampDataType IS NULL OR @p IS NOT NULL AND timestampDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timestampDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = '2012-12-12-12.12.12.012000'

SELECT ID FROM ALLTYPES WHERE timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = '2012-12-12-12.12.12.012000'

SELECT ID FROM ALLTYPES WHERE timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = '2012-12-12-12.12.12.012000'

SELECT ID FROM ALLTYPES WHERE timestampDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timestampDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp -- DateTime
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timestampDataType IS NULL OR @p IS NOT NULL AND timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp -- DateTime
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timestampDataType IS NULL OR @p IS NOT NULL AND timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND timestampDataType IS NULL OR @p IS NOT NULL AND timestampDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT timestampDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = 2012-12-12-12.12.12.012000

SELECT ID FROM ALLTYPES WHERE timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = 2012-12-12-12.12.12.012000

SELECT ID FROM ALLTYPES WHERE timestampDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Timestamp(20) -- DateTime
SET     @p = 2012-12-12-12.12.12.012000

SELECT ID FROM ALLTYPES WHERE timestampDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT xmlDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW

SELECT xmlDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW

SELECT rowid FROM AllTypes WHERE ID = 2

-- DB2 DB2.LUW DB2LUW

SELECT clobDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = Null

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND clobDataType IS NULL OR @p IS NOT NULL AND clobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = Null

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND clobDataType IS NULL OR @p IS NOT NULL AND clobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = Null

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND clobDataType IS NULL OR @p IS NOT NULL AND clobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT clobDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW

SELECT blobDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = Null

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND blobDataType IS NULL OR @p IS NOT NULL AND blobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Blob -- Binary
SET     @p = Null

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND blobDataType IS NULL OR @p IS NOT NULL AND blobDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Blob -- Binary
SET     @p = Null

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND blobDataType IS NULL OR @p IS NOT NULL AND blobDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT blobDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW

SELECT xmlDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW

SELECT xmlDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW

SELECT decimalDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decimalDataType IS NULL OR @p IS NOT NULL AND decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decimalDataType IS NULL OR @p IS NOT NULL AND decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decimalDataType IS NULL OR @p IS NOT NULL AND decimalDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT decimalDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(15)
SET     @p = 9999999

SELECT ID FROM ALLTYPES WHERE decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(15)
SET     @p = 9999999

SELECT ID FROM ALLTYPES WHERE decimalDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(15)
SET     @p = 9999999

SELECT ID FROM ALLTYPES WHERE decimalDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varbinaryDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varbinaryDataType IS NULL OR @p IS NOT NULL AND varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varbinaryDataType IS NULL OR @p IS NOT NULL AND varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary -- Binary
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND varbinaryDataType IS NULL OR @p IS NOT NULL AND varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT varbinaryDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(4) -- Binary
SET     @p = 31323334

SELECT ID FROM ALLTYPES WHERE varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(4) -- Binary
SET     @p = 31323334

SELECT ID FROM ALLTYPES WHERE varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarBinary(4) -- Binary
SET     @p = 31323334

SELECT ID FROM ALLTYPES WHERE varbinaryDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT decfloatDataType FROM ALLTYPES WHERE ID = 1

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decfloatDataType IS NULL OR @p IS NOT NULL AND decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decfloatDataType IS NULL OR @p IS NOT NULL AND decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p VarChar -- String
SET     @p = NULL

SELECT ID FROM ALLTYPES WHERE @p IS NULL AND decfloatDataType IS NULL OR @p IS NOT NULL AND decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW

SELECT decfloatDataType FROM ALLTYPES WHERE ID = 2

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(16)
SET     @p = 8888888

SELECT ID FROM ALLTYPES WHERE decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(16)
SET     @p = 8888888

SELECT ID FROM ALLTYPES WHERE decfloatDataType = @p

-- DB2 DB2.LUW DB2LUW
DECLARE @p Decimal(16)
SET     @p = 8888888

SELECT ID FROM ALLTYPES WHERE decfloatDataType = @p

