BeforeExecute
-- SapHana.Native SapHana

RENAME TABLE "AllTypes" TO "AllTypes_OLD"

BeforeExecute
-- SapHana.Native SapHana


CREATE COLUMN TABLE "AllTypes"
(
	ID INTEGER CS_INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"bigintDataType" BIGINT NULL,
	"smallintDataType" SMALLINT NULL,
	"decimalDataType" DECIMAL NULL,
	"smalldecimalDataType" SMALLDECIMAL NULL,
	"intDataType" INTEGER NULL,
	"tinyintDataType" TINYINT NULL,
	"floatDataType" FLOAT NULL,
	"realDataType" REAL NULL,

	"dateDataType" DATE NULL,
	"timeDataType" TIME NULL,
	"seconddateDataType" SECONDDATE NULL,
	"timestampDataType" TIMESTAMP NULL,

	"charDataType" CHAR(1) NULL,
	"char20DataType" CHAR(20) NULL,
	"varcharDataType" VARCHAR(20) NULL,
	"textDataType" TEXT NULL,
	"shorttextDataType" SHORTTEXT(20) NULL,
	"ncharDataType" NCHAR(1) NULL,
	"nchar20DataType" NCHAR(20) NULL,
	"nvarcharDataType" NVARCHAR(20) NULL,
	"alphanumDataType" ALPHANUM(20) NULL,

	"binaryDataType" BINARY(10) NULL,
	"varbinaryDataType" VARBINARY(10) NULL,

	"blobDataType" BLOB NULL,
	"clobDataType" CLOB NULL,
	"nclobDataType" NCLOB NULL,
	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Native SapHana

INSERT INTO "AllTypes" SELECT ID, "bigintDataType", "smallintDataType", "decimalDataType", "smalldecimalDataType", "intDataType", "tinyintDataType", "floatDataType", "realDataType", "dateDataType", "timeDataType", "seconddateDataType", "timestampDataType", "charDataType", "char20DataType", "varcharDataType", "textDataType", "shorttextDataType", "ncharDataType", "nchar20DataType", "nvarcharDataType", "alphanumDataType", "binaryDataType", "varbinaryDataType", "blobDataType", "clobDataType", "nclobDataType" FROM "AllTypes_OLD"

BeforeExecute
-- SapHana.Native SapHana

DROP TABLE "AllTypes_OLD"

BeforeExecute
-- SapHana.Native SapHana
DECLARE @Value_1  -- Int32
SET     @Value_1 = 0

INSERT INTO "AllTypes"
(
	"intDataType"
)
VALUES
(
	:"Value_1"
)

BeforeExecute
-- SapHana.Native SapHana

SELECT MAX("ID") FROM "AllTypes"

BeforeExecute
-- SapHana.Native SapHana (asynchronously)
DECLARE @Value_1  -- Int32
SET     @Value_1 = 200

INSERT INTO "AllTypes"
(
	"intDataType"
)
VALUES
(
	:"Value_1"
)

BeforeExecute
-- SapHana.Native SapHana (asynchronously)
DECLARE @Value_1  -- Int32
SET     @Value_1 = 300

INSERT INTO "AllTypes"
(
	"intDataType"
)
VALUES
(
	:"Value_1"
)

BeforeExecute
-- SapHana.Native SapHana
DECLARE @lastId  -- Int32
SET     @lastId = 1003

SELECT
	"_"."ID",
	"_"."intDataType"
FROM
	"AllTypes" "_"
WHERE
	"_"."ID" > :"lastId"
ORDER BY
	"_"."ID"

BeforeExecute
-- SapHana.Native SapHana
DECLARE @lastId  -- Int32
SET     @lastId = 1003

DELETE FROM
	"AllTypes" "t1"
WHERE
	"t1"."ID" >= :"lastId"

