BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DropTableTestID"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "DropTableTestID"
(
	"ID"  Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ID1" Integer                                  NOT NULL,

	PRIMARY KEY ("ID")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

INSERT INTO "DropTableTestID"
(
	"ID1"
)
VALUES
(
	2
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "DropTableTestID"

