BeforeExecute
-- SqlServer.2005 (asynchronously)

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[Parent] [p]
			WHERE
				[p].[ParentID] = 3 AND ([p].[Value1] = COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) OR [p].[Value1] IS NULL AND COALESCE(CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END, CASE WHEN N'' IS NULL THEN NULL ELSE CAST(N'3' AS INT) END) IS NULL)
		)
			THEN 1
		ELSE 0
	END

