-- PostgreSQL.15 PostgreSQL12
SELECT
	CAST(MOD(CAST(TRUNC((EXTRACT(EPOCH FROM x."Time")) / 3600) AS BIGINT), 24) AS INTEGER)
FROM
	"Issue2950Table" x
WHERE
	CAST(MOD(CAST(TRUNC((EXTRACT(EPOCH FROM x."Time")) / 3600) AS BIGINT), 24) AS INTEGER) >= 0

