BeforeExecute
-- SqlServer.2012

SELECT TOP (1)
	'T5=(CHAR: ' + CASE WHEN N'X' IS NULL THEN 'null' ELSE CAST(N'X' AS NVARCHAR) END + ', STRING: ' + N'some string' + ')',
	'T5=(CHAR: ' + CASE WHEN NULL IS NULL THEN 'null' ELSE CAST(NULL AS NVARCHAR) END + ', STRING: ' + N'another string' + ')',
	'T5=(CHAR: ' + CASE WHEN NULL IS NULL THEN 'null' ELSE CAST(NULL AS NVARCHAR) END + ', STRING: ' + NULL + ')',
	'T3=(BYTE: ' + CAST(123 AS NVARCHAR) + ', INT: ' + CASE WHEN 456 IS NULL THEN 'null' ELSE CAST(456 AS NVARCHAR) END + ')',
	'T3=(BYTE: ' + CAST(123 AS NVARCHAR) + ', INT: ' + CASE WHEN NULL IS NULL THEN 'null' ELSE CAST(NULL AS NVARCHAR) END + ')',
	'T4=(BYTE: ' + CAST(123 AS NVARCHAR) + ', INT: ' + CAST(456 AS NVARCHAR) + ')',
	'T2=(BYTE: ' + CASE WHEN NULL IS NULL THEN 'null' ELSE CAST(NULL AS NVARCHAR) END + ')',
	'T2=(BYTE: ' + CASE WHEN 45 IS NULL THEN 'null' ELSE CAST(45 AS NVARCHAR) END + ')',
	'T1=UNSUPPORTED PARAMETERS'
FROM
	[Parent] [t1]

