BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "activity649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "activity649"
(
	"activityid" Integer   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personid"   Integer                                    NOT NULL,
	"added"      Timestamp                                  NOT NULL,

	PRIMARY KEY ("activityid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "person649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "person649"
(
	"personid"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personname" NVarChar(255)                                  NOT NULL,

	PRIMARY KEY ("personid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @added  -- DateTime
SET     @added = '2017-01-01'

SELECT
	"a_Person"."personid",
	"a_Person"."personname",
	MAX("$VB$It"."added")
FROM
	"activity649" "$VB$It"
		INNER JOIN "person649" "a_Person" ON "$VB$It"."personid" = "a_Person"."personid"
WHERE
	"$VB$It"."added" >= ?
GROUP BY
	"a_Person"."personid",
	"a_Person"."personname"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "person649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "activity649"

