BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "activity649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "activity649"
(
	"activityid" Integer   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personid"   Integer                                    NOT NULL,
	"added"      Timestamp                                  NOT NULL,

	PRIMARY KEY ("activityid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "person649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "person649"
(
	"personid"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personname" NVarChar(255)                                  NOT NULL,

	PRIMARY KEY ("personid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"a_Person"."personid",
	"a_Person"."personname",
	MAX("f"."added")
FROM
	"activity649" "f"
		INNER JOIN "person649" "a_Person" ON "f"."personid" = "a_Person"."personid"
WHERE
	"f"."added" >= To_Timestamp('2017-01-01 00:00:00.000')
GROUP BY
	"a_Person"."personid",
	"a_Person"."personname"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "person649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "activity649"

