-- PostgreSQL.16 PostgreSQL.15 PostgreSQL12

SELECT
	t."Id",
	SUM(t."IntValue") OVER (PARTITION BY t."CategoryId" ORDER BY t."Id" GROUPS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE TIES)
FROM
	"WindowFunctionTestEntity" t

