-- PostgreSQL.16 PostgreSQL.15 PostgreSQL

SELECT
	SUM(t."IntValue") OVER (ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE CURRENT ROW),
	SUM(t."IntValue") OVER (ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE GROUP),
	SUM(t."IntValue") OVER (ORDER BY t."Id" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE TIES),
	SUM(t."IntValue") OVER (ORDER BY t."Id" ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING EXCLUDE CURRENT ROW)
FROM
	"WindowFunctionTestEntity" t

