BeforeExecute
--  SapHana.Odbc SapHanaOdbc

ALTER TABLE "Doctor" DROP CONSTRAINT "FK_Doctor_Person"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

ALTER TABLE "Patient" DROP CONSTRAINT "FK_Patient_Person"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

RENAME TABLE "Person" TO "Person_OLD"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc


CREATE COLUMN TABLE "Person" (
	"PersonID" INTEGER CS_INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"FirstName" NVARCHAR(50) NOT NULL ,
	"LastName" NVARCHAR(50) NOT NULL ,
	"MiddleName" NVARCHAR(50) NULL ,
	"Gender" CHAR(1) NOT NULL ,
	 PRIMARY KEY ("PersonID")
)

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

INSERT INTO "Person" SELECT "PersonID", "FirstName", "LastName", "MiddleName", "Gender" FROM "Person_OLD"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

DROP TABLE "Person_OLD"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

ALTER TABLE "Doctor" ADD CONSTRAINT "FK_Doctor_Person" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON UPDATE CASCADE ON DELETE CASCADE

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

ALTER TABLE "Patient" ADD CONSTRAINT "FK_Patient_Person" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON UPDATE CASCADE ON DELETE CASCADE

BeforeExecute
BeginTransaction
BeforeExecute
--  SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."PersonID",
	"t1"."Diagnosis"
FROM
	"Patient" "t1"
ORDER BY
	"t1"."PersonID"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."PersonID",
	"t1"."Taxonomy"
FROM
	"Doctor" "t1"
ORDER BY
	"t1"."PersonID"

BeforeExecute
--  SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."FirstName",
	"t1"."PersonID",
	"t1"."LastName",
	"t1"."MiddleName",
	"t1"."Gender"
FROM
	"Person" "t1"
ORDER BY
	"t1"."PersonID"

BeforeExecute
DisposeTransaction
