BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomerBase"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "CustomerBase"
(
	"Id"           Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ClientType"   NChar(6)                                       NOT NULL,
	"Name"         NVarChar(255)                                      NULL,
	"ContactEmail" NVarChar(255)                                      NULL,
	"Enabled"      TinyInt                                            NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @filter NVarChar(6) -- String
SET     @filter = '%test%'
DECLARE @filter NVarChar(6) -- String
SET     @filter = '%test%'

SELECT
	"q"."Id",
	"q"."Name",
	"q"."ContactEmail",
	"q"."Enabled"
FROM
	"CustomerBase" "q"
WHERE
	"q"."ClientType" = 'Client' AND ("q"."Name" LIKE ? ESCAPE '~' OR "q"."ContactEmail" LIKE ? ESCAPE '~')

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "CustomerBase"

