-- DuckDB

SELECT
	CAST(CAST(EXTRACT(year FROM p.DateTimeValue) AS VARCHAR) || '-01-01 00:00:00' AS TIMESTAMP)
FROM
	LinqDataTypes p
WHERE
	EXTRACT(day FROM CAST(CAST(EXTRACT(year FROM p.DateTimeValue) AS VARCHAR) || '-01-01 00:00:00' AS TIMESTAMP)) > 0

