-- SQLite.MS SQLite

DROP TABLE IF EXISTS [Issue681Table2]

-- SQLite.MS SQLite

CREATE TABLE [main].[Issue681Table2]
(
	[ID]    INTEGER NOT NULL,
	[Value] INTEGER NOT NULL,

	CONSTRAINT [PK_Issue681Table2] PRIMARY KEY ([ID])
)

-- SQLite.MS SQLite

DROP TABLE IF EXISTS [Issue681Table2]

