BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "activity649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "activity649"
(
	"activityid" Integer   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personid"   Integer                                    NOT NULL,
	"added"      Timestamp                                  NOT NULL,

	PRIMARY KEY ("activityid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "person649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "person649"
(
	"personid"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"personname" NVarChar(255)                                  NOT NULL,

	PRIMARY KEY ("personid")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @added  -- DateTime
SET     @added = '2017-01-01'

SELECT
	"$VB$It"."c1",
	"$VB$It"."c2",
	Max("$VB$It"."added")
FROM
	(
		SELECT
			"a_Person"."personid" as "c1",
			"a_Person"."personname" as "c2",
			"p"."added"
		FROM
			"activity649" "p"
				INNER JOIN "person649" "a_Person" ON "p"."personid" = "a_Person"."personid"
		WHERE
			"p"."added" >= ?
	) "$VB$It"
GROUP BY
	"$VB$It"."c1",
	"$VB$It"."c2"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "person649"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "activity649"

