-- SqlServer.2019.MS SqlServer.2019

SELECT
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN CURRENT ROW AND CURRENT ROW),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN CURRENT ROW AND 3 FOLLOWING),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN 2 PRECEDING AND UNBOUNDED FOLLOWING),
	SUM([t].[IntValue]) OVER (ORDER BY [t].[Id] ROWS BETWEEN 2 PRECEDING AND 3 FOLLOWING)
FROM
	[WindowFunctionTestEntity] [t]

