-- SQLite.Classic.MPM SQLite.Classic SQLite

SELECT
	SUM([t].[IntValue]) OVER (PARTITION BY [t].[CategoryId] ORDER BY [t].[Id] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE TIES)
FROM
	[WindowFunctionTestEntity] [t]

