-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "FluentTemp_Merge"';
END

-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "FluentTemp_Merge"
		(
			ID     Int          NOT NULL,
			"Name" NVarChar(20)     NULL,

			CONSTRAINT "PK_FluentTemp_Merge" PRIMARY KEY (ID)
		)
	';
END

-- DB2 DB2.LUW DB2LUW
DECLARE @ID Integer(4) -- Int32
SET     @ID = 1
DECLARE @Name VarChar(4) -- String
SET     @Name = 'John'

INSERT INTO "FluentTemp_Merge"
(
	ID,
	"Name"
)
VALUES
(
	@ID,
	@Name
)

-- DB2 DB2.LUW DB2LUW

MERGE INTO "FluentTemp_Merge" "Target"
USING (VALUES
	(1,'John II')
) "Source"
(
	ID,
	"Name"
)
ON ("Target".ID = "Source".ID)

WHEN MATCHED THEN
UPDATE
SET
	"Name" = "Source"."Name"

WHEN NOT MATCHED THEN
INSERT
(
	ID,
	"Name"
)
VALUES
(
	"Source".ID,
	"Source"."Name"
)

-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "FluentTemp_Merge"';
END

