-- Firebird.5 Firebird4

SELECT
	"r".RDB$RELATION_NAME,
	"r".RDB$RELATION_TYPE,
	"r".RDB$OWNER_NAME,
	"r".RDB$DESCRIPTION
FROM
	RDB$RELATIONS "r"
WHERE
	"r".RDB$SYSTEM_FLAG IS NULL OR CAST("r".RDB$SYSTEM_FLAG AS Int) = 0

-- Firebird.5 Firebird4

SELECT
	"rc".RDB$RELATION_NAME,
	"rc".RDB$CONSTRAINT_NAME,
	"seg".RDB$FIELD_NAME,
	"seg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$INDEX_SEGMENTS "seg" ON "rc".RDB$INDEX_NAME = "seg".RDB$INDEX_NAME
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'

-- Firebird.5 Firebird4

SELECT
	"rf".RDB$RELATION_NAME,
	"rf".RDB$FIELD_NAME,
	"rf".RDB$FIELD_POSITION,
	"rf".RDB$NULL_FLAG,
	"rf".RDB$DESCRIPTION,
	"f".RDB$FIELD_TYPE,
	"f".RDB$FIELD_SUB_TYPE,
	"f".RDB$CHARACTER_LENGTH,
	"f".RDB$FIELD_PRECISION,
	"f".RDB$FIELD_SCALE,
	"f".RDB$COMPUTED_SOURCE
FROM
	RDB$RELATION_FIELDS "rf"
		INNER JOIN RDB$FIELDS "f" ON "rf".RDB$FIELD_SOURCE = "f".RDB$FIELD_NAME

-- Firebird.5 Firebird4

SELECT
	"rc".RDB$CONSTRAINT_NAME,
	"rc".RDB$RELATION_NAME,
	"rcUq".RDB$RELATION_NAME,
	"thisSeg".RDB$FIELD_NAME,
	"otherSeg".RDB$FIELD_NAME,
	"thisSeg".RDB$FIELD_POSITION
FROM
	RDB$RELATION_CONSTRAINTS "rc"
		INNER JOIN RDB$REF_CONSTRAINTS "refc" ON "rc".RDB$CONSTRAINT_NAME = "refc".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$RELATION_CONSTRAINTS "rcUq" ON "refc".RDB$CONST_NAME_UQ = "rcUq".RDB$CONSTRAINT_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "thisSeg" ON "rc".RDB$INDEX_NAME = "thisSeg".RDB$INDEX_NAME
		INNER JOIN RDB$INDEX_SEGMENTS "otherSeg" ON ("rcUq".RDB$INDEX_NAME = "otherSeg".RDB$INDEX_NAME OR "rcUq".RDB$INDEX_NAME IS NULL AND "otherSeg".RDB$INDEX_NAME IS NULL) AND ("thisSeg".RDB$FIELD_POSITION = "otherSeg".RDB$FIELD_POSITION OR "thisSeg".RDB$FIELD_POSITION IS NULL AND "otherSeg".RDB$FIELD_POSITION IS NULL)
WHERE
	"rc".RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'

