-- DB2 DB2.LUW DB2LUW

select current_schema from sysibm.sysdummy1

-- DB2 DB2.LUW DB2LUW


SELECT
	TABSCHEMA,
	TABNAME,
	INDNAME,
	COLNAMES
FROM
	SYSCAT.INDEXES
WHERE
	UNIQUERULE = 'P' AND TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT
	TABSCHEMA,
	TABNAME,
	COLNAME,
	LENGTH,
	SCALE,
	NULLS,
	IDENTITY,
	COLNO,
	TYPENAME,
	REMARKS,
	CODEPAGE
FROM
	SYSCAT.COLUMNS
WHERE
	TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT
	CONSTNAME,
	TABSCHEMA,
	TABNAME,
	FK_COLNAMES,
	REFTABSCHEMA,
	REFTABNAME,
	PK_COLNAMES
FROM
	SYSCAT.REFERENCES
WHERE
	TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT * FROM (
	SELECT
		p.SPECIFICNAME,
		p.PROCSCHEMA,
		p.PROCNAME,
		p.TEXT,
		p.REMARKS,
		'P' AS IS_PROCEDURE,
		o.OBJECTMODULENAME,
		CASE WHEN CURRENT SCHEMA = p.PROCSCHEMA THEN 1 ELSE 0 END,
		p.PARM_COUNT
	FROM
		SYSCAT.PROCEDURES p
		LEFT JOIN SYSCAT.MODULEOBJECTS o ON p.SPECIFICNAME = o.SPECIFICNAME
	WHERE p.PROCSCHEMA = 'DB2INST1' AND p.PROCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM')
	UNION ALL
	SELECT
		f.SPECIFICNAME,
		f.FUNCSCHEMA,
		f.FUNCNAME,
		f.BODY,
		f.REMARKS,
		f.TYPE,
		o.OBJECTMODULENAME,
		CASE WHEN CURRENT SCHEMA = f.FUNCSCHEMA THEN 1 ELSE 0 END,
		f.PARM_COUNT
	FROM
		SYSCAT.FUNCTIONS f
		LEFT JOIN SYSCAT.MODULEOBJECTS o ON f.SPECIFICNAME = o.SPECIFICNAME
		WHERE f.FUNCSCHEMA = 'DB2INST1' AND f.FUNCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM') AND f.FUNCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM'))
ORDER BY OBJECTMODULENAME, PROCSCHEMA, PROCNAME, PARM_COUNT

-- DB2 DB2.LUW DB2LUW


SELECT
	SPECIFICNAME,
	PROCSCHEMA,
	PROCNAME,
	PARMNAME,
	TYPENAME,
	PARM_MODE,
	ORDINAL,
	LENGTH,
	SCALE,
	NULLS
FROM
	SYSCAT.PROCPARMS
WHERE PROCSCHEMA = 'DB2INST1'
UNION ALL
SELECT
	SPECIFICNAME,
	FUNCSCHEMA,
	FUNCNAME,
	PARMNAME,
	TYPENAME,
	CASE WHEN ORDINAL = 0 THEN 'RET' ELSE 'IN' END,
	ORDINAL,
	LENGTH,
	SCALE,
	'Y'
FROM
	SYSCAT.FUNCPARMS
	WHERE ROWTYPE <> 'R' AND FUNCSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW
DECLARE @I Integer(4) -- Int32
SET     @I = 0

DB2INST1.TEST_MODULE1.TEST_PROCEDURE

-- DB2 DB2.LUW DB2LUW

SELECT * FROM TABLE(DB2INST1.TEST_MODULE1.TEST_TABLE_FUNCTION(NULL))

-- DB2 DB2.LUW DB2LUW
DECLARE @I Integer(4) -- Int32
SET     @I = 0

DB2INST1.TEST_MODULE2.TEST_PROCEDURE

-- DB2 DB2.LUW DB2LUW

SELECT * FROM TABLE(DB2INST1.TEST_MODULE2.TEST_TABLE_FUNCTION(NULL))

-- DB2 DB2.LUW DB2LUW

DB2INST1.ADDISSUE792RECORD

-- DB2 DB2.LUW DB2LUW
DECLARE @ID Integer(4) -- Int32
SET     @ID = 0

DB2INST1.PERSON_SELECTBYKEY

-- DB2 DB2.LUW DB2LUW
DECLARE @I Integer(4) -- Int32
SET     @I = 0

DB2INST1.TEST_PROCEDURE

-- DB2 DB2.LUW DB2LUW

SELECT * FROM TABLE(DB2INST1.TEST_TABLE_FUNCTION(NULL))

RollbackTransaction
-- DB2 DB2.LUW DB2LUW

select current_schema from sysibm.sysdummy1

-- DB2 DB2.LUW DB2LUW


SELECT
	TABSCHEMA,
	TABNAME,
	INDNAME,
	COLNAMES
FROM
	SYSCAT.INDEXES
WHERE
	UNIQUERULE = 'P' AND TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT
	TABSCHEMA,
	TABNAME,
	COLNAME,
	LENGTH,
	SCALE,
	NULLS,
	IDENTITY,
	COLNO,
	TYPENAME,
	REMARKS,
	CODEPAGE
FROM
	SYSCAT.COLUMNS
WHERE
	TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT
	CONSTNAME,
	TABSCHEMA,
	TABNAME,
	FK_COLNAMES,
	REFTABSCHEMA,
	REFTABNAME,
	PK_COLNAMES
FROM
	SYSCAT.REFERENCES
WHERE
	TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT * FROM (
	SELECT
		p.SPECIFICNAME,
		p.PROCSCHEMA,
		p.PROCNAME,
		p.TEXT,
		p.REMARKS,
		'P' AS IS_PROCEDURE,
		o.OBJECTMODULENAME,
		CASE WHEN CURRENT SCHEMA = p.PROCSCHEMA THEN 1 ELSE 0 END,
		p.PARM_COUNT
	FROM
		SYSCAT.PROCEDURES p
		LEFT JOIN SYSCAT.MODULEOBJECTS o ON p.SPECIFICNAME = o.SPECIFICNAME
	WHERE p.PROCSCHEMA = 'DB2INST1' AND p.PROCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM')
	UNION ALL
	SELECT
		f.SPECIFICNAME,
		f.FUNCSCHEMA,
		f.FUNCNAME,
		f.BODY,
		f.REMARKS,
		f.TYPE,
		o.OBJECTMODULENAME,
		CASE WHEN CURRENT SCHEMA = f.FUNCSCHEMA THEN 1 ELSE 0 END,
		f.PARM_COUNT
	FROM
		SYSCAT.FUNCTIONS f
		LEFT JOIN SYSCAT.MODULEOBJECTS o ON f.SPECIFICNAME = o.SPECIFICNAME
		WHERE f.FUNCSCHEMA = 'DB2INST1' AND f.FUNCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM') AND f.FUNCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM'))
ORDER BY OBJECTMODULENAME, PROCSCHEMA, PROCNAME, PARM_COUNT

-- DB2 DB2.LUW DB2LUW


SELECT
	SPECIFICNAME,
	PROCSCHEMA,
	PROCNAME,
	PARMNAME,
	TYPENAME,
	PARM_MODE,
	ORDINAL,
	LENGTH,
	SCALE,
	NULLS
FROM
	SYSCAT.PROCPARMS
WHERE PROCSCHEMA = 'DB2INST1'
UNION ALL
SELECT
	SPECIFICNAME,
	FUNCSCHEMA,
	FUNCNAME,
	PARMNAME,
	TYPENAME,
	CASE WHEN ORDINAL = 0 THEN 'RET' ELSE 'IN' END,
	ORDINAL,
	LENGTH,
	SCALE,
	'Y'
FROM
	SYSCAT.FUNCPARMS
	WHERE ROWTYPE <> 'R' AND FUNCSCHEMA = 'DB2INST1'

RollbackTransaction
-- DB2 DB2.LUW DB2LUW

select current_schema from sysibm.sysdummy1

-- DB2 DB2.LUW DB2LUW


SELECT
	TABSCHEMA,
	TABNAME,
	INDNAME,
	COLNAMES
FROM
	SYSCAT.INDEXES
WHERE
	UNIQUERULE = 'P' AND TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT
	TABSCHEMA,
	TABNAME,
	COLNAME,
	LENGTH,
	SCALE,
	NULLS,
	IDENTITY,
	COLNO,
	TYPENAME,
	REMARKS,
	CODEPAGE
FROM
	SYSCAT.COLUMNS
WHERE
	TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT
	CONSTNAME,
	TABSCHEMA,
	TABNAME,
	FK_COLNAMES,
	REFTABSCHEMA,
	REFTABNAME,
	PK_COLNAMES
FROM
	SYSCAT.REFERENCES
WHERE
	TABSCHEMA = 'DB2INST1'

-- DB2 DB2.LUW DB2LUW


SELECT * FROM (
	SELECT
		p.SPECIFICNAME,
		p.PROCSCHEMA,
		p.PROCNAME,
		p.TEXT,
		p.REMARKS,
		'P' AS IS_PROCEDURE,
		o.OBJECTMODULENAME,
		CASE WHEN CURRENT SCHEMA = p.PROCSCHEMA THEN 1 ELSE 0 END,
		p.PARM_COUNT
	FROM
		SYSCAT.PROCEDURES p
		LEFT JOIN SYSCAT.MODULEOBJECTS o ON p.SPECIFICNAME = o.SPECIFICNAME
	WHERE p.PROCSCHEMA = 'DB2INST1' AND p.PROCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM')
	UNION ALL
	SELECT
		f.SPECIFICNAME,
		f.FUNCSCHEMA,
		f.FUNCNAME,
		f.BODY,
		f.REMARKS,
		f.TYPE,
		o.OBJECTMODULENAME,
		CASE WHEN CURRENT SCHEMA = f.FUNCSCHEMA THEN 1 ELSE 0 END,
		f.PARM_COUNT
	FROM
		SYSCAT.FUNCTIONS f
		LEFT JOIN SYSCAT.MODULEOBJECTS o ON f.SPECIFICNAME = o.SPECIFICNAME
		WHERE f.FUNCSCHEMA = 'DB2INST1' AND f.FUNCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM') AND f.FUNCSCHEMA NOT IN ('SYSPROC', 'SYSIBMADM', 'SQLJ', 'SYSIBM'))
ORDER BY OBJECTMODULENAME, PROCSCHEMA, PROCNAME, PARM_COUNT

-- DB2 DB2.LUW DB2LUW


SELECT
	SPECIFICNAME,
	PROCSCHEMA,
	PROCNAME,
	PARMNAME,
	TYPENAME,
	PARM_MODE,
	ORDINAL,
	LENGTH,
	SCALE,
	NULLS
FROM
	SYSCAT.PROCPARMS
WHERE PROCSCHEMA = 'DB2INST1'
UNION ALL
SELECT
	SPECIFICNAME,
	FUNCSCHEMA,
	FUNCNAME,
	PARMNAME,
	TYPENAME,
	CASE WHEN ORDINAL = 0 THEN 'RET' ELSE 'IN' END,
	ORDINAL,
	LENGTH,
	SCALE,
	'Y'
FROM
	SYSCAT.FUNCPARMS
	WHERE ROWTYPE <> 'R' AND FUNCSCHEMA = 'DB2INST1'

RollbackTransaction
