-- PostgreSQL.15 PostgreSQL

SELECT
	t1."ID",
	t1."bigintDataType",
	t1."numericDataType",
	t1."smallintDataType",
	t1."intDataType",
	t1."moneyDataType",
	t1."doubleDataType",
	t1."realDataType",
	t1."timestampDataType",
	t1."timestampTZDataType",
	t1."dateDataType",
	t1."timeDataType",
	t1."timeTZDataType",
	t1."intervalDataType",
	t1."intervalDataType2",
	t1."charDataType",
	t1."char20DataType",
	t1."varcharDataType",
	t1."textDataType",
	t1."binaryDataType",
	t1."uuidDataType",
	t1."bitDataType",
	t1."booleanDataType",
	t1."colorDataType",
	t1."xmlDataType",
	t1."varBitDataType",
	t1."pointDataType",
	t1."lsegDataType",
	t1."boxDataType",
	t1."pathDataType",
	t1."polygonDataType",
	t1."circleDataType",
	t1."lineDataType",
	t1."inetDataType",
	t1."cidrDataType",
	t1."macaddrDataType",
	t1."macaddr8DataType",
	t1."jsonDataType",
	t1."jsonbDataType"
FROM
	"TestTableFunctionSchema"() t1

-- PostgreSQL.15 PostgreSQL

SELECT
	t1."ID",
	t1."bigintDataType",
	t1."numericDataType",
	t1."smallintDataType",
	t1."intDataType",
	t1."moneyDataType",
	t1."doubleDataType",
	t1."realDataType",
	t1."timestampDataType",
	t1."timestampTZDataType",
	t1."dateDataType",
	t1."timeDataType",
	t1."timeTZDataType",
	t1."intervalDataType",
	t1."intervalDataType2",
	t1."charDataType",
	t1."char20DataType",
	t1."varcharDataType",
	t1."textDataType",
	t1."binaryDataType",
	t1."uuidDataType",
	t1."bitDataType",
	t1."booleanDataType",
	t1."colorDataType",
	t1."xmlDataType",
	t1."varBitDataType",
	t1."pointDataType",
	t1."lsegDataType",
	t1."boxDataType",
	t1."pathDataType",
	t1."polygonDataType",
	t1."circleDataType",
	t1."lineDataType",
	t1."inetDataType",
	t1."cidrDataType",
	t1."macaddrDataType",
	t1."macaddr8DataType",
	t1."jsonDataType",
	t1."jsonbDataType"
FROM
	"AllTypes" t1
ORDER BY
	t1."ID"

-- PostgreSQL.15 PostgreSQL

SELECT
	t1."ID",
	t1."bigintDataType",
	t1."numericDataType",
	t1."smallintDataType",
	t1."intDataType",
	t1."moneyDataType",
	t1."doubleDataType",
	t1."realDataType",
	t1."timestampDataType",
	t1."timestampTZDataType",
	t1."dateDataType",
	t1."timeDataType",
	t1."timeTZDataType",
	t1."intervalDataType",
	t1."intervalDataType2",
	t1."charDataType",
	t1."char20DataType",
	t1."varcharDataType",
	t1."textDataType",
	t1."binaryDataType",
	t1."uuidDataType",
	t1."bitDataType",
	t1."booleanDataType",
	t1."colorDataType",
	t1."xmlDataType",
	t1."varBitDataType",
	t1."pointDataType",
	t1."lsegDataType",
	t1."boxDataType",
	t1."pathDataType",
	t1."polygonDataType",
	t1."circleDataType",
	t1."lineDataType",
	t1."inetDataType",
	t1."cidrDataType",
	t1."macaddrDataType",
	t1."macaddr8DataType",
	t1."jsonDataType",
	t1."jsonbDataType"
FROM
	"AllTypes" t1
ORDER BY
	t1."ID"

