BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Stone"
(
	"Id"           Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Name"         NVarChar(255)                                  NOT NULL,
	"Enabled"      TinyInt                                            NULL,
	"ImageFullUrl" NVarChar(255)                                      NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group1'
DECLARE @Enabled  -- Byte
SET     @Enabled = 1
DECLARE @ImageFullUrl NVarChar(3) -- String
SET     @ImageFullUrl = '123'

INSERT INTO "Stone"
(
	"Name",
	"Enabled",
	"ImageFullUrl"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group1'
DECLARE @Enabled  -- Byte
SET     @Enabled = 1
DECLARE @ImageFullUrl NVarChar(3) -- String
SET     @ImageFullUrl = '123'

INSERT INTO "Stone"
(
	"Name",
	"Enabled",
	"ImageFullUrl"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group2'
DECLARE @Enabled  -- Byte
SET     @Enabled = 1
DECLARE @ImageFullUrl NVarChar(3) -- String
SET     @ImageFullUrl = '123'

INSERT INTO "Stone"
(
	"Name",
	"Enabled",
	"ImageFullUrl"
)
VALUES
(
	?,
	?,
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"s"."Name"
FROM
	"Stone" "s"
WHERE
	("s"."Enabled" = 1 AND "s"."Enabled" IS NOT NULL) AND
	"s"."Name" NOT LIKE 'level - %' ESCAPE '~' AND Length("s"."ImageFullUrl") > 0
GROUP BY
	"s"."Name"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group1'

SELECT
	"s"."Id",
	"s"."Name",
	"s"."Enabled",
	"s"."ImageFullUrl"
FROM
	"Stone" "s"
WHERE
	("s"."Enabled" = 1 AND "s"."Enabled" IS NOT NULL) AND
	"s"."Name" NOT LIKE 'level - %' ESCAPE '~' AND
	Length("s"."ImageFullUrl") > 0 AND
	"s"."Name" = ?

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Name NVarChar(6) -- String
SET     @Name = 'group2'

SELECT
	"s"."Id",
	"s"."Name",
	"s"."Enabled",
	"s"."ImageFullUrl"
FROM
	"Stone" "s"
WHERE
	("s"."Enabled" = 1 AND "s"."Enabled" IS NOT NULL) AND
	"s"."Name" NOT LIKE 'level - %' ESCAPE '~' AND
	Length("s"."ImageFullUrl") > 0 AND
	"s"."Name" = ?

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Stone"

