BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TableWithIdentitySrc"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "TableWithIdentitySrc"
(
	"Id"    Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Value" Integer                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TableWithIdentity"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "TableWithIdentity"
(
	"Id"    Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Value" Integer                                  NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc
DECLARE @Value  -- Int32
SET     @Value = 1

INSERT INTO "TableWithIdentitySrc"
(
	"Value"
)
VALUES
(
	?
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

INSERT INTO "TableWithIdentity"
(
	"Id",
	"Value"
)
SELECT
	345,
	"t1"."Value" + 123
FROM
	"TableWithIdentitySrc" "t1"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."Id",
	"t1"."Value"
FROM
	"TableWithIdentity" "t1"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TableWithIdentity"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "TableWithIdentitySrc"

