BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Request"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Request"
(
	"Id" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Metric"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "Metric"
(
	"Id"        Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"RequestId" Integer                                  NOT NULL,
	"Value"     Double                                       NULL,

	PRIMARY KEY ("Id")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"t1"."not_null",
	"t1"."Value_1",
	"t1"."HasValue"
FROM
	"Request" "a"
		LEFT JOIN LATERAL (
			SELECT
				CASE
					WHEN "a_Metrics"."Value" IS NOT NULL THEN 1
					ELSE 0
				END as "Value_1",
				"a_Metrics"."Value" as "HasValue",
				1 as "not_null"
			FROM
				"Metric" "a_Metrics"
			WHERE
				"a"."Id" = "a_Metrics"."RequestId"
			LIMIT 1
		) "t1" ON 1=1

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Metric"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "Request"

