BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"p_100"."ParentID",
	"p_100"."Value1",
	"c_1"."ParentID",
	"c_1"."ChildID"
FROM
	"Child" "c_1"
		INNER JOIN "Parent" "p" ON "c_1"."ParentID" = "p"."ParentID"
		INNER JOIN "Parent" "p_1" ON "p"."ParentID" = "p_1"."ParentID"
		INNER JOIN "Parent" "p_2" ON "p_1"."ParentID" = "p_2"."ParentID"
		INNER JOIN "Parent" "p_3" ON "p_2"."ParentID" = "p_3"."ParentID"
		INNER JOIN "Parent" "p_4" ON "p_3"."ParentID" = "p_4"."ParentID"
		INNER JOIN "Parent" "p_5" ON "p_4"."ParentID" = "p_5"."ParentID"
		INNER JOIN "Parent" "p_6" ON "p_5"."ParentID" = "p_6"."ParentID"
		INNER JOIN "Parent" "p_7" ON "p_6"."ParentID" = "p_7"."ParentID"
		INNER JOIN "Parent" "p_8" ON "p_7"."ParentID" = "p_8"."ParentID"
		INNER JOIN "Parent" "p_9" ON "p_8"."ParentID" = "p_9"."ParentID"
		INNER JOIN "Parent" "p_10" ON "p_9"."ParentID" = "p_10"."ParentID"
		INNER JOIN "Parent" "p_11" ON "p_10"."ParentID" = "p_11"."ParentID"
		INNER JOIN "Parent" "p_12" ON "p_11"."ParentID" = "p_12"."ParentID"
		INNER JOIN "Parent" "p_13" ON "p_12"."ParentID" = "p_13"."ParentID"
		INNER JOIN "Parent" "p_14" ON "p_13"."ParentID" = "p_14"."ParentID"
		INNER JOIN "Parent" "p_15" ON "p_14"."ParentID" = "p_15"."ParentID"
		INNER JOIN "Parent" "p_16" ON "p_15"."ParentID" = "p_16"."ParentID"
		INNER JOIN "Parent" "p_17" ON "p_16"."ParentID" = "p_17"."ParentID"
		INNER JOIN "Parent" "p_18" ON "p_17"."ParentID" = "p_18"."ParentID"
		INNER JOIN "Parent" "p_19" ON "p_18"."ParentID" = "p_19"."ParentID"
		INNER JOIN "Parent" "p_20" ON "p_19"."ParentID" = "p_20"."ParentID"
		INNER JOIN "Parent" "p_21" ON "p_20"."ParentID" = "p_21"."ParentID"
		INNER JOIN "Parent" "p_22" ON "p_21"."ParentID" = "p_22"."ParentID"
		INNER JOIN "Parent" "p_23" ON "p_22"."ParentID" = "p_23"."ParentID"
		INNER JOIN "Parent" "p_24" ON "p_23"."ParentID" = "p_24"."ParentID"
		INNER JOIN "Parent" "p_25" ON "p_24"."ParentID" = "p_25"."ParentID"
		INNER JOIN "Parent" "p_26" ON "p_25"."ParentID" = "p_26"."ParentID"
		INNER JOIN "Parent" "p_27" ON "p_26"."ParentID" = "p_27"."ParentID"
		INNER JOIN "Parent" "p_28" ON "p_27"."ParentID" = "p_28"."ParentID"
		INNER JOIN "Parent" "p_29" ON "p_28"."ParentID" = "p_29"."ParentID"
		INNER JOIN "Parent" "p_30" ON "p_29"."ParentID" = "p_30"."ParentID"
		INNER JOIN "Parent" "p_31" ON "p_30"."ParentID" = "p_31"."ParentID"
		INNER JOIN "Parent" "p_32" ON "p_31"."ParentID" = "p_32"."ParentID"
		INNER JOIN "Parent" "p_33" ON "p_32"."ParentID" = "p_33"."ParentID"
		INNER JOIN "Parent" "p_34" ON "p_33"."ParentID" = "p_34"."ParentID"
		INNER JOIN "Parent" "p_35" ON "p_34"."ParentID" = "p_35"."ParentID"
		INNER JOIN "Parent" "p_36" ON "p_35"."ParentID" = "p_36"."ParentID"
		INNER JOIN "Parent" "p_37" ON "p_36"."ParentID" = "p_37"."ParentID"
		INNER JOIN "Parent" "p_38" ON "p_37"."ParentID" = "p_38"."ParentID"
		INNER JOIN "Parent" "p_39" ON "p_38"."ParentID" = "p_39"."ParentID"
		INNER JOIN "Parent" "p_40" ON "p_39"."ParentID" = "p_40"."ParentID"
		INNER JOIN "Parent" "p_41" ON "p_40"."ParentID" = "p_41"."ParentID"
		INNER JOIN "Parent" "p_42" ON "p_41"."ParentID" = "p_42"."ParentID"
		INNER JOIN "Parent" "p_43" ON "p_42"."ParentID" = "p_43"."ParentID"
		INNER JOIN "Parent" "p_44" ON "p_43"."ParentID" = "p_44"."ParentID"
		INNER JOIN "Parent" "p_45" ON "p_44"."ParentID" = "p_45"."ParentID"
		INNER JOIN "Parent" "p_46" ON "p_45"."ParentID" = "p_46"."ParentID"
		INNER JOIN "Parent" "p_47" ON "p_46"."ParentID" = "p_47"."ParentID"
		INNER JOIN "Parent" "p_48" ON "p_47"."ParentID" = "p_48"."ParentID"
		INNER JOIN "Parent" "p_49" ON "p_48"."ParentID" = "p_49"."ParentID"
		INNER JOIN "Parent" "p_50" ON "p_49"."ParentID" = "p_50"."ParentID"
		INNER JOIN "Parent" "p_51" ON "p_50"."ParentID" = "p_51"."ParentID"
		INNER JOIN "Parent" "p_52" ON "p_51"."ParentID" = "p_52"."ParentID"
		INNER JOIN "Parent" "p_53" ON "p_52"."ParentID" = "p_53"."ParentID"
		INNER JOIN "Parent" "p_54" ON "p_53"."ParentID" = "p_54"."ParentID"
		INNER JOIN "Parent" "p_55" ON "p_54"."ParentID" = "p_55"."ParentID"
		INNER JOIN "Parent" "p_56" ON "p_55"."ParentID" = "p_56"."ParentID"
		INNER JOIN "Parent" "p_57" ON "p_56"."ParentID" = "p_57"."ParentID"
		INNER JOIN "Parent" "p_58" ON "p_57"."ParentID" = "p_58"."ParentID"
		INNER JOIN "Parent" "p_59" ON "p_58"."ParentID" = "p_59"."ParentID"
		INNER JOIN "Parent" "p_60" ON "p_59"."ParentID" = "p_60"."ParentID"
		INNER JOIN "Parent" "p_61" ON "p_60"."ParentID" = "p_61"."ParentID"
		INNER JOIN "Parent" "p_62" ON "p_61"."ParentID" = "p_62"."ParentID"
		INNER JOIN "Parent" "p_63" ON "p_62"."ParentID" = "p_63"."ParentID"
		INNER JOIN "Parent" "p_64" ON "p_63"."ParentID" = "p_64"."ParentID"
		INNER JOIN "Parent" "p_65" ON "p_64"."ParentID" = "p_65"."ParentID"
		INNER JOIN "Parent" "p_66" ON "p_65"."ParentID" = "p_66"."ParentID"
		INNER JOIN "Parent" "p_67" ON "p_66"."ParentID" = "p_67"."ParentID"
		INNER JOIN "Parent" "p_68" ON "p_67"."ParentID" = "p_68"."ParentID"
		INNER JOIN "Parent" "p_69" ON "p_68"."ParentID" = "p_69"."ParentID"
		INNER JOIN "Parent" "p_70" ON "p_69"."ParentID" = "p_70"."ParentID"
		INNER JOIN "Parent" "p_71" ON "p_70"."ParentID" = "p_71"."ParentID"
		INNER JOIN "Parent" "p_72" ON "p_71"."ParentID" = "p_72"."ParentID"
		INNER JOIN "Parent" "p_73" ON "p_72"."ParentID" = "p_73"."ParentID"
		INNER JOIN "Parent" "p_74" ON "p_73"."ParentID" = "p_74"."ParentID"
		INNER JOIN "Parent" "p_75" ON "p_74"."ParentID" = "p_75"."ParentID"
		INNER JOIN "Parent" "p_76" ON "p_75"."ParentID" = "p_76"."ParentID"
		INNER JOIN "Parent" "p_77" ON "p_76"."ParentID" = "p_77"."ParentID"
		INNER JOIN "Parent" "p_78" ON "p_77"."ParentID" = "p_78"."ParentID"
		INNER JOIN "Parent" "p_79" ON "p_78"."ParentID" = "p_79"."ParentID"
		INNER JOIN "Parent" "p_80" ON "p_79"."ParentID" = "p_80"."ParentID"
		INNER JOIN "Parent" "p_81" ON "p_80"."ParentID" = "p_81"."ParentID"
		INNER JOIN "Parent" "p_82" ON "p_81"."ParentID" = "p_82"."ParentID"
		INNER JOIN "Parent" "p_83" ON "p_82"."ParentID" = "p_83"."ParentID"
		INNER JOIN "Parent" "p_84" ON "p_83"."ParentID" = "p_84"."ParentID"
		INNER JOIN "Parent" "p_85" ON "p_84"."ParentID" = "p_85"."ParentID"
		INNER JOIN "Parent" "p_86" ON "p_85"."ParentID" = "p_86"."ParentID"
		INNER JOIN "Parent" "p_87" ON "p_86"."ParentID" = "p_87"."ParentID"
		INNER JOIN "Parent" "p_88" ON "p_87"."ParentID" = "p_88"."ParentID"
		INNER JOIN "Parent" "p_89" ON "p_88"."ParentID" = "p_89"."ParentID"
		INNER JOIN "Parent" "p_90" ON "p_89"."ParentID" = "p_90"."ParentID"
		INNER JOIN "Parent" "p_91" ON "p_90"."ParentID" = "p_91"."ParentID"
		INNER JOIN "Parent" "p_92" ON "p_91"."ParentID" = "p_92"."ParentID"
		INNER JOIN "Parent" "p_93" ON "p_92"."ParentID" = "p_93"."ParentID"
		INNER JOIN "Parent" "p_94" ON "p_93"."ParentID" = "p_94"."ParentID"
		INNER JOIN "Parent" "p_95" ON "p_94"."ParentID" = "p_95"."ParentID"
		INNER JOIN "Parent" "p_96" ON "p_95"."ParentID" = "p_96"."ParentID"
		INNER JOIN "Parent" "p_97" ON "p_96"."ParentID" = "p_97"."ParentID"
		INNER JOIN "Parent" "p_98" ON "p_97"."ParentID" = "p_98"."ParentID"
		INNER JOIN "Parent" "p_99" ON "p_98"."ParentID" = "p_99"."ParentID"
		INNER JOIN "Parent" "p_100" ON "p_99"."ParentID" = "p_100"."ParentID"

