BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "UserDTO"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "UserDTO"
(
	"UserId"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"UserName" NVarChar(255)                                      NULL,

	PRIMARY KEY ("UserId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "UserPositionDTO"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "UserPositionDTO"
(
	"UserPositionId" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"UserId"         Integer                                  NOT NULL,
	"PositionId"     Integer                                  NOT NULL,

	PRIMARY KEY ("UserPositionId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "UPS"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "UPS"
(
	"UserPositionSectorId" Integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"UserPositionId"       Integer                                  NOT NULL,
	"SectorId"             Integer                                  NOT NULL,

	PRIMARY KEY ("UserPositionSectorId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "PositionDTO"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "PositionDTO"
(
	"PositionId"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"PositionName" NVarChar(255)                                  NOT NULL,

	PRIMARY KEY ("PositionId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "SectorDTO"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

CREATE COLUMN TABLE "SectorDTO"
(
	"SectorId"   Integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"SectorName" NVarChar(255)                                  NOT NULL,

	PRIMARY KEY ("SectorId")
)

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"m_1"."SectorId",
	"a_User"."UserId"
FROM
	"SectorDTO" "m_1"
		INNER JOIN "UPS" "d" ON "m_1"."SectorId" = "d"."SectorId"
		INNER JOIN "UserPositionDTO" "a_UserPosition" ON "d"."UserPositionId" = "a_UserPosition"."UserPositionId"
		INNER JOIN "UserDTO" "a_User" ON "a_UserPosition"."UserId" = "a_User"."UserId"
WHERE
	"a_UserPosition"."PositionId" = 1

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

SELECT
	"x"."SectorId"
FROM
	"SectorDTO" "x"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "SectorDTO"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "PositionDTO"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "UPS"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "UserPositionDTO"

BeforeExecute
-- SapHana.Odbc SapHanaOdbc

DROP TABLE "UserDTO"

