-- DuckDB
DECLARE $z2  -- Int32
SET     $z2 = 2
DECLARE $y10  -- Int32
SET     $y10 = 10
DECLARE $x3  -- Int32
SET     $x3 = 3

SELECT
	((((CAST($x3 AS INTEGER) * (CAST($y10 AS INTEGER) - CAST($z2 AS INTEGER)) / CAST($x3 AS INTEGER)) * CAST($z2 AS INTEGER)) * (((((CAST($x3 AS INTEGER) * (CAST($y10 AS INTEGER) - CAST($z2 AS INTEGER)) / CAST($x3 AS INTEGER)) * CAST($z2 AS INTEGER)) * (CAST($y10 AS INTEGER) - CAST($z2 AS INTEGER)) / ((CAST($x3 AS INTEGER) * (CAST($y10 AS INTEGER) - CAST($z2 AS INTEGER)) / CAST($x3 AS INTEGER)) * CAST($z2 AS INTEGER))) * CAST($z2 AS INTEGER)) - child_1.ChildID) / ((CAST($x3 AS INTEGER) * (CAST($y10 AS INTEGER) - CAST($z2 AS INTEGER)) / CAST($x3 AS INTEGER)) * CAST($z2 AS INTEGER))) * child_1.ChildID)
FROM
	Child child_1

