BeforeExecute
-- SqlServer.2016.MS SqlServer.2016 (asynchronously)

SELECT
	IIF(EXISTS(
		SELECT
			*
		FROM
			[Parent] [p]
		WHERE
			[p].[ParentID] = 2 AND (COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END) = [p].[Value1] OR COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST(N'-1' AS INT) END) IS NULL AND [p].[Value1] IS NULL)
	), 1, 0)

