BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "UserDTO"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "UserDTO"
		(
			"UserId"   Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"UserName" NVarChar(255)                                  NULL,

			CONSTRAINT "PK_UserDTO" PRIMARY KEY ("UserId")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "UserPositionDTO"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "UserPositionDTO"
		(
			"UserPositionId" Int GENERATED ALWAYS AS IDENTITY NOT NULL,
			"UserId"         Int                              NOT NULL,
			"PositionId"     Int                              NOT NULL,

			CONSTRAINT "PK_UserPositionDTO" PRIMARY KEY ("UserPositionId")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE UPS';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE UPS
		(
			"UserPositionSectorId" Int GENERATED ALWAYS AS IDENTITY NOT NULL,
			"UserPositionId"       Int                              NOT NULL,
			"SectorId"             Int                              NOT NULL,

			CONSTRAINT PK_UPS PRIMARY KEY ("UserPositionSectorId")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "PositionDTO"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "PositionDTO"
		(
			"PositionId"   Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"PositionName" NVarChar(255)                              NOT NULL,

			CONSTRAINT "PK_PositionDTO" PRIMARY KEY ("PositionId")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "SectorDTO"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
	EXECUTE IMMEDIATE '
		CREATE TABLE "SectorDTO"
		(
			"SectorId"   Int           GENERATED ALWAYS AS IDENTITY NOT NULL,
			"SectorName" NVarChar(255)                              NOT NULL,

			CONSTRAINT "PK_SectorDTO" PRIMARY KEY ("SectorId")
		)
	';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"m_1"."SectorId",
	"a_User"."UserId"
FROM
	"SectorDTO" "m_1"
		INNER JOIN UPS "d" ON "m_1"."SectorId" = "d"."SectorId"
		INNER JOIN "UserPositionDTO" "a_UserPosition" ON "d"."UserPositionId" = "a_UserPosition"."UserPositionId"
		INNER JOIN "UserDTO" "a_User" ON "a_UserPosition"."UserId" = "a_User"."UserId"
WHERE
	"a_UserPosition"."PositionId" = 1

BeforeExecute
-- DB2 DB2.LUW DB2LUW

SELECT
	"x"."SectorId"
FROM
	"SectorDTO" "x"

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "SectorDTO"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "PositionDTO"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE UPS';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "UserPositionDTO"';
END

BeforeExecute
-- DB2 DB2.LUW DB2LUW

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE "UserDTO"';
END

