SELECT
	[p].[FIRST_NAME],
	5,
	5000 + LENGTH([p].[FIRST_NAME]) * 10
FROM
	[PERSON] [p]
WHERE
	[p].[FIRST_NAME] <> '' OR [p].[FIRST_NAME] IS NULL

SELECT
	[q].[FIRST_NAME],
	5000 + LENGTH([q].[FIRST_NAME]) * 10
FROM
	[PERSON] [q]
WHERE
	[q].[FIRST_NAME] <> '' OR [q].[FIRST_NAME] IS NULL

