-- ClickHouse.Octonica ClickHouse

SELECT
	EXISTS(
		SELECT
			*
		FROM
			Parent p
		WHERE
			p.ParentID = 2 AND (p.Value1 = COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END) OR p.Value1 IS NULL AND COALESCE(CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END, CASE WHEN NULL IS NULL THEN NULL ELSE CAST('-1' AS INT) END) IS NULL)
	)

