BeforeExecute
-- ClickHouse.Octonica ClickHouse

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				AllTypes p
			WHERE
				p.ID = 2 AND (p.intDataType = COALESCE(CASE WHEN p.varcharDataType IS NULL THEN NULL ELSE CAST('7777777' AS INT) END, CASE WHEN p.varcharDataType IS NULL THEN NULL ELSE CAST('7777777' AS INT) END) AND p.intDataType IS NOT NULL AND COALESCE(CASE WHEN p.varcharDataType IS NULL THEN NULL ELSE CAST('7777777' AS INT) END, CASE WHEN p.varcharDataType IS NULL THEN NULL ELSE CAST('7777777' AS INT) END) IS NOT NULL OR p.intDataType IS NULL AND COALESCE(CASE WHEN p.varcharDataType IS NULL THEN NULL ELSE CAST('7777777' AS INT) END, CASE WHEN p.varcharDataType IS NULL THEN NULL ELSE CAST('7777777' AS INT) END) IS NULL)
		)
			THEN true
		ELSE false
	END

